### ISSUE TITLE
Support starting a game at a set time

### ISSUE THREAD

**Issue by gsingh93** [facebook/fbctf#10]
At the moment you have to click "Begin Game" manually to start a game. We should add a feature to set the start time and a duration or end time, and have the game automatically start at the start time.

**Comment by dylanjacob** [comment]
👍

**Comment by constance628** [comment]
Where to click "Begin Game" manually to start a game?
TIMER of Configuration only GAME DURATION can be set, did I miss something?

**Comment by mpomarole** [comment]
@constance628 you want to be clicking on the button highlighted to being game:
<img width="1396" alt="screen shot 2016-05-14 at 19 52 30" src="https://cloud.githubusercontent.com/assets/333924/15270166/7d4fcd92-1a0d-11e6-919a-e936024e39c1.png">

**Comment by gsingh93** [comment]
@javuto should we move that to "Controls" instead?

**Comment by constance628** [comment]
@mpomarole Thank you, I didn't notice that there is a scroll bar beside main menu....

**Comment by dylanjacob** [comment]
But what about setting a time in the future for the game to automatically start without having to have a person actually click "Begin Game"?  If I wanted to schedule for, say 9:00am tomorrow, and then  allow people to register today, how would I accomplish that?

My suggestion would be to have a radio on/off for "Start: immediately/future" and then when future is selected show a date/time picker for the future date/time.  Once that is entered and saved, the clock that appears when you click play would count down to 9:00am tomorrow and the page would refresh at 0 to allow users who have already logged in to enter the game at almost the same time.

**Comment by gsingh93** [comment]
> But what about setting a time in the future for the game to automatically start without having to have a person actually click "Begin Game"?

That's what this issue is for.

**Comment by colbyjoe1919** [comment]
We can't play these games people I know it's a long shift but the end
processes are going to invoke torture and collect data themselves.  We have
a dark Lord to satisfy.  Let get serious here.

**Comment by juliannagler** [comment]
Relevant to #392 - automation is coming

**Comment by juliannagler** [comment]
Addressed in #449
