### ISSUE TITLE
How to know username and password i tried admin:password

### ISSUE THREAD

**Issue by darkclownstein** [facebook/fbctf#101]

**Comment by mehnomy** [comment]
You are provided a admin password when you run the provision script, as the instructions tell you:

> The password for the user admin will be printed in the console at the end of provisioning, as it is randomly generated everytime the CTF platform is provisioned.

Regards,
Byron

**Comment by darkclownstein** [comment]
THANKS! Can I change it?

**Comment by mehnomy** [comment]
> We will add a way to change this password from the command line in the near future (in the meantime, you can figure out how to do it manually by looking at the import_empty_db function in ./extra/lib.sh.

If you have any other issues please reply back here in your own issue.

Regards,
Byron

**Comment by darkclownstein** [comment]
@mehnomy i got this error
Login incorrect

**Comment by mehnomy** [comment]
@darkclownstein Could you please upload a screenshot to [Imgur](https://imgur.com)

Regards,
Byron

**Comment by killer123246** [comment]
I can login perfectly,please check your login and password again
