### ISSUE TITLE
What does -DEC do?

### ISSUE THREAD

**Issue by JamieH** [facebook/fbctf#102]
Both quizes and normal challenges have a `-DEC` - What is this? It doesn't appear to be in the documentation?

**Comment by tbowman01** [comment]
It appears to decrement the bonus for each wrong answer.  ie.  If you were to set the bonus to 30 points and the decrement to 10 then for each wrong answer the bonus would decrease.

**Comment by gsingh93** [comment]
@javuto can you document this in the wiki?

**Comment by rdenman** [comment]
This above answer is actually incorrect. DEC decreases the BONUS awarded to a team depending on the number of teams that have already answered a question.

For example, if a challenge is worth 50 points and has BONUS=10 and DEC=5, then the first team to correctly solve a challenge (regardless of the number of attempts it takes) will receive 60 points, the second team to solve it will receive 55 points, and every team after that will receive 50 points.

**Comment by gsingh93** [comment]
Yes, @rdenman's answer is correct (sorry I forgot to answer it myself). In CTFs, this is called getting points for "first blood".

**Comment by juliannagler** [comment]
More info on this can be found on [Admin Guide](https://github.com/facebook/fbctf/wiki/Admin-Guide) in the wiki.
