### ISSUE TITLE
what should I do? I think it's not complete

### ISSUE THREAD

**Issue by darkclownstein** [facebook/fbctf#103]
![Uploading error.png…]()

**Comment by mehnomy** [comment]
You need to explain your situation a little more, we can't help with such little information.

can you please copy and paste the output of the provision script so we know what other errors you're having, you also have another issue opened has that been resolved:
https://github.com/facebook/fbctf/issues/101

Kind Regards,
Byron Fisher

**Comment by darkclownstein** [comment]
Complete! I run Facebookctf on firefox browser. But it should be run on vm right?
![fbctf](https://cloud.githubusercontent.com/assets/19530586/15524714/57ac4546-2257-11e6-84ff-975f2a05db33.png)

**Comment by mehnomy** [comment]
@darkclownstein its up to you where you want to create the environment, we suggest using a Virtual Machine so it can easily be switched on and off when not in use. We also recommend using a VM as the challenges wouldn't be accompanied with the same server/machine for hacking purposes (the challenges) or anything which could damage the platform.

**Environment Setups:**
- If you're just wanting to learn & create by yourself or with a few friends on the same network then your current setup will work perfectly fine. 
- More then just a few friends, or don't want to be having to be in the same room &/or network then i would recommend getting a VPS.

Not sure what your intentions are with the platform but if you need any help/suggestions please feel free on replying, else you can close this ticket/issue.

Kind Regards,
Byron

**Comment by darkclownstein** [comment]
Well i dont have any friends that has interest in this. Do you have any suggestion? Thanks in advance 😊

**Comment by mehnomy** [comment]
@darkclownstein I'm not quite sure whether you have any coding abilities, though i do see that you're using a Linux OS (Ubuntu) on your personal computer so you may have some.

**If you want to learn how to code there are some really cool free websites and resources out there:**

**Code Academy:**
Code Academy is a really fun and interactive learning environment which has on offer HTML, CSS, PHP, Python, Java, Javascript, Angular JS, Jquery, Ruby, Ruby on Rails, they even teach you how to use Popular APIs and how to use Git!
https://www.codecademy.com

**w3Schools:**
We utilize this with our students at RMIT, its the togo to website when you're in need of help as it provides examples which you can edit and preview.
http://www.w3schools.com

**If you want to learn a language like C i would suggest reading books like:**
- The C Programming Language by Brian W. Kernighan, Dennis M. Ritchie
- C Programming: A Modern Approach by K.N. King 


I'm not quite sure you understand what you have just installed so this is a quote from [Facebooks Note](https://www.facebook.com/notes/facebook-ctf/facebook-ctf-is-now-open-source/525464774322241):
> So, we built a free platform for everyone to use that takes care of the backend requirements of running a CTF, including the game map, team registration, and scoring. 

If you want to pursue a career in the I.T Industry in particular Security i would suggest starting off with a language like Python, if Security is not your thing then maybe tell me what you're interested in and i can try and help you out.

Regards,
Byron

**Comment by darkclownstein** [comment]
Well im 1st yr college 17yrs'old IT student from the Philippines and i have some "BASIC" idea on computer programming language like Java and webprogram html css js php. I have windows 10, ubuntu, and also kali linux triple boot(i also want to become a e IT Security XD lol, but idont have enough knowledge) i dont have my own internet connection but my neighbors does. Thats why i have kali linux and fluxion(wifi tools i downloaded here in github installed in kali) hahaha sorry i say too much

**Comment by javuto** [comment]
@darkclownstein it seems like you have the platform running now, nice! The next step will be to add challenges if you want to run a competition yourself. There are some examples here: https://github.com/facebook/fbctf/tree/master/demo_levels
If you want to focus in Security, I'd suggest you to take a look at other available CTFs, you can get a list in https://ctftime.org/event/list/upcoming or also participate in Bug Bounty programs.
@mehnomy thanks for the help!

**Comment by killer123246** [comment]
Yes it should
But how did u run it as a website,I don't have much time to use the
computer cuz I have school so.... I don't know why is it possible to run it
like this

[image: fbctf]

**Comment by mehnomy** [comment]
@killer123246 could you please make your own issue, as provide more information have you tried following [my wiki for Production mode](https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki).

- If creating a new issue information which would help us: the output of the provision script, any errors you seen, and make sure your running Ubuntu 14.04 it MUST be 64bits all of this information and more is in my wiki.

Regards,
Byron
