### ISSUE TITLE
Admin Panel not logging me in

### ISSUE THREAD

**Issue by FinlayDaG33k** [facebook/fbctf#104]
Hii There,

Today I decided to install fbctf on my own server so that I can play with some of my friends, but after the installation, I can't login into the admin panel.

I go to `login` and enter these credentials:
team name: `admin`
password: `the password given by the provisioning script`

It does not show up the red text meaning that the password is incorrect, but instead it redirects me to the index page.

Upon a little bit of investigation, I noticed this in the network tab Firefox:
status: `302`
Method: `GET`
File: `index.php?page=admin`
Domain: `10.0.0.124`
Type: `html`

I have edited the nginx configuration (`/etc/nginx/sites-enabled/fbctf.conf`) a little bit so that it wouldn't have to use HTTPS as I am just going to play with some of my friends and I don't want to pay for a SSL certificate.

**Comment by mehnomy** [comment]
Two Options since you don't want to pay:
- You can get a free SSL certificate from: http://letsencrypt.org
- Use a self signed certificate you will get a warning that its not a trusted SSL certificate when loading the page, click advance and then click continue to website.

Kind Regards,
Byron Fisher

**Comment by FinlayDaG33k** [comment]
Thanks for your reply.
I will try to use letsencrypt.

Also, does fbctf really need HTTPS? (because then I can keep that in mind for next time)

**Comment by gsingh93** [comment]
We have not tested without HTTPS, but I believe you'll need to make some modifications to run it without HTTPS.

We want to make running CTFs as easy as possible, but we also want to make sure the CTFs are run securely, so we force SSL by default. That being said, we're working on Let's Encrypt integration so users don't need to worry about any of that in the future.

**Comment by FinlayDaG33k** [comment]
ah okay,
It works now so thanks :)
