### ISSUE TITLE
I got a blank web page....

### ISSUE THREAD

**Issue by arphanetx** [facebook/fbctf#106]
I follow the guide from @mehnomy ( https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki/Installing-FBCTF ) is really useful, all goes good, ubuntu 14.04 server x64, follow step by step, after all the installation, when i try to reach https://myip it connect, i saw the ports listening in 80 and 443, also when i connect to https://myip it only shows a blank page.

the nginx is running, the hhvm, so i do not know what else is wrong. 

thanks for the help.

**Comment by javuto** [comment]
What do you get if you do ```curl -vk https://localhost``` in the same machine where you installed it?

**Comment by mehnomy** [comment]
@arphanetx are you still have any issues, if not could you please inform us on what your solution was for others to read and if you don't mind closing the issue.

Regards,
Nomy
