### ISSUE TITLE
Clearing FacebookCTF message after login to tty1

### ISSUE THREAD

**Issue by adipginting** [facebook/fbctf#109]
I tried to install fbctf on my local Ubuntu machine, non vagrant. It turned out I can't make it successfully. I have uninstalled most of the leftovers but something is still there. The FacebookCTF message appears every time I login to tty1. Any thought to remove it?

**Comment by mehnomy** [comment]
read what the provison script installs and uninstall them.

Regards,
Byron

**Comment by javuto** [comment]
@adipginting that message is set as MOTD. The code that does that is in the function ```set_motd``` here: https://github.com/facebook/fbctf/blob/master/extra/lib.sh#L48
To remove the facebookCTF message just remove ```/etc/update-motd.d/10-help-text``` and it will be gone in the next login.

**Comment by adipginting** [comment]
Thanks @mehnomy. I did like what @javuto said. It worked.
