### ISSUE TITLE
mysqld not (re)started during installation

### ISSUE THREAD

**Issue by r0p0s3c** [facebook/fbctf#116]
As per #69, mysqld is installed but not started by extra/lib.sh, leading to the installation failing. As per the comments in that issue, please consider adding a "sudo service mysql restart" in install_mysql.

**Comment by gsingh93** [comment]
MySQL should start automatically. Running `sudo apt-get install mysql-server` on an Ubuntu 14.04 Vagrant VM gives me this at the end of the output:

```
160601 19:21:55 [Note] /usr/sbin/mysqld (mysqld 5.5.49-0ubuntu0.14.04.1) starting as process 12944 ...
mysql start/running, process 13076
```

**Comment by r0p0s3c** [comment]
Interesting. I see, after that line:

`invoke-rc.d: policy-rc.d denied execution of start.`

This is running in a container (ubuntu:trusty) via docker. May be worth documenting this issue somewhere.

**Comment by gsingh93** [comment]
Interesting, thanks for the details. We should have docker containers soon, so we'll investigate more then.

**Comment by javuto** [comment]
This was implemented here https://github.com/facebook/fbctf/commit/a07b27b8a192dc6c9e2416ddf4bb056f001ef43c
