### ISSUE TITLE
LDAP integration for Team Login

### ISSUE THREAD

**Issue by nikhilgeo** [facebook/fbctf#126]
Hi,
I'm planning to use fbctf to conduct a CTF. But I like to integration the team registration with LDAP. 
It will be very helpful if you can point me which files need the change...I'm pretty new to php and hack....
Thanks in advance..

**Comment by javuto** [comment]
@nikhilgeo, all the code for registration and login lives here: https://github.com/facebook/fbctf/blob/master/src/controllers/ajax/IndexAjaxController.php
You can probably replace those by your own code to integrate LDAP login and create the session, after that, everything else should work fine. Let us know how that goes!

**Comment by secursive** [comment]
I had already added LDAP support for a local team CTF in my fork (https://github.com/secursive/fbctf). Recently I created a pull request (https://github.com/facebook/fbctf/pull/284) to merge that fork back to the master branch. If there is a demand for this feature, consider my pull request. If anyone wants to try it out, clone directly from my fork and check it out.
