### ISSUE TITLE
Access the Ubuntu 14.04 VM

### ISSUE THREAD

**Issue by cadewolcott** [facebook/fbctf#129]
I have FBCTF up and running on localhost in dev mode, however I cannot find the correct credentials for the virtual box. Any help?

**Comment by javuto** [comment]
Did you use vagrant for setting up the virtual machine? If so, from the fbctf folder, you can run ```vagrant ssh``` and it will connect to your development Ubuntu virtual machine. If you want to connect to that machine, you can see what is the SSH configuration used with the command ```vagrant ssh-config```

**Comment by cadewolcott** [comment]
Yes I used vagrant and will try what you suggested!
