### ISSUE TITLE
Error with hhvm

### ISSUE THREAD

**Issue by louMacias** [facebook/fbctf#132]
I have been trying to get fbctf to work with vagrant up and I keep receiving an error:
 /usr/bin/hhvm: error while loading shared libraries: libdouble-conversion.so.1: cannot open shared object file: no such file or directory 
Then two lines down there is another error:
php: error while loading shared libraries: libdouble-conversion.so.1: cannot open shared object file: no such file or directory
Curl: (23) failed writing body (0 != 16133
I am stuck with trying to get this to work. Any help would be appreciated thanks

**Comment by gsingh93** [comment]
There is a recent bug in HHVM. Did you clone today or some time before today? @javuto committed a fix earlier today: https://github.com/facebook/fbctf/commit/61a8e4f7afa729d08a0159b3b700b5343f451cb5

**Comment by louMacias** [comment]
@gsingh93 I cloned one yesterday. I will try a new clone and see how it goes.

**Comment by louMacias** [comment]
@gsingh93 It works. Thank you so much for responding me and letting me know. And Thank you @javuto for the fix
