### ISSUE TITLE
I got a blank web page

### ISSUE THREAD

**Issue by devkell** [facebook/fbctf#133]
I follow the guide from @mehnomy ( https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki/Installing-FBCTF ) is really useful, all goes good, ubuntu 14.04 server x64, follow step by step, after all the installation, when i try to reach https://myip it connect, i saw the ports listening in 80 and 443, also when i connect to https://myip it only shows a blank page.

the nginx is running, the hhvm, so i do not know what else is wrong.

thanks for the help.

**Comment by javuto** [comment]
Are you running the platform in a machine with direct Internet access? What happens when you try to access ```https://127.0.0.1```? Can you run in the command line from that machine the command ```curl -k https://127.0.0.1``` and see what happens?

**Comment by benichmt1** [comment]
I had a similar issue and can confirm that it was running on 127.0.0.1.
I think his issue stems from the hardcoded IP in provision.sh

https://github.com/facebook/fbctf/blob/16cc965c3242a2c94ba45d02e64d65324d2ef1fb/extra/provision.sh#L235


<code>

ok_log 'fbctf deployment is complete! Ready in https://10.10.10.5'
</code>

**Comment by mehnomy** [comment]
@devkell seems to have resolved he's initial issue as he's asking questions via:
https://github.com/mehnomy/FBCTF-Ubuntu-Setup/issues/2

@benichmt1 are you still having an issue?
 - we are quite aware of the hardcoded IP as its used within the development so users can get familiar with the environment.

Depending on what type of environment you're running the in FBCTF the IP address will be different, however if you're testing it within a virtual sandboxed environment then 127.0.0.1 or localhost will work just fine. Else using ifconfig and locating the IP address of the machine if you're utilising a VPS or a Dedicated Server for instance and accessing the platform from a external machine.
- e.g something like https://challenge.rmit.me and accessing it from your own machine, the sub domain is pointed at the machines public IPv4 address.

Regards,
Byron

**Comment by benichmt1** [comment]
@mehnomy no, I am totally fine. I was just guessing what the OP was struggling with. I just followed the output link from the script mindlessly and saw what I think he saw.

**Comment by jeff350** [comment]
after I initially setup my instance all I was able to see was a blank page. After some playing around I found that the issue was that I was using an add blocker in my browser. AdBlock Plus will not allow any content to be rendered on the page. This could be one possible cause.

**Comment by mehnomy** [comment]
@jeff350 

I'm quite curious what Browser are you using with your AdBlock Plus?
- Are you able to load https://challenge.rmit.me/ on that browser with AdBlock Plus active?

Regards,
Byron

**Comment by jeff350** [comment]
@mehnomy  

I was able to replicate this on your site on a new virtual machine. This was using Firefox 47.0 and AdBlock Plus. On your site I was able to see the navbar but not any content. 

The exact issue I had was using Fanboy's Social Blocking list that is built into Adblock Plus, and some other add blockers. their homepage is https://easylist.github.io/index.html

Jeff
