### ISSUE TITLE
Request to access Private Repo

### ISSUE THREAD

**Issue by no1rscyber** [facebook/fbctf#134]
I emailed in sometime ago now to request access to the Private Repo for an event we are running later in the year.

Now either you have been inundated with requests, decided not to respond or not received my email.

A response either way would be appreciated.

**Comment by tbowman01** [comment]
I received a response within a week; around the middle of May and the comment in the email was: 

> "We’re putting the final touches on the challenges this week, and will begin adding folks who’ve requested access as soon as possible. "

I have not seen any action on this since the email.

**Comment by hackmethod** [comment]
@tbowman01, It's good to know they are responding and not just ignoring or being slammed with access requests.  Thanks.

@everyone, In addition to the FBCTF repo, I am also looking for individuals to build challenges, mainly web and RE.  If there is a network of hidden talented people like this that exist, I would like to find them.

**Comment by juliannagler** [comment]
Hey @no1rscyber - So sorry for the radio silence! We've indeed received exponentially more requests than we had expected (which is a great problem to have). Reguardless of that, we’ve decided to take a step back to completely revamp our challenges repo, adding more clarity and additional choice in difficulty and category. We hope to have the challenges ready for distribution in the coming weeks, at which point we’ll grant access to those who've requested it. We apologize for the delay!

**Comment by no1rscyber** [comment]
No worries and thanks for responding. I have generated about 2 to 3 hours worth of activity for my platform already and look forward to expanding it further.

**Comment by ShubhamAgarwal96** [comment]
Hello , 

I also wanted to know If I can be given access to the private repo. I have alreadt emailed the dev team with all the necessary information. Though our team has made many challenges but we wished if we can have some expert help. 

TIA
