### ISSUE TITLE
Unable to Login to VirtualBox Command Line

### ISSUE THREAD

**Issue by rdenman** [facebook/fbctf#136]
I have the platform working on my host OS and I'm able to login and edit the configurations through the site, but I have not been able to login to the guest OS. Every time I try to login, I am told that the login is incorrect. As far as I've been able to find, the login should be username=admin and password=password for the development environment. Am I using incorrect credentials?

**Comment by rdenman** [comment]
sorry, I had not noticed that this issue was opened and solved a few days ago

**Comment by rdenman** [comment]
After lots of guesswork, I found that I was able to login to the development environment using the username 'vagrant' and the password 'vagrant' - I'm assuming these are the defaults. Before doing so, I ran the commands 'vagrant ssh' and 'vagrant ssh-config' - though I'm not sure if these were necessary to create the login credentials.

**Comment by gsingh93** [comment]
The proper way to log in to the vagrant VM is to run `vagrant ssh` on the command line in the fbctf folder. I haven't had time to add this to the README yet, but I plan to do so.
