### ISSUE TITLE
Problems with changing ip address in VagrantFile

### ISSUE THREAD

**Issue by cadewolcott** [facebook/fbctf#139]
I try changing the ip address in my VagrantFile to my private ip, but when running vagrant up I got the following error:

The specified host network collides with a non-hostonly network!
This will cause your specified IP to be inaccessible. Please change
the IP or name of your host only network so that it no longer matches that of
a bridged or non-hostonly network.

Any help?

**Comment by javuto** [comment]
The IP address assigned to the vagrant box can not be the same as your machine. Those are two separate machines. If you want your machine to be accessed as the CTF platform, you can setup port forwarding. Here is a good guide on how to do it: https://www.vagrantup.com/docs/networking/forwarded_ports.html
