### ISSUE TITLE
Error starting up vm?

### ISSUE THREAD

**Issue by SimPlaysGames** [facebook/fbctf#141]
Hey, I am using trying to set this up, on a windows system using virtualbox, but when I run the command "vagrant up" in the fbctf directory. But I get this error:

http://pastebin.com/VHXaZ1tg

==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
 
Command: ["startvm", "e37cfb98-0bab-4823-aca9-7bfcb8495164", "--type", "headless"]
 
Stderr: VBoxManage.exe: error: The virtual machine 'fbctf_default_1466268322422_85770' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\Simen\VirtualBox VMs\fbctf_default_1466268322422_85770\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

**Comment by mehnomy** [comment]
@SimPlaysGames 

Since you're using a Virtual Machine, you could try using my Guide if you create a new sandboxed environment with Ubuntu 14.04 64x on it.

[The Guide](https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki)

Regards,
Byron

**Comment by paulmar** [comment]
Can you run other VMs? Doesn't seem to be a fbctf problem. See http://superuser.com/questions/785072/e-fail-0x80004005-when-running-linux-through-windows-8-virtualbox or ask Google for possible solutions.

**Comment by javuto** [comment]
I had the same issue in OSX, and closing the terminal fixed the problem.
