### ISSUE TITLE
How to upload the fbctf to GoDaddy Hosting?

### ISSUE THREAD

**Issue by atoooooooooom10** [facebook/fbctf#142]
Hi,

It was my first time to work with VM and Vagrant and I managed to make the FBCTF work on my windows. Now, I'd like to know how to make it run on my domain, I am using GoDaddy Hosting.
Would like to run a CTF for our school. Yep, Can't find any tutorial in the google.

Thanks for taking the time to read this.

Cheers,
Allan

**Comment by mehnomy** [comment]
hello @atoooooooooom10 

What kind of GoDaddy Hosting do you have, is it shared hosting or VPS?
- if its shared, you won't be able to host FBCTF on it.

You require a VPS or a Dedicated Server with Ubuntu 14.04 64x OS.

[Server Requirements](https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki/Server-Requirements)

Regards,
Byron

**Comment by atoooooooooom10** [comment]
hi @mehnomy 

Thanks for your response.
I bought this [Ultimate Hosting(for Linux)](https://ph.godaddy.com/hosting/web-hosting) but I don't know if it's a Shared Hosting or VPS. 

Thanks,
Allan

**Comment by mehnomy** [comment]
@atoooooooooom10 if you have purchased Ultimate Hosting from GoDaddy solely for FBCTF i would recommend getting a refund as that is Shared Hosting not a VPS, else if you have also purchased it for your own use then well don't get a refund 👍 

Regards,
Byron

**Comment by atoooooooooom10** [comment]
Oh! Thanks, @mehnomy.

**Comment by mehnomy** [comment]
@atoooooooooom10 

If i have answered all your questions regarding this issue please close the issue.

Regards,
Byron

**Comment by sangat96** [comment]
Hey Byron, I would like to know how to host fbctf on a vps.. Can you just tell me the steps??
