### ISSUE TITLE
Unable to upload attachment files

### ISSUE THREAD

**Issue by no1rscyber** [facebook/fbctf#145]
The actual files although listed in the level don't seem to actually upload to the server resulting in an "An error occurred"

Help appreciated.

**Comment by no1rscyber** [comment]
Sorted, just need to change the permissions on the attachments folder.

**Comment by Hestat** [comment]
I know this is closed, I am trying the fix on my test machine, but it does not seem to be working, am I changing the right directory permissions, running as a docker container changing the perm on /fbctf/src/data/attachments
