### ISSUE TITLE
Challenge Repo

### ISSUE THREAD

**Issue by no1rscyber** [facebook/fbctf#146]
Has anybody setup any challenges on their platforms yet that they have shared in the public domain?

We have about 23 flag levels and around 30 quiz levels which equals about 3 hours or so worth of content.

Would be useful to have a "Challenge Ideas" or something of this ilk so that other platform administrators can get some inspiration on creating more content.

We have run a couple of comps so far with good results.

**Comment by devkell** [comment]
it would nice too for you to share what you have done so far, that other people can comment and share some improvements based on what you have planned.

**Comment by devkell** [comment]
through i agree with you, that is a very good idea

**Comment by gsingh93** [comment]
The problem with making our challenges public to everyone, is that we're able to reuse them for multiple local CTFs. For example, we can use the challenges at two different University CTFs, where there is no chance of someone being at both CTFs.

For ideas for flag levels, there are already many challenges posted online, like [this site](http://captf.com/) and some Github repos that contain [solutions](https://github.com/ctfs/write-ups-2016).

**Comment by no1rscyber** [comment]
I of course understand that making challenges public might cause some crossover on multiple events but that wasn't really what I was getting at. 

Its all about ideas and inspiration in order for organisers to create content that's fresh and both challenging at the same time.

I am looking forward to seeing what the FBCTF Team have in their private repo soon.

This may spur me on to create my own repo of ideas?

Thanks for your comments.

**Comment by Ttech** [comment]
There is actually one going live for FBCTF and CTFd soon, I'll post details in the next few days. The idea behind it is to allow quick setup of CTF competitions for use internally or for small events.

**Comment by no1rscyber** [comment]
Great, I have some forward looking plans to implement this platform in various projects Im working on so Im looking forward to this.

Thanks very much.
