### ISSUE TITLE
up and running but clients cannot log in

### ISSUE THREAD

**Issue by kiwiruss** [facebook/fbctf#147]
I have the CTF up and running. clients can get the login screen but every attempts to log in fails.

**Comment by kiwiruss** [comment]
Local login works on the system but anyone on the same network but a different physical machine cannot get past the login screen.

**Comment by no1rscyber** [comment]
I know this sounds like a basic suggestion but can you login with admin on different machines not just locally. When you say locally do you mean logging onto the actual server?

**Comment by gsingh93** [comment]
Is login failing for the admin account or other registered accounts. If it's for the admin account, make sure your password is correct. Did you provision in dev or prod mode?

**Comment by kiwiruss** [comment]
I can open a web browser on the system running vagrant and the VM and login with the admin login. But from other physical systems we can use a browser to get to the login page but login failed as user or admin.

**Comment by kiwiruss** [comment]
I know its HTTPS so is it possible a SSL cert issue ?

**Comment by kiwiruss** [comment]
My co worker fixed the issue and its up and running and accessible. turns out it was a issue with the password and having to put it into production mode.  this issue can be closed. thanks
