### ISSUE TITLE
Facts without vagrant

### ISSUE THREAD

**Issue by kiwiruss** [facebook/fbctf#148]
Is it possible to run facts without vagrant, just get a native fm up and running to connect to.

**Comment by javuto** [comment]
I believe what you are looking for is the provisioning in a production environment. You can provision the fbctf platform using a self-signed certificate, generate a new one using let's encrypt or use your own. Check out the README or follow this guide on how to do this: https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki
