### ISSUE TITLE
babys_first_bof.c: unable to compile due to error in line 11

### ISSUE THREAD

**Issue by divancorp** [facebook/fbctf#149]
I'm unable to create babys_first_bof binary file due to below error. 
I have modified code to fgets but then I get different error due

As-IS code error: 
vagrant@facebookCTF-Dev:/var/www/fbctf/demo_levels/babys_first_bof$ make all
gcc -m32 -fno-stack-protector -U_FORTIFY_SOURCE -fno-stack-protector -z execstack -mpreferred-stack-boundary=2 -w babys_
first_bof.c -o babys_first_bof
/tmp/ccj2jibD.o: In function `main':
babys_first_bof.c:(.text+0x50): warning: the `gets' function is dangerous and should not be used.

modified fgets error

vagrant@facebookCTF-Dev:/var/www/fbctf/demo_levels/babys_first_bof$ make all
gcc -m32 -fno-stack-protector -U_FORTIFY_SOURCE -fno-stack-protector -z execstack -mpreferred-stack-boundary=2 -w babys_
first_bof.c -o babys_first_bof
babys_first_bof.c: In function ‘main’:
babys_first_bof.c:11:5: error: too few arguments to function ‘fgets’
     fgets(buffer);
     ^
In file included from babys_first_bof.c:2:0:
/usr/include/stdio.h:622:14: note: declared here
 extern char *fgets (char *__restrict __s, int __n, FILE *__restrict __stream)
              ^
make: *** [all] Error 1

**Comment by gsingh93** [comment]
The first "error" is a warning, not an error.
