### ISSUE TITLE
Can't change admin password

### ISSUE THREAD

**Issue by SlayterDev** [facebook/fbctf#151]
Using the script to change the admin password like so:

    ./extra/lib.sh set_password password ctf ctf fbctf $PWD

does nothing.

**Comment by gsingh93** [comment]
I tested this recently and it worked fine. Is this in dev install or a prod install? A VM or a physical Ubuntu 14.04 machine? Do you see any errors, or are you simply unable to login with the new password? Were you able to login before you reset the password?

**Comment by SlayterDev** [comment]
Production, physical Ubuntu 14.04 machine. No output of any kind from the script. I was able to login before reseting the password. However resetting the password from the website still works.

**Comment by gsingh93** [comment]
> However resetting the password from the website still works.

What do you mean by "resetting from the website"? Do you mean after you try to reset, you can log in with the original password?

Here's a test you can run. Run `mysql -u ctf -p fbctf`, and when prompted for the password type `ctf`. Then run `select * from teams;`. Note the value in the `password_hash` field. Now try running the password reset script. Run the `select * from teams;` command again. Did the password hash change?

**Comment by assazzin** [comment]
use following commands after enter 'fbctf' folder.
There are 2 commands.

```
. ./extra/lib.sh
set_password password ctf ctf fbctf $PWD
```

**Comment by wpaisk** [comment]
In the interface of the teams configuration team1 you can set the name of the administrator and password, if it is with the command configuration, with the following two:./extra/lib.sh (two points between a space)
Password CTF CTF fbctf $PWD set_password

**Comment by Joeyn414** [comment]
When I enter the command for setting the password on a production install (set_password mynewpassword admin old_password fbctf $PWD) I get an error: ERROR 1045 (28000): Access denied for user 'admin'@'localhost' (using password:YES). It actually prints this error twice. How do I change the password from the one thats generated for the production install?

Side question, I cant seem to access the admin portal, I can get to the page just fine, I type in admin and the generated password, it appears to accept the login but doesnt bring me anyway. I tried to hardcode the php?p=admin but it doesnt seem to bring me to an admin portal. Is there something else I need to enable? If there are instructions I am not finding in the github page please tell me but I cant seem to find it. Thanks so much for your help!!

**Comment by gsingh93** [comment]
For your first question, are you sure you can login with `mysql -u admin -p` followed by typing `old_password`? The error seems to indicate that's failing.

For the second question, try checking `/var/log/hhvm/error.log` to see if there are any errors there that show what the problem is.

**Comment by Joeyn414** [comment]
When I tried to login to mysql as described above I get the same error.
I've reinstalled the entire fb CTF setup on another Ubuntu vm and I'm still
getting the same error.

I will check the error log and report back what I find. Thanks!

**Comment by Joeyn414** [comment]
@gsingh93 I am not able to login to mysql with admin, but I can with ctf with a password of ctf. I was able to see that there is an "admin" in the teams list too. However after trying to run the password reset command now I cant login to the ctf portal with admin with my old or new password. I can redeploy the server to see if I can then access mysql with the admin account and the generated password and report back.

Here is the error Im seeing in error.log [Thu Jul 28 03:22:10 2016] [hphp] [7874:7f23d67ff700:47:000001] [] #0 /var/www/fbctf/src/Router.php(71): SessionUtils::enforceLogin()\n#1 /var/www/fbctf/src/Router.php(19): Router::genRouteNormal()\n#2 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#3 /var/www/fbctf/src/index.php(19): genInit()\n#4 {main}

**Comment by Joeyn414** [comment]
@gsingh93 After reinstalling the platform as prod but with the -self specificed for self signed cert it seemed to actually work. The command in the readme file doesnt specify one option by default. I also didnt change the generated admin password as I fear this may corrupt the mysql database and not allow me login again. So as far as my question/issues are concerned they are all set. When I login with the admin account it redirects me to the admin portal.

**Comment by wpaisk** [comment]
@Joeyn414 ：Will you install the development model it or mode of production? If the former, then the default account is admin / password, if it is the latter, then the default account is admin and a random number in your installation time! I personally installed development model, so the password is password, and therefore can be used later in order to get rid of this!

**Comment by Joeyn414** [comment]
I installed the prod version but with the default install command and it
didn't seem to work, when I used the prod install but entered the flag for
self signed certs it installed and worked perfectly. Sorry I haven't
updated this until now. I haven't tried to update the password I just use
the randomly generated one as I fear it may corrupt the database as it
appeared to do in previous attempts.
