### ISSUE TITLE
Increase default MySQL connection limit

### ISSUE THREAD

**Issue by gsingh93** [facebook/fbctf#153]
By default, MySQL has an extremely low connection limit. This causes problems with running the CTF with around 100 people, even though the platform can support many more. We should include a `my.cnf` file that sets `max_connections` to a larger number (maybe 1000?), as stated [here](https://dev.mysql.com/doc/refman/5.5/en/too-many-connections.html).

**Comment by javuto** [comment]
I think this is totally reasonable. Given that the default value is 151 (see it with the command ```show variables like "max_connections";```) we can easily and safely put it to 500 at least.

**Comment by javuto** [comment]
We should definitely deploy our own ```my.cnf``` and also enable binary logs.

**Comment by JamieH** [comment]
I used FBCTF for a CTF with around 50 people and had a whole bunch of issues with max_connections. Another solution would be to use persistent connections or connection pooling perhaps?

**Comment by gsingh93** [comment]
We've fixed various performance issues, and we're continuing to do more. After thinking about this issue, I don't think we should make any changes.

max_connections is definitely very low by default, but we shouldn't be overwriting the entire my.cnf file when we provision. The user could have already put a number of tweaks in there and we don't want to override those. Because of that, I'm going to close this.
