### ISSUE TITLE
Streaming of results

### ISSUE THREAD

**Issue by acjcool** [facebook/fbctf#154]
Hi,

Is it possible to access a stream that contains the leader board information during the competition from another platform/app? This is to enable apps to take the feed from FB CTF and make the results available to everybody registered for the event no matter where they are. We will have the leader board on the big screen in the room where the competition is running but there are several rooms and we can then run CTF's with different levels but one app showing the leader board of each CTF game.

Kind regards

**Comment by javuto** [comment]
If you go to https://YOUR_CTF_DOMAIN/data/leaderboard.php there is an endpoint with the current leaderboard in JSON format. It does require authentication though.

**Comment by acjcool** [comment]
Hi, I'm giving up. I can;t get this to work. Any way you can break it down for me a bit further? For example, I've entered the https://..../data/leaderboard.php into my browser but it gives me a page not found error. I've tried to accessing it as a service it nothing there. What am I missing? Please...

**Comment by acjcool** [comment]
Ok, found the answer and it was probably obvious. You have to have a game running to view the leaderboard via the json endpoint. I was trying to view it without having a game running with the thinking that it should display the teams but with 0 points.
