### ISSUE TITLE
Open source CTF problem sets

### ISSUE THREAD

**Issue by LuqiPan** [facebook/fbctf#156]
Thank you for this awesome platform. I'm wondering if it's possible to open source your problem sets for CTFs too? As I think it would definitely help us to bootstrap our own CTFs.

**Comment by no1rscyber** [comment]
Have a look in here, this might help you?

https://github.com/facebook/fbctf/issues/146

**Comment by LuqiPan** [comment]
@no1rscyber thx for the reference, I'll close this issue for now.
