### ISSUE TITLE
Install Enhancements

### ISSUE THREAD

**Issue by Hacktast1c** [facebook/fbctf#157]
Can someone please tell me how to apply updates / enhancements?

TYIA

**Comment by javuto** [comment]
Define updates/enhancements. 
If you mean to have always your code updated, then ```git pull``` is what you are looking for.

**Comment by gsingh93** [comment]
And then after you pull, you can sync your code with either rsync or unison. It should be safe to overwrite all of the old files as well, other than the settings.ini.

**Comment by gsingh93** [comment]
@javuto It might be nice to include a `--update` flag to the provision script, that does the pull and the rsync to the www directory.
