### ISSUE TITLE
Error popup for login failures...

### ISSUE THREAD

**Issue by nikhilgeo** [facebook/fbctf#159]
I was trying to implement an error pop up for failed login with message from JSON response.

I tried invoking the _Modal.loadPopup_ in _function sendIndexRequest_ in /var/www/fbctf/src/static/dist/js/app.js but it's giving an error like **ReferenceError: Modal is not defined**

Is there any initializations or something that need to be done before calling **Modal.loadPopup**  in _function sendIndexRequest_

**Comment by gsingh93** [comment]
Sorry for the delayed response, I somehow missed this issue. You need to import modal.js, like this: https://github.com/facebook/fbctf/blob/master/src/static/js/fb-ctf.js#L6
