### ISSUE TITLE
host ctf

### ISSUE THREAD

**Issue by hyunvis** [facebook/fbctf#160]
Finally, i made the local fbctf system.

but, i want make this for about 50 people that they can see, and solve.

I have domain for this, and server also.

what should i do?

thanks a lot.

**Comment by no1rscyber** [comment]
Would it not be just a case of installing your Ubuntu server o/s and provisioning the server in production? Stick a DNS record in and away you go. Oh, you might have to get some certificates if you are running across the Internet for security purposes but there is lots of information on how to do this by searching around here.

**Comment by javuto** [comment]
There is a great guide on how to desploy the FBCTF platform, written by @mehnomy. You can follow it in a VPS or a AWS machine and you should be good to go: 
https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki
