### ISSUE TITLE
Backing up databases in dev mode

### ISSUE THREAD

**Issue by rdenman** [facebook/fbctf#163]
Is there a way to back up all the challenges and quiz questions I've entered into my development environment without doing a snapshot of the whole platform/challenges? Where is all that information stored? I want to give the platform to a couple other people to load on their machines and play around with before setting up the server.

**Comment by gsingh93** [comment]
You can just dump the database with `mysqldump` and then load it with `mysql` later on. I can provide the exact commands later if you can't figure it out.

[This PR](https://github.com/facebook/fbctf/pull/150) should provide exporting capability from the UI, but I haven't had time to review it yet.

**Comment by rdenman** [comment]
thanks!

**Comment by rdenman** [comment]
For anyone looking for specifics:
-ssh into vm
-run: mysqldump -u ctf -pctf fbctf > fbctf.sql
-sudo mv fbctf.sql /vagrant (if you want to get it off the vm and store on the local machine)
