### ISSUE TITLE
Run `hh_format` on our codebase

### ISSUE THREAD

**Issue by gsingh93** [facebook/fbctf#164]
We should run `hh_format` on our codebase to make sure we have consistent style. We don't necessarily need to accept all the defaults, but we should configure it to our liking and require people run it before making pull requests.

**Comment by gsingh93** [comment]
Ugh, `hh_format` allows absolutely no customization of formatting. We'd have to just go with whatever they use.

**Comment by maydewd** [comment]
Should this still be done, despite no customization?

**Comment by gsingh93** [comment]
I think the way forward here is to run hh_format on the codebase and see how much of their style guide we disagree with. I think it'll be minimal, in which case I think it's worth it to compromise on a few of our style guidelines for the convenience of automatic formatting.
