### ISSUE TITLE
Cant find admin page

### ISSUE THREAD

**Issue by Joeyn414** [facebook/fbctf#172]
When I try to go to https://ipaddress/index.php?p=admin (I have a public facing IP in place of the ipaddress) it redirects to the main page. Can someone please help me figure out how to get to the admin page so I can setup the CTF contest.

**Comment by Tweekzor** [comment]
I am also having the same issue. When I try to visit the adminpanel at https://127.0.0.1/index.php?p=admin I get redirected to the homepage again. I installed fbctf in dev mode on my own vm, ubuntu 14.04 without Vagrant. All the other pages are working fine.
/var/log/hhvm/error.log raises these errors:

`[Wed Aug  3 12:05:44 2016] [hphp] [59568:7fc3cfbff700:21:000001] [] #0 /var/www/fbctf/src/controllers/IndexController.php(679): IndexController->genRenderPage()\n#1 /var/www/fbctf/src/controllers/Controller.php(12): IndexController->genRenderBody()\n#2 /var/www/fbctf/src/Router.php(73): Controller->genRender()\n#3 /var/www/fbctf/src/Router.php(19): Router::genRouteNormal()\n#4 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#5 /var/www/fbctf/src/index.php(17): genInit()\n#6 {main}`
`[Wed Aug  3 12:05:44 2016] [hphp] [59568:7fc3cfbff700:22:000001] [] #0 /var/www/fbctf/src/Router.php(69): SessionUtils::enforceLogin()\n#1 /var/www/fbctf/src/Router.php(19): Router::genRouteNormal()\n#2 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#3 /var/www/fbctf/src/index.php(17): genInit()\n#4 {main}`

**Comment by javuto** [comment]
Are you trying to access the admin page logged in as an admin?

**Comment by devkell** [comment]
On the top you will find the link to login, Just click in and it will direct you to admin login page

**Comment by Tweekzor** [comment]
@devkell Thank you, that seemed to have worked. The readme from the demo levels made it seem I needed to access the admin page directly via the URL. Logging in on the Team Login page redirected me to the admin panel.
