### ISSUE TITLE
Problem with VM customizations

### ISSUE THREAD

**Issue by jarmouz** [facebook/fbctf#173]
Hello,

I try to fix this issue with : 
BoxManage modifyvm "ae956a4e-0c46-408e-bbc5-84580c39ddf7" --memory 1024

But the problem persist.
I need your help 

root@ubuntu:/home/jarmouz/fbctf# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
A customization command failed:

["modifyvm", :id, "--memory", "4096"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "ae956a4e-0c46-408e-bbc5-84580c39ddf7", "--memory", "4096"]

Stderr: VBoxManage: error: Invalid RAM size: 4096 MB (must be in range [4, 3584] MB)
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component SessionMachine, interface IMachine, callee nsISupports
Context: "COMSETTER(MemorySize)(ValueUnion.u32)" at line 415 of file VBoxManageModifyVM.cpp
>

Please fix this customization and try again.

**Comment by srvenkat26** [comment]
@jarmouz 
How did you resolve this issue before closing?
