### ISSUE TITLE
Combine multiple await calls to improve performance

### ISSUE THREAD

**Issue by gsingh93** [facebook/fbctf#175]
In Hack you can `await` multiple functions in parallel for better performance. We should do that in places like [this](https://github.com/facebook/fbctf/blob/master/src/controllers/AdminController.php#L1864) which should improve performance a lot.

**Comment by noraj1337** [comment]
+1

**Comment by justinwray** [comment]
This should be closable given the merge of #325.

cc: @gsingh93
