### ISSUE TITLE
Problem networking

### ISSUE THREAD

**Issue by jarmouz** [facebook/fbctf#176]
Hello,

The Vagrant VM eth0 interface take 10.0.2.15 and the vboxnet0 take 10.10.10.1 

I can't access to the interface from my physical host.

I need your help

**Comment by jarmouz** [comment]
I change eth0 on NAT but i can't access to interface

**Comment by joohanik** [comment]
Why do not you use VirtualBox Port Forwarding?

I am using VirtualBox Port Forwarding used as follows
    Host IP : Your Host System IP, Host Port : 443 --> Guest IP : 10.0.2.15, Guest Port : 443
    MyHost's Safari : https://localhost

**Comment by javuto** [comment]
@jarmouz using VirtualBox port forwarding can be a good solution. For our vagrant configuration we use the private network settings, you can read the documentation here: https://www.vagrantup.com/docs/networking/private_network.html
Make the changes you need in the ```Vagrantfile``` and you should be good to go.
Closing this as it is not an issue within the platform.
