### ISSUE TITLE
Enable Repo Authoritative mode in production

### ISSUE THREAD

**Issue by gsingh93** [facebook/fbctf#183]
The performance gains of [Repo Authoritative Mode](https://docs.hhvm.com/hhvm/advanced-usage/repo-authoritative) are massive. We should enable this by default on production builds.

**Comment by javuto** [comment]
Implemented in https://github.com/facebook/fbctf/commit/c214fab0c9b9f4f6d4ba55d0d0cb5e1c575e32b6
