### ISSUE TITLE
Improve session management

### ISSUE THREAD

**Issue by gsingh93** [facebook/fbctf#185]
We currently do DB writes very often because of the session `write` function, and we do DELETE queries as well because of `destroy` and `gc`. We should reduce the number of times these are called.

**Comment by javuto** [comment]
Maybe we should also look at the values of [gc_probability](http://php.net/manual/en/session.configuration.php#ini.session.gc-probability), [gc_divisor](http://php.net/manual/en/session.configuration.php#ini.session.gc_divisor) and [gc_maxlifetime](http://php.net/manual/en/session.configuration.php#ini.session.gc_maxlifetime). They will impact on how many times ```gc``` will be called.
