### ISSUE TITLE
Provision issue mysql

### ISSUE THREAD

**Issue by PingLord** [facebook/fbctf#190]
Hello,

Im trying to provision the fbctf on a ubuntu 16.04 server.
I've ran the provision script with the following : 
./extra/provision.sh -m dev -s $PWD -d /opt/dashboard

It crashed with the following error : 
ERROR 1364 (HY000) at line 1: Field 'points' doesn't have a default value

Any idea how to fix this ?

**Comment by PingLord** [comment]
I've added a default 0 for the points in the schema.sql , re-run everything and now : 

ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'ctf'@'localhost'

...

**Comment by Ttech** [comment]
The installer specifically says use 14.04, not 16.04. That might fix your problem right there due to version incompatibilities.

**Comment by javuto** [comment]
^^^ @PingLord, what @Ttech said :)
