### ISSUE TITLE
Unable to Click on Countries

### ISSUE THREAD

**Issue by rdenman** [facebook/fbctf#192]
Just got a server set up with the platform running, did a mysqldump from the dev platform and as I went to check it out, I found I was unable to click on any of the countries to view the actual challenges... All the levels were imported correctly and all the information is there, but when looking at the gameboard, all I can do is zoom in/out and interact with the menus (navigation, teams, etc). This happens as admin as well as for a regular user.

I'm also unable to access the game logs page as admin. When I try going to the section, I get an HTTP 500 error. This doesn't happen on any other admin pages (or anywhere else on the platform for that matter).

I'm running everything exactly as specified on the production portion of the README (Ubuntu 64-bit 14.04) and ran the commands there to get things up and running. Anybody know what the issue might be?

**Comment by rdenman** [comment]
Not sure how helpful this is, but I found that if I turn the board refresh feature off, then the countries are selectable (as in they get the yellow outline) but the challenges don't show up within them and nothing happens when you click them. Once board refresh is back on, the levels repopulate, but then become unselectable again.

**Comment by rdenman** [comment]
Adding levels manually (rather than through sqldump) does not make a difference.

**Comment by rdenman** [comment]
I ended up dropping the fbctf database and rerunning the provision script, and now everything is working for me perfectly. However, when I reran the provision, it stopped when it was creating the mysql database (specifically, it stopped at the 'Creating user...' command with 'ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'ctf'@'localhost''). But even before dumping my development database into the server, I was able to get add test levels and everything worked. I'm not sure what happened the first time around.

**Comment by rdenman** [comment]
Aaaand then I deleted some old test teams, ran DELETE FROM registration_tokens (to fix the issue where the config admin page breaks when teams are deleted), and now the countries are no longer selectable again... But at least I'm getting closer to the root of the problem.

**Comment by rdenman** [comment]
See #111 for more about delete user issue

**Comment by rdenman** [comment]
Manually went through my sql dump file and removed all teams (except admin), all tokens, all logs, etc and redumped the file into my fbctf database and things started working again (again). I'll leave this open for now as I toy around with the platform in case I run into more problems (unless you guys want me to close the issue)

**Comment by javuto** [comment]
I am closing this and @rdenman feel free to open a new issue if there are more problems. Note that providing *exact* steps to reproduce the actual issue is critical for us to understand and isolate the problem. Also logs are welcome too.

**Comment by rdenman** [comment]
These are the two main errors (from /var/log/hhvm/error.log) that kept coming up when the countries weren't working for me:

`
[Tue Aug 23 14:49:11 2016] [hphp] [5607:7f2d45bff700:176:000001] [] \nFatal error: Uncaught exception 'HH\\InvariantException' with message 'Expected exactly one result' in /var/www/fbctf/src/models/Team.php:389\nStack trace:\n#0 /var/www/fbctf/src/models/Team.php(389): HH\\invariant_violation()\n#1 /var/www/fbctf/src/controllers/AdminController.php(3108): Team::genTeam()\n#2 /var/www/fbctf/src/controllers/AdminController.php(3304): AdminController->genRenderLogsContent()\n#3 /var/www/fbctf/src/controllers/AdminController.php(3314): AdminController->genRenderPage()\n#4 /var/www/fbctf/src/controllers/Controller.php(12): AdminController->genRenderBody()\n#5 /var/www/fbctf/src/Router.php(71): Controller->genRender()\n#6 /var/www/fbctf/src/Router.php(19): Router::genRouteNormal()\n#7 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#8 (): genInit()\n#9 (): HH\\WaitHandle->join()\n#10 /var/www/fbctf/src/index.php(17): HH\\Asio\\join()\n#11 {main}
[Tue Aug 23 14:49:17 2016] [hphp] [5607:7f2d607ff700:180:000001] [] \nFatal error: Uncaught exception 'OutOfBoundsException' with message 'Integer key 0 is out of bounds' in /var/www/fbctf/src/models/Team.php:481\nStack trace:\n#0 /var/www/fbctf/src/data/country-data.php(89): Team::genFirstCapture()\n#1 (): CountryDataController->genGenerateData()\n#2 (): HH\\WaitHandle->join()\n#3 /var/www/fbctf/src/data/country-data.php(119): HH\\Asio\\join()\n#4 {main}
`

There are hundreds of lines occupied by just those two different errors. If you want a full log list, I can post it all (although there aren't really any other relevant errors as far as I can tell).

**Comment by rdenman** [comment]
These are the two main errors (from /var/log/hhvm/error.log) that kept coming up when the countries weren't working for me:

`
 [Tue Aug 23 14:49:11 2016] [hphp] [5607:7f2d45bff700:176:000001] [] \nFatal error: Uncaught exception 'HH\\InvariantException' with message 'Expected exactly one result' in /var/www/fbctf/src/models/Team.php:389\nStack trace:\n#0 /var/www/fbctf/src/models/Team.php(389): HH\\invariant_violation()\n#1 /var/www/fbctf/src/controllers/AdminController.php(3108): Team::genTeam()\n#2 /var/www/fbctf/src/controllers/AdminController.php(3304): AdminController->genRenderLogsContent()\n#3 /var/www/fbctf/src/controllers/AdminController.php(3314): AdminController->genRenderPage()\n#4 /var/www/fbctf/src/controllers/Controller.php(12): AdminController->genRenderBody()\n#5 /var/www/fbctf/src/Router.php(71): Controller->genRender()\n#6 /var/www/fbctf/src/Router.php(19): Router::genRouteNormal()\n#7 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#8 (): genInit()\n#9 (): HH\\WaitHandle->join()\n#10 /var/www/fbctf/src/index.php(17): HH\\Asio\\join()\n#11 {main}

[Tue Aug 23 14:49:17 2016] [hphp] [5607:7f2d607ff700:180:000001] [] \nFatal error: Uncaught exception 'OutOfBoundsException' with message 'Integer key 0 is out of bounds' in /var/www/fbctf/src/models/Team.php:481\nStack trace:\n#0 /var/www/fbctf/src/data/country-data.php(89): Team::genFirstCapture()\n#1 (): CountryDataController->genGenerateData()\n#2 (): HH\\WaitHandle->join()\n#3 /var/www/fbctf/src/data/country-data.php(119): HH\\Asio\\join()\n#4 {main} 
`

There are hundreds of lines occupied by just those two different errors. If you want a full log list, I can post it all (although there aren't really any other relevant errors as far as I can tell).

**Comment by sajkog** [comment]
I think I'm experiencing a variation of original issue.
fbctf set up with docket in prod mode (current master)
added single flag level
when going to gameboard its outlined and selectable
as soon as I set "REFRESH GAMEBOARD" to off, its no longer outlined on the map nor selectable
