### ISSUE TITLE
Installation on EC2? Anyone had luck?

### ISSUE THREAD

**Issue by dlbennett** [facebook/fbctf#195]
When I attempt to install I receive memory errors on EC2. Can anyone think of why the install would not work? I'm doing production...

**Comment by jan0sik** [comment]
Yeah, I was able to launch and get FBCTF setup on a ec2 mini instance with no issues. Then added Lets Encrypt certs and it works like a charm. Also went through the trouble of change the scheme to red, which was what took me the most time. Everything else took me about a couple hours. Ran into troubles with Lets Encrypt. Gotta run the normal install first, then the cert portion. And dev will not work on ec2 because its AWS. Gotta go full prod. Check mine out. https://ctf.matttopor.com

**Comment by javuto** [comment]
@dlbennett you should be able to setup a CTF in AWS following our README or using this guide someone wrote: https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki

@jan0sik I really like the red colors. I would like to add themes capability and this could be a good start. Did you just replace colors by the red tone?

**Comment by jan0sik** [comment]
@dlbennett I used the setup process on https://github.com/facebook/fbctf/blob/master/README.md, you have to use production and run the first main prod command, then the let's encrypt command to get certs, unless you are hosting locally then selfsigned will do.

@javuto Yeah, adding themes would be awesome. I masked it after the color theme of my community, which is red/black. So what I ended up doing was using sed to replace all the color variables in the css files from their bluish colors to the matching red types using a color picker to get the exact numbers. Spent a minutes getting most of them done ,but there were several that were really hard to find and change. But now that I know relativly which ones to change and nivigated pretty much around the whole setup, I understand the location and the design of the website, which helps even more!

As for additions, I want to incorporate radio plugin into my site, so players can play music as they compete. And some other things I have in mind. Right now it is not open to the public to play, but will be a annual or semiannual competition with real prizes in the future. Thanks for the like of the color theme, worked hard to change it all hehe.

**Comment by javuto** [comment]
@jan0sik would you like to work together to get a basic theme functionality ready to go? Let's open a new issue for that and start documenting your findings, it was a great job indeed!

**Comment by javuto** [comment]
@dlbennett please do follow the guidelines above to deploy in AWS and feel free to open a new issue, with more details of the problem encountered. Closing this one now.
@jan0sik please do add your insights to the new issue #200 for the themes.

**Comment by dlbennett** [comment]
Thanks! Will do.
