### ISSUE TITLE
How to set the countdown?

### ISSUE THREAD

**Issue by tr4nc3** [facebook/fbctf#198]
Hi,
Looking for a HOWTO to set the countdown clock to the event.  Is there a way to set the countdown clock so it counts down to the actual event?

Thanks.

**Comment by javuto** [comment]
Sorry @tr4nc3 we do not have that implemented yet. Hopefully I can get some time to look at it after we merge the current open pull requests.

**Comment by juliannagler** [comment]
Addressed with PR #392
