### ISSUE TITLE
'provision.sh prod' doesn't work fine

### ISSUE THREAD

**Issue by Dor1s** [facebook/fbctf#20]
There are a couple of issues

1) **Incorrect path to a certificate file in nginx configuration**

Would be better to create self-signed certificate in default case and provide path to it instead of using [.csr file](https://github.com/facebook/fbctf/blob/5d75a0a5b71d724ff71ac301e99ad5ed99a7947b/extra/lib.sh#L86
) since it breaks nginx configuration.

By default it doesn't exist at all:

```
Mai 11 12:56:34 ub16x64 nginx[16037]: nginx: [emerg] BIO_new_file("/etc/nginx/certs/fbctf.csr") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('
Mai 11 12:56:34 ub16x64 nginx[16037]: nginx: configuration file /etc/nginx/nginx.conf test failed
```

If you put your own `.csr` it breaks because it should be a certificate, not certificate signing request:
```
Mai 11 12:57:44 ub16x64 nginx[16339]: nginx: [emerg] PEM_read_bio_X509_AUX("/etc/nginx/certs/test_cert.csr") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:E
Mai 11 12:57:44 ub16x64 nginx[16339]: nginx: configuration file /etc/nginx/nginx.conf test failed
```

After fixing the issue with cert I've started to get `500 hphp_invoke`.

2) **Need to create some hhvm directories**

I had to manually create `/var/log/hhvm` to get logs into there, then found out the following errors:

```
# cat /var/log/hhvm/error.log 
[Wed May 11 13:15:44 2016] [hphp] [19848:7fa7475e9c00:0:000001] [] Unable to open pid file /var/run/hhvm/pid for write
[Wed May 11 13:15:57 2016] [hphp] [19848:7fa72bfff700:1:000001] [] \nFatal error: Class undefined: AsyncMysqlConnectionPool in /var/www/fbctf/src/Db.php on line 19

```

Created one more dir:

```
sudo mkdir /var/run/hhvm
chown www-data:root /var/run/hhvm; chmod 755 /var/run/hhvm
```

3) **Fix hhvm config files**

Also had to change `/etc/hhvm/server.ini` to use `hhvm.pid_file` option instead of `pid`:

```
;pid = /var/run/hhvm/pid
hhvm.pid_file = /var/run/hhvm/pid
```

Looks like that fixed the issue with `/var/run/hhvm/pid` file.

But I'm still getting:

```
[Wed May 11 13:33:37 2016] [hphp] [24750:7fae537ff700:1:000001] [] \nFatal error: Class undefined: AsyncMysqlConnectionPool in /var/www/fbctf/src/Db.php on line 19
```

And have no idea how to fix that. Tried to supply non-empty array to the constructor in `/var/www/fbctf/src/Db.php`:

```
$this->pool = new AsyncMysqlConnectionPool(array($this_config));
```

But it doesn't help :(

**Additional information**:
```
# hhvm --version
HipHop VM 3.11.1 (rel)
Compiler: 3.11.1+dfsg-1ubuntu1
Repo schema: 2f678922fc70b326c82e56bedc2fc106c2faca61
# uname -a
Linux ub16x64 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fnzv** [comment]
Getting the same error: 
nginx: [emerg] BIO_new_file("/etc/nginx/certs/fbctf.csr") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/fbctf.csr','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed


And in nginx error.log:
[emerg] 3154#0: BIO_new_file("/etc/nginx/certs/fbctf.csr") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/fbctf.csr','r') error:2006D080:BIO routines:BIO_new_file:no such file)

Shouldn't be a quick install\one liner  to deploy easily and try it?

**Comment by gsingh93** [comment]
> Would be better to create self-signed certificate in default case and provide path to it instead of using .csr file since it breaks nginx configuration.

Note that if you provision in dev mode (i.e. `./extra/provision.sh dev `pwd``), self signed certificates are used. We forgot to mention this in the README because we do all of our development on a Vagrant VM, and it provisions in dev mode by default. We'll clarify this in the README.

I haven't run into the other issues, but I'll look into them. Thanks for the report!

**Comment by STRML** [comment]
I can confirm all these issues. Its propensity to copy certs over to `/etc/nginx/certs` is also not a great idea with e.g. letsencrypt certs.

With the `AsyncMysqlConnectionPool` error I am unable to get the project started.

**Comment by mpomarole** [comment]
@STRML could you let us know what version of HHVM and Ubuntu you are running?

**Comment by mpomarole** [comment]
@Dor1s 
We recommend using Ubuntu 14.04 and HHVM 3.13 to run the platform at this moment. We are confirming with HHVM team when Ubuntu 16 will be supported.

**Comment by Dor1s** [comment]
Thanks @mpomarole for clarification! Will try :)

**Comment by STRML** [comment]
@mpomarole You're correct, I was on 16.04 which is apparently not supported by HHVM > 3.11. I tried compiling from source but there was some linkage issue. Reverted to 14.04 and all seems good.
