### ISSUE TITLE
Failed install on Amazon EC2 - Errors included

### ISSUE THREAD

**Issue by dlbennett** [facebook/fbctf#201]
Ok, I just retried the install on an EC2 Ubuntu 14.04 instance. Any assistance is appreciated!

The install command I used after update/etc was:

_./extra/provision.sh -m prod -c self -s $PWD_

The error that occurred was:

_Assertion failure: /tmp/tmp.3f6VuVMO0N/hphp/runtime/base/rds.cpp:534: void HPHP::rds::threadInit(): assertion `tl_base != ((void *) -1)' failed.
Failed to mmap persistent RDS region. errno = Cannot allocate memory

Core dumped: Aborted
Stack trace in /tmp/stacktrace.8671.log
hphp failed
running hphp took 0'22" (22353307 us) wall time_

The stack trace is an empty file.

Thanks,

-Darren

**Comment by iangcarroll** [comment]
Are you on an instance with <1GB of RAM? Looks like HHVM ran out of RAM.

**Comment by gsingh93** [comment]
Yea, I've seen this on a t2.micro. The problem was resolved on a t2.small.

**Comment by dlbennett** [comment]
Will try it on a t2.small. Was using the t2.micro. Thanks for the quick feedback! (and the great software)

**Comment by dlbennett** [comment]
That was the issue. Looks like you need a minimum of a t2.small instance to run it. (no free ec2 for me!). Thanks again for the feedback.

-Darren

**Comment by jan0sik** [comment]
To be fair, I am running sert.tangoworldwide.net on a t2.micro right now with no issues. And I reinstalled it multiple times. I installed it on Monday. That is weird that it did not work for you.
