### ISSUE TITLE
Facebook Integration

### ISSUE THREAD

**Issue by acjcool** [facebook/fbctf#202]
Hi,

Since there is Facebook all over the app, is it not possible to have Facebook integration? For example, when the play a game then they can post their results to Facebook or/and other social media platforms?

Also, for those having Facebook pages, it would be great if the app can auto post every x minutes to the page to keep followers up tot date regarding who is in front.

**Comment by rdenman** [comment]
It would also be nice if you could login/register using your Facebook account

**Comment by javuto** [comment]
This falls under the different login methods and it is relevant to https://github.com/facebook/fbctf/issues/126

**Comment by stevcoll** [comment]
Facebook integration has been implemented into the platform for registration and login.
