### ISSUE TITLE
Sponsors brands

### ISSUE THREAD

**Issue by acjcool** [facebook/fbctf#203]
We have some sponsors for our tournament. Is there no way that we can add the sponsors brands/logo's on the app? For instance, this tournament is sponsored by 'x' and then their logo's can scroll at the top of the screen or something like that? For instance, gold sponsors = xxx, silver sponsors = xxx etc. And if someone clicks on a sponsors logo then it should direct them to the sponsor page. Some sponsors have discounts to courses, products etc specifically for the tournament so it could direct them to that special discount page. Also, can we improve the leadboard screen so that it auto refreshes with the sponsors details so that we can leave it on the big screen for all to see the progress? And if a team claims first spot, then some flashing on the leaderboard would be nice to show that there was a change in the rankings.

**Comment by acjcool** [comment]
Hi,

This is what I have done so far but it would be a lot better to have it in the configurations menu instead of a hack attempt in the Controller.php file:

<?hh // strict

  echo "<html>";
  echo "<body>";
  echo "<marquee> My FB CTF Competition. Gold Sponsors: Sponsor 1, Sponsor 2. Silver Sponsors: Sponsor 3, Sponsor 4. etc</marquee>";
  echo "</body>";
  echo "</html";

  abstract class Controller {
  abstract protected function getTitle(): string;
  abstract protected function getFilters(): array<string, mixed>;
  abstract protected function getPages(): array<string>;

.....

**Comment by acjcool** [comment]
I've added the code in the code bracket this time as I noticed that the html tags have been removed for obvious reasons

`  echo "<html>";
  echo "<body>";
  echo "<marquee> My FB CTF Competition. Gold Sponsors: Sponsor 1, Sponsor 2. Silver Sponsors: Sponsor 3, Sponsor 4. etc</marquee>";
  echo "</body>";
  echo "</html";`

**Comment by javuto** [comment]
Merged in https://github.com/facebook/fbctf/pull/448
