### ISSUE TITLE
development is so slow

### ISSUE THREAD

**Issue by kazenomamani210** [facebook/fbctf#204]
This is my feedback.

Looking at pull requests, #71 and #36 are open for over 3 month. 

I think development on fbctf is so slow...:(  Why is it? 

fbctf is less active than another project, such as parse, buck. I hope facebook allocate more resource for fbctf's development.

Just adding one feature takes 3 months is slow, isn't it?

**Comment by kazenomamani210** [comment]
I am not complaing... I just want to see more great function on this platform.

**Comment by jan0sik** [comment]
To be fair it was probably due to the recent conference month. Many major security conferences happen in August, and that just makes people really busy and out of town. I am sure it will pick up in the coming months? But that is for the people at Facebook to decide. Overall, I think they are doing a great job, considering it looks like only several people are working on this and they all have full time jobs. (I presume.)

**Comment by juliannagler** [comment]
Hey @kazenomamani210! 

Thanks for the feedback and overall support of the platform. As @jan0sik correctly said, we've got limited bandwidth to support new development at the moment, but we're heads down working on hiring a dedicated engineering lead to focus specifically on FBCTF. If you know anyone who'd be a good fit for the remote eng position, have them apply [here](http://pro.applytojob.com/apply/Qe1YmW/CTF-Engineering-Lead)!

**Comment by kazenomamani210** [comment]
@juliannagler 

I think your team needs to tell "we are hiring" on readme page, rather than this open issue. So another user can notice that message. What do you think?

**Comment by juliannagler** [comment]
Great idea! Adding it now.

**Comment by kazenomamani210** [comment]
@juliannagler 

Thank you for the update:)

I think #71 is wating for marge, but no update has been made. Any idea on this issue? #71 is the most needed feature on this platform. I hope your team will marge it...

**Comment by kazenomamani210** [comment]
Your team will focus on #71, I am going to close this issue.

**Comment by javuto** [comment]
The functionality you mention increases the attack surface of the platform, which is not really optimal when hosting a CTF competition. It requires proper testing, and reviewing the code carefully, which I am glad we are having some time now to do. Did you check out the pull request yourself? Did you do any further testing? Did it look strong enough for you? Asserting that such feature is "waiting for merge" is a bold statement and I would love to hear your take on it.

This is an open source project with a long list of open issues. If you want the development to go faster, feel free to pick up something and fix it.
