### ISSUE TITLE
 access to the private repository of existing challenges, 

### ISSUE THREAD

**Issue by devkell** [facebook/fbctf#205]
May i ask, how long does it take to have access to private repository of challenges. Because beside this plattfrom is a very good one. Be i have requested the repo twice. One with more than a month. and nothing or no one has been respond to me yet.

**Comment by juliannagler** [comment]
Hey @devkell - so sorry for the radio silence, looks like your email from last month slipped through the cracks! We’ve reprioritized our limited bandwidth to further develop the platform, at the short term expense of building out the challenges repo. We’re in the process of hiring a dedicated engineer to support FBCTF, with the challenges repo being one of their first tasks. We hope to have the repo ready for distribution within the next few months. So sorry for this delay! 

In the meantime, if you know of anyone who’d be a good fit for the remote contractor eng position, have them apply [here](http://pro.applytojob.com/apply/Qe1YmW/CTF-Engineering-Lead)!

**Comment by mwooly6** [comment]
can we request the original repo?  Sounds like you are working on a new repo, which is great but I am looking to do some training with it next month and the original repo of web app challenges would be perfect

**Comment by 5hubh4m** [comment]
Sorry for bumping the thread, but I sent an email to ctf@fb.com, and I seem to have gotten no reply yet. Is the repo of challenges still available?
