### ISSUE TITLE
Safe Way to Delete Users During Game?

### ISSUE THREAD

**Issue by rdenman** [facebook/fbctf#206]
If you're running a game using tokens for registration, then need to delete a team, it can lead to an unusable admin page (#111), unclickable countries (#192), as well as a few other minor issues (i.e. inaccessible failure log/team pages).

Has anybody come up with a safe way to delete a user WITHOUT deleting all the registration tokens? Also, if registration tokens are deleted, will the other teams that weren't meant to be deleted still function? Are there any preventative steps that can be taken before starting a competition to keep these problems from arising (aside from not deleting teams)?

**Comment by rdenman** [comment]
UPDATE:
Logging into the platform server and deleting only the token for the team you wish to delete before deleting the team seems to avoid the problem - SO, the database should be updated to cascade delete the registration token that matches the team_id of the team being deleted BEFORE the team is actually deleted. I believe this would fix the problem.

**Comment by rdenman** [comment]
For a quick fix (until a PR can be made):
`
CREATE TRIGGER delete_registration_token BEFORE DELETE ON teams FOR EACH ROW DELETE FROM registration_tokens WHERE registration_tokens.team_id = OLD.id;
`

**Comment by johnny-y-wang** [comment]
A little change to the MySQL patch
```
delimiter //
CREATE TRIGGER delete_team BEFORE DELETE on teams FOR EACH ROW
BEGIN
    DELETE FROM registration_tokens WHERE registration_tokens.team_id = OLD.id;
    DELETE FROM scores_log where scores_log.team_id = OLD.id;
    DELETE FROM hints_log where hints_log.team_id = OLD.id;
    DELETE FROM failures_log where failures_log.team_id = OLD.id;
END //

delimiter ;
```

**Comment by justinwray** [comment]
This should now be correctly handled in PR #372.
