### ISSUE TITLE
Docker image hangs forever

### ISSUE THREAD

**Issue by freeqaz** [facebook/fbctf#207]
Howdy y'all,

In setting up the container with Docker, I'm getting an infinite hang. Here is my output.

```
~/code/fbctf master 10s
❯ docker build --build-arg MODE=dev -t="fbctf_in_dev" .
Sending build context to Docker daemon 6.762 MB
Step 1 : FROM ubuntu:trusty
 ---> 4a725d3b3b1c
Step 2 : MAINTAINER Boik boik@tdohacker.org
 ---> Using cache
 ---> eeb225da0779
Step 3 : ENV HOME /root
 ---> Using cache
 ---> 1250cf585514
Step 4 : ARG DOMAIN
 ---> Using cache
 ---> 9baf979c4fc7
Step 5 : ARG EMAIL
 ---> Using cache
 ---> c915799cfc66
Step 6 : ARG MODE=dev
 ---> Using cache
 ---> f2268ddd0c8e
Step 7 : ARG TYPE=self
 ---> Using cache
 ---> ff62e0e5652c
Step 8 : ARG KEY
 ---> Using cache
 ---> 4563b348302c
Step 9 : ARG CRT
 ---> Using cache
 ---> 98646d861424
Step 10 : WORKDIR $HOME
 ---> Using cache
 ---> c7bce922cc6d
Step 11 : COPY . $HOME
 ---> Using cache
 ---> 8c7b9aebe829
Step 12 : RUN apt-get update   && apt-get install -y   rsync   ca-certificates   && chown www-data:www-data $HOME   && ./extra/provision.sh -m $MODE -c $TYPE -k $KEY -C $CRT -D $DOMAIN -e $EMAIL -s `pwd` --docker   && apt-get clean   && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Using cache
 ---> b10169a49c2d
Step 13 : CMD ./extra/service_startup.sh
 ---> Using cache
 ---> 5ba4bda08343
Successfully built 5ba4bda08343

~/code/fbctf master
❯ docker run -p 80:80 -p 443:443 fbctf_in_dev
 * Restarting nginx nginx
   ...done.
 * Starting MySQL database server mysqld
   ...done.
 * Checking for tables which need an upgrade, are corrupt or were
not closed cleanly.
```

It hangs forever on that last line. Control-C, V, or Z have not effect and I have to close the terminal window.

More info on my setup:
- Using Virtualbox on my Mac, version 5.0.12
- Docker version 1.12.0, build 8eab29e
- Using an Ubuntu machine for this

**Comment by gsingh93** [comment]
I believe it will hang if you don't use `-i` for interactive.

**Comment by freeqaz** [comment]
Hey @gsingh93,

These commands are copy-pasted from the project Readme. Are you saying that I should add `-i` to stick this in the background and then I can access the app? 

Is there an easy way to check the health of the application afterwards? Something along the lines of `curl localhost/health` but pointed at the fbctf instance.

**Comment by qazbnm456** [comment]
@freeqaz The default run command provided in README will not be terminated with Control-C, V, or Z. If you want to terminate the container with those keys, you should pass `-it` as well, ex: `docker run -p 80:80 -p 443:443 -it fbctf_in_dev`.

**Comment by freeqaz** [comment]
Thanks @qazbnm456!

I'll go ahead and close this then, since it sounds like intended behavior. We should definitely add a comment in there helping new Docker users (like me) understand what they're doing. The lack of being able to terminate the container really caught me off guard!

I SSH'd into the Docker image and I can curl the endpoint. I'll figure out how to talk to it from my browser next.

**Comment by acjcool** [comment]
Hi,

How did you resolve your container hanging? Mine is also stuck at this section and stays like that forever

* Starting MySQL database server mysqld    ...done.
* Checking for tables which need an upgrade, are corrupt or were not closed cleanly.

When I navigate to 127.0.0.1 it gives me a 502 Bad Gateway from nginx. I've installed the image twice to check if there wasn't something wrong during installation but the script finishes each time saying that it was successful.

**Comment by qazbnm456** [comment]
@acjcool I do take your problem seriously, but you'll have to give me more infos to let me know why you encounter this, such as your host os, fbctf building environment(dev or prod) and arguments, and etc. The more you give, the more I can clarify. Many thanks :)

**Comment by adrianbrink** [comment]
So this still happens.

Ubuntu 14.04.05
DigitalOcean 2GB

1. command run: `docker build --build-arg MODE=prod --build-arg DOMAIN=test.mydomain.com --build-arg EMAIL=myemail@mydomain.com --build-arg TYPE=certbot -t="fbctf_in_prod" .`

works fine without errors (maybe with the ssl certs through certbot)

2. command: `docker run -p 80:80 -p 443:443 -it -v /etc/letsencrypt:/etc/letsencrypt fbctf_in_prod`

Expected result: Working server

Actual result: `sammy@ctf:~/fbctf$ docker run -p 80:80 -p 443:443 -it -v /etc/letsencrypt:/etc/letsencrypt fbctf_in_prod
 * Restarting HHVM FastCGI Daemon hhvm                                                                                           [ OK ]
 * Restarting nginx nginx                                                                                                        [fail]
 * Stopping MySQL database server mysqld                                                                                         [ OK ]
 * Starting MySQL database server mysqld                                                                                         [ OK ]
 * Checking for tables which need an upgrade, are corrupt or were
not closed cleanly.`

Any help is appreciated :-)

**Comment by iangcarroll** [comment]
Can you open a separate issue for this? In the meantime, try getting a bash shell with `docker exec -ti <container id> bash` inside the running container and see if there's anything in `/var/log/nginx/error.log`.
