### ISSUE TITLE
Latest update broke Docker(?)

### ISSUE THREAD

**Issue by frite** [facebook/fbctf#209]
I believe that the latest commit (32a9f47d488895925cf187e80340ac2ff143cacc) broke hhvm for docker.
```docker -v
Docker version 1.12.0, build 8eab29e```

```
$ docker exec -it e24668d642e3 bash
root@e24668d642e3:~# service nginx status
 * nginx is running
root@e24668d642e3:~# service mysql status
 * /usr/bin/mysqladmin  Ver 8.42 Distrib 5.5.50, for debian-linux-gnu on x86_64
Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Server version 		5.5.50-0ubuntu0.14.04.1
Protocol version       	10
Connection     		Localhost via UNIX socket
UNIX socket    		/var/run/mysqld/mysqld.sock
Uptime:			29 sec

Threads: 1  Questions: 110  Slow queries: 0  Opens: 71  Flush tables: 1  Open tables: 61  Queries per second avg: 3.793
root@e24668d642e3:~# service hhvm status
 * hhvm is not running
root@e24668d642e3:~#
```

Vagrant on the other hand works fine.


I see there's a build job here https://travis-ci.org/facebook/fbctf/builds . Maybe it can be expanded to run tests for docker as well.  

Regards

**Comment by qazbnm456** [comment]
@frite I've noticed that it's the permission problem of hhvm's socket, which cause the broken image. I've sent PR already, and you might want to follow the commit to fix this problem out. :)

**Comment by frite** [comment]
Awesome, thanks a million @qazbnm456

**Comment by qazbnm456** [comment]
@frite Not at all.
