### ISSUE TITLE
FBCTF doesn't restart when the system is rebooted.

### ISSUE THREAD

**Issue by dlbennett** [facebook/fbctf#214]
Is there a trick? I checked nginx, mysql and hhvm. I'm getting "Bad Gateway" error when restarting. Is this possibly due to the fact that the system IP changes (dhcp) when rebooted? How can I manually restart FBCTF and what files need to be tweaked if the IP changes? 

Thanks!

**Comment by wisco24** [comment]
I am getting the same error right after install.

**Comment by gsingh93** [comment]
I think the issue is with repo authoritative mode. Try:
```
rm /var/run* and && rm /home/ubuntu/.hhvm.hhbc
```

Followed by:
```
sudo hhvm-repo-mode enable .
```

**Comment by wisco24** [comment]
I ran those, and it still is giving me the Bad Gateway error.

**Comment by wisco24** [comment]
Here is some of the nginx logs:

2016/09/09 18:40:38 [warn] 1195#0: "ssl_stapling" ignored, issuer certificate not found
2016/09/09 18:41:25 [crit] 1200#0: *1 connect() to unix:/var/run/hhvm/sock failed (2: No such file or directory) while connecting to upstream, client: x.x.x.x, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/hhvm/sock:", host: "my.domain.com"

**Comment by matthewpurcell** [comment]
@wisco24 There is an issue with the latest release of HHVM. Take a look at my [comment here](https://github.com/facebook/fbctf/issues/215#issuecomment-246299523) which hopefully will help you.

**Comment by javuto** [comment]
Pull Request also open to mitigate this problem: https://github.com/facebook/fbctf/pull/216

**Comment by javuto** [comment]
Given that this is mitigated for now (and awaiting a fix from HHVM for the latest package) should be good to close.
