### ISSUE TITLE
Running behind a reverse proxy breaks login

### ISSUE THREAD

**Issue by profrowe** [facebook/fbctf#220]
Running behind an nginx reverse proxy completely breaks login.  I am have the CTF working in a Linux Container NAT'ed behind an nginx reverse proxy.  This is letting me use 16.04 on the front-end with a 14.04 container.  Everything works just fine directly accessing the backend host, but as soon as it passes through an nginx proxy, login breaks.  No error, login gives no error (it errors normally with bad pw) successful but no logged in session - returns to main page.

FBCTF Ubuntu 14.04 box fbctf.conf from nginx:
```
server {
  listen 80;

  add_header X-Frame-Options DENY;
  add_header X-Content-Type-Options nosniff;
 add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";

  add_header Cache-Control "no-cache, no-store";
  add_header Pragma "no-cache";
  expires -1;

  root /var/www/fbctf/src;
  index index.php;
  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_pass  unix:/var/run/hhvm/sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
  }
  error_page 400 401 402 403 404 500 /error.php;
  client_max_body_size 25M;

}
```

Reverse proxy nginx configuration:

```
server_tokens off;

server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass https://10.185.154.42/; #IP of the FBCTF Container.
        }
}
```

**Comment by profrowe** [comment]
FBCTF Ubuntu 14.04 box fbctf.conf from nginx:
`server {
#  listen 80;
#  rewrite ^ https://$host$request_uri? permanent;
  add_header X-Frame-Options DENY;
  add_header X-Content-Type-Options nosniff;
 # add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";

  add_header Cache-Control "no-cache, no-store";
  add_header Pragma "no-cache";
  expires -1;

  root /var/www/fbctf/src;
  index index.php;
  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_pass  unix:/var/run/hhvm/sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
  }
  error_page 400 401 402 403 404 500 /error.php;
  client_max_body_size 25M;

}
`

Reverse proxy nginx configuration:
`server_tokens off;

server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass https://10.185.154.42/; #IP of the FBCTF Container.
        }
}
`

**Comment by irqbank** [comment]
FWIW, I am running fbctf behind nginx as well, and I have no issues with logging in. Have you tried listening on port 443 (tls) instead of 80? On a quick glance, this is the only difference that stands out to me.
