### ISSUE TITLE
How to install?Please help me!

### ISSUE THREAD

**Issue by evilchurch** [facebook/fbctf#223]
I'm going to install it on a vps(ubuntu 14.04.5 64). It's my step:
1.sudo apt-get update
2.sudo apt-get install git
3.git clone https://github.com/facebook/fbctf
4.cd fbctf
5../extra/provision.sh -m prod -s $PWD
But when intall hhvm,it stoped! The /var/log/hhvm/error.log say:
[Fri Sep 23 11:28:14 2016] [hphp] [22376:7f15de81ffc0:0:000002] [] system("bash -c '! fuser /var/run/hhvm/sock'"): Cannot allocate memory

**Comment by gsingh93** [comment]
How much memory does your VPS have?

**Comment by evilchurch** [comment]
@gsingh93  my machine is 1GB

**Comment by adrianbrink** [comment]
You need at least 2GB, otherwise it fails.
