### ISSUE TITLE
"Docker build" requires exactly 1 argument(s).

### ISSUE THREAD

**Issue by adrianbrink** [facebook/fbctf#225]
Ubuntu 14.04.05 on Digital Ocean

Command: `docker build --build-arg MODE=dev -t="fbctf_in_dev"`

Expected result: Building the container without an error

Actual result: ```
sammy@ctf:~/fbctf$ docker build --build-arg MODE=dev -t="fbctf_in_dev"
"docker build" requires exactly 1 argument(s).
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
```

I followed the explanation in the [README.md](https://github.com/facebook/fbctf#using-docker)

Any help would be appreciated.

**Comment by qazbnm456** [comment]
@adrianbrink It should be `docker build --build-arg MODE=dev -t="fbctf_in_dev" .` :) Notice there is a dot in the end.

**Comment by adrianbrink** [comment]
@qazbnm456 Oh right, thank you :-)
