### ISSUE TITLE
Test script is failing

### ISSUE THREAD

**Issue by iangcarroll** [facebook/fbctf#227]
The run_tests script appears to be [failing](https://travis-ci.org/facebook/fbctf/builds/162369829) on this line: https://github.com/facebook/fbctf/blob/master/src/language/language.php#L2

It doesn't look like the run_tests script is exiting when it hits an error; it should probably have `set -e` at the top so that the build will properly fail if the tests fail.

**Comment by gsingh93** [comment]
Should be fixed now, thanks.
