### ISSUE TITLE
Docker production deployment fails - rm: cannot remove '/var/run/hhvm/sock': No such file or directory

### ISSUE THREAD

**Issue by adrianbrink** [facebook/fbctf#229]
System:
Ubuntu 14.04.05 with 2GB of RAM running on DigitalOcean

Command: `docker build --build-arg MODE=prod --build-arg DOMAIN=hackitu.io --build-arg EMAIL=adrian@brink-holdings.com --build-arg TYPE=certbot -t="fbctf_in_prod" .`

Expected Result: A deployed build.

Actual Result: 
`\033[0;32m [+] fbctf deployment is complete! Ready in https://10.10.10.5 \033[0m
rm: cannot remove '/var/run/hhvm/sock': No such file or directory
The command '/bin/sh -c apt-get update   && apt-get install -y   rsync   ca-certificates   && chown www-data:www-data $HOME   && ./extra/provision.sh -m $MODE -c $TYPE -k $KEY -C $CRT -D $DOMAIN -e $EMAIL -s `pwd` --docker   && rm /var/run/hhvm/sock   && apt-get clean   && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 1`

Further question, what's the process to make the docker container accessible from the outside world and can I use a different email address than my deployment domain.

**Comment by qazbnm456** [comment]
@adrianbrink Thanks, I'll look into this. The quick fix might be to revise `rm /var/run/hhvm/sock` to `rm -f /var/run/hhvm/sock` in [Dockerfile](https://github.com/facebook/fbctf/blob/master/Dockerfile#L21).

BTW, just type `docker run -p 80:80 -p 443:443 -v /etc/letsencrypt:/etc/letsencrypt fbctf_in_prod` to make your container accessible through port 80 and 443, and it should be okay if you provide different domain regarding to your second question.

**Comment by adrianbrink** [comment]
With the -f flag it works. 

Last question, I am using a floating IP from Digital Ocean and the certbot challenge fails due to the server IP being different. Is that expected or should it normally work?

Also, the run command still hangs at this stage:
```
 * Checking for tables which need an upgrade, are corrupt or were
not closed cleanly.
```

Thanks for the help :-)

**Comment by qazbnm456** [comment]
If your domain points to your IP correctly, it should be no problem claiming your certs through certbot (don't forget `-v /etc/letsencrypt:/etc/letsencrypt` when you up your fbctf server), and certs will be generated under **/etc/letsencrypt**.

To your second question, you can refer to https://github.com/facebook/fbctf/issues/207 :)

**Comment by adrianbrink** [comment]
@qazbnm456 Is there some weird interaction I should expect when using cloudflare as my dns service?

**Comment by qazbnm456** [comment]
@adrianbrink I actually have no experience of cloudflare, thus I'm not sure if there will be some problems. You could try and report results here, though I think it should be no problem at all :)

**Comment by adrianbrink** [comment]
I'm gonna play around more with letsencrypt and cloudflare and report back :-)
