### ISSUE TITLE
teams_data does not populate - cannot store names of people on team

### ISSUE THREAD

**Issue by rdenman** [facebook/fbctf#233]
When player names is turned on for registration, teams are asked to enter names and emails. However, this information is (seemingly) not available anywhere. It does not populate on the admin 'teams' page under names (all you see is "No Team Names") and when I query the teams_data table in the database, I receive an empty result set.

Anyone else have this problem? Or, rather, has anyone else been able to get team names and emails to work?

**Comment by ajhenley** [comment]
I am having this problem as well...

**Comment by javuto** [comment]
There is already an issue for this: https://github.com/facebook/fbctf/issues/86
