### ISSUE TITLE
"502 Bad Gateway" NGINX error when HHVM does not start on virtual machine restart

### ISSUE THREAD

**Issue by eeeehaw** [facebook/fbctf#234]
I thought I had licked this 502 Bad Gateway error when running FBCTF on Azure, after changing the private internal subnet address space to 10.10.10.0/24 and setting the virtual machine (VM) eth0 IPaddr to 10.10.10.5 (see Closed Issue https://github.com/facebook/fbctf/issues/219 ).  But then I discovered that after restarting the VM, the problem came back.  I then tried Google Cloud and saw the exact same problem occur on that VM, which uses a different hyper-visor.  Of course, both VMs are running Ubuntu 14.04LTS.  'sudo service hhvm status' shows hhvm running after initial provisioning, but not running after the VM is restarted.

I am able to correct the problem temporarily by re-provisioning FBCTF again ('./extra/provision.sh -m prod -s $PWD'); then everything is back to normal...until the VM is restarted again.  Meanwhile, mysql & nginx services restart properly and run even after hhvm fails to start.  As a volunteer for a high school  cyber security club (= no money aside of volunteer out-of-pocket), I don't want a Azure or Google Cloud VM running when not needed so as to keep my out-of-pocket costs down, thus the need to have those environments stopped when not needed and restarted when needed by admin or students.

I have posted this problem in the HHVM project Issues page also.  A search on NGINX did not reveal any relevant causes as far as I could determine (altho they emphasized file permissions as a frequent cause).  Could there be a permissions change that occurs during a restart that may be affecting sockets or something else, which I presume would fall into the FBCTF area scripts?

**Comment by iangcarroll** [comment]
I cannot say why setting that IP resolved your problem, because the source code does not use that IP, Vagrant does, but either way:

Try running the following after rebooting:
```
sudo rm /var/run/hhvm/hhvm.hhbc
sudo hhvm-repo-mode enable "/var/www/fbctf"
sudo chown www-data:www-data /var/run/hhvm/hhvm.hhbc
sudo service hhvm start
```

**Comment by eeeehaw** [comment]
Ian, that does work to recover HHVM to running service, and resolve the 
nginx 502 Bad Gateway error.  Helpful as a clue toward finding root 
cause of the problem?

Here's my console output for that:
----------------
eeeehaw@cyberwars-vm1:~$ sudo rm /var/run/hhvm/hhvm.hhbc
eeeehaw@cyberwars-vm1:~$ sudo hhvm-repo-mode enable "/var/www/fbctf"
running hphp...
parsing inputs...
Unable to stat file 
/var/www/fbctf/vendor/phpunit/php-token-stream/tests/_fixture/test1.php
Unable to stat file 
/var/www/fbctf/vendor/phpunit/php-token-stream/tests/_fixture/test2.php
Unable to stat file 
/var/www/fbctf/vendor/phpunit/php-token-stream/tests/_fixture/test3.php
Unable to stat file 
/var/www/fbctf/vendor/phpunit/php-token-stream/tests/_fixture/test4.php
Unable to stat file 
/var/www/fbctf/vendor/phpunit/php-token-stream/vendor/autoload.php
Unable to stat file 
/var/www/fbctf/vendor/phpunit/phpunit-mock-objects/vendor/autoload.php
Unable to stat file 
/var/www/fbctf/vendor/phpunit/phpunit/build/tools/phar:/composer.phar/bin/composer
Unable to stat file 
/var/www/fbctf/vendor/phpunit/phpunit/vendor/autoload.php
Unable to stat file 
/var/www/fbctf/vendor/sebastian/comparator/vendor/autoload.php
Unable to stat file 
/var/www/fbctf/vendor/sebastian/resource-operations/build/arginfo.php
analyzeProgram...
analyzeProgram took 0'00" (458096 us) wall time
parsing inputs took 0'44" (44099109 us) wall time
pre-optimizing...
pre-optimizing took 0'00" (403734 us) wall time
creating binary HHBC files...
creating binary HHBC files took 0'13" (13185443 us) wall time
all files saved in /var/run/hhvm ...
running hphp took 0'58" (58715371 us) wall time
Success!
eeeehaw@cyberwars-vm1:~$ sudo chown www-data:www-data 
/var/run/hhvm/hhvm.hhbc
eeeehaw@cyberwars-vm1:~$ sudo service hhvm start
eeeehaw@cyberwars-vm1:~$ sudo service hhvm status
  * hhvm is running
eeeehaw@cyberwars-vm1:~$
----------------------------

**Comment by iangcarroll** [comment]
Does `/var/run/hhvm/hhvm.hhbc` exist after rebooting? What do its permissions look like in `ls -al /var/run/hhvm` (after rebooting)?

**Comment by eeeehaw** [comment]
BEFORE rebooting and everything working:
eeeehaw@cyberwars-vm1:/var/run/hhvm$ ls -al
total 78592
drwxr-xr-x  2 www-data www-data      100 Sep 26 21:14 .
drwxr-xr-x 20 root     root          800 Sep 26 21:09 ..
-rw-r--r--  1 www-data www-data 80473088 Sep 26 21:14 hhvm.hhbc
-rw-r--r--  1 www-data www-data        4 Sep 26 21:15 pid
srwxrw----  1 www-data www-data        0 Sep 26 21:14 sock
eeeehaw@cyberwars-vm1:/var/run/hhvm$

AFTER rebooting and hhvm service not running:
eeeehaw@cyberwars-vm1:/var/run/hhvm$ ls -al
total 28
drwxr-xr-x  2 www-data www-data    80 Sep 26 21:55 .
drwxr-xr-x 20 root     root       800 Sep 26 21:57 ..
-rw-r--r--  1 www-data www-data 26624 Sep 26 21:55 hhvm.hhbc
-rw-r--r--  1 www-data www-data     0 Sep 26 21:55 pid
eeeehaw@cyberwars-vm1:/var/run/hhvm$ sudo service hhvm status
  * hhvm is not running
eeeehaw@cyberwars-vm1:/var/run/hhvm$

**Comment by iangcarroll** [comment]
So, HHVM is expecting all of the source files to be precompiled in the `hhvm.hhbc` file, and it looks like it's being deleted. We may want to address this in our provisioning script, but until then you should add `hhvm-repo-mode enable "/var/www/fbctf"` into an init script so that it builds the cache upon reboot.

**Comment by eeeehaw** [comment]
An HHVM tech is asking for backtrace info using a debug package, in 
support of this issue having been reported by someone with FBCTF a 
couple weeks ago to them.  Do you have a debug version I can try for 
FBCTF?  Worth the effort to do that?  (not certain exactly how to do 
that, but willing to try)

What could be deleting that?

**Comment by eeeehaw** [comment]
Is there are existing init script that would be best to edit for this? 
(and location?)  I assume this should be done at a specific point in 
time during reboot, and given Upstart presumably being used in the 
Ubuntu 14.04 release (ie, asynchronous after a certain point) it may be 
a fbctf related one?

**Comment by eeeehaw** [comment]
Ian, I found the following script in /etc/init.d for hhvm; console 
attached in the txt file (notice the permissions also at the end).  
Would this be an appropriate place to add your suggested change?


On 2016-09-26 15:33, Ian Carroll wrote:
> So, HHVM is expecting all of the source files to be precompiled in the
> hhvm.hhbc file, and it looks like it's being deleted. We may want to
> address this in our provisioning script, but until then you should add
> hhvm-repo-mode enable "/var/www/fbctf" into an init script so that it
> builds the cache upon reboot.
> 
> 
eeeehaw@cyberwars-vm1:/etc/init.d$ cat hhvm
#!/bin/sh
#
# /etc/init.d/hhvm -- startup script for HHVM FastCGI
#
### BEGIN INIT INFO
# Provides:          hhvm
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Starts The HHVM FastCGI Daemon
### END INIT INFO

# Author: Dominic Luechinger <dol@snowgarden.ch>

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="HHVM FastCGI Daemon"
NAME=hhvm
DAEMON=/usr/bin/hhvm
PIDFILE=/var/run/hhvm/pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Default values. This values can be overwritten in '/etc/default/hhvm'
CONFIG_FILE="/etc/hhvm/server.ini"
SYSTEM_CONFIG_FILE="/etc/hhvm/php.ini"
RUN_AS_USER="www-data"
RUN_AS_GROUP="www-data"
ADDITIONAL_ARGS=""

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

DAEMON_ARGS="--config ${SYSTEM_CONFIG_FILE} \
--config ${CONFIG_FILE} \
--user ${RUN_AS_USER} \
--mode daemon \
-vPidFile=${PIDFILE} \
${ADDITIONAL_ARGS}"

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
check_run_dir() {
    # Only perform folder creation, if the PIDFILE location was not modified
    PIDFILE_BASEDIR=$(dirname ${PIDFILE})
    # We might have a tmpfs /var/run.
    if [ "/var/run/hhvm" = "${PIDFILE_BASEDIR}" ] && [ ! -d /var/run/hhvm ]; then
        mkdir -p -m0755 /var/run/hhvm
        chown $RUN_AS_USER:$RUN_AS_GROUP /var/run/hhvm
    fi
}

do_start()
{
        # Return
        #   0 if daemon has been started
        #   1 if daemon was already running
        #   2 if daemon could not be started
        touch $PIDFILE
        chown $RUN_AS_USER:$RUN_AS_GROUP $PIDFILE
        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
                || return 1
        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
                $DAEMON_ARGS \
                || return 2
        # Add code here, if necessary, that waits for the process to be ready
        # to handle requests from services started subsequently which depend
        # on this one. As a last resort, sleep for some time.
}

#
# Function that stops the daemon/service
#
do_stop()
{
        # Return
        #   0 if daemon has been stopped
        #   1 if daemon was already stopped
        #   2 if daemon could not be stopped
        #   other if a failure occurred
        start-stop-daemon --stop --quiet --retry=TERM/10/KILL/5 --pidfile $PIDFILE --name $NAME
        RETVAL="$?"
        [ "$RETVAL" = 2 ] && return 2
        # Wait for children to finish too if this is a daemon that forks
        # and if the daemon is only ever run from this initscript.
        # If the above conditions are not satisfied then add some other code
        # that waits for the process to drop all resources that could be
        # needed by services started subsequently.  A last resort is to
        # sleep for some time.
        start-stop-daemon --stop --quiet --oknodo --retry=0/10/KILL/5 --exec $DAEMON
        [ "$?" = 2 ] && return 2
        # Many daemons don't delete their pidfiles when they exit.
        rm -f $PIDFILE
        return "$RETVAL"
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
        #
        # If the daemon can reload its configuration without
        # restarting (for example, when it is sent a SIGHUP),
        # then implement that here.
        #
        start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
        return 0
}

case "$1" in
  start)
        check_run_dir
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
        do_start
        case "$?" in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  stop)
        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop
        case "$?" in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  status)
        status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
  #reload|force-reload)
        #
        # If do_reload() is not implemented then leave this commented out
        # and leave 'force-reload' as an alias for 'restart'.
        #
        #log_daemon_msg "Reloading $DESC" "$NAME"
        #do_reload
        #log_end_msg $?
        #;;
  restart|force-reload)
        #
        # If the "reload" option is implemented then remove the
        # 'force-reload' alias
        #
        check_run_dir
        log_daemon_msg "Restarting $DESC" "$NAME"
        do_stop
        case "$?" in
          0|1)
                do_start
                case "$?" in
                        0) log_end_msg 0 ;;
                        1) log_end_msg 1 ;; # Old process is still running
                        *) log_end_msg 1 ;; # Failed to start
                esac
                ;;
          *)
                # Failed to stop
                log_end_msg 1
                ;;
        esac
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
        exit 3
        ;;
esac
:
eeeehaw@cyberwars-vm1:/etc/init.d$ ls -al hhvm
-rwxrwxr-x 1 root root 5610 Sep  8 00:54 hhvm
eeeehaw@cyberwars-vm1:/etc/init.d$

**Comment by Ttech** [comment]
I have this same problem.

cat /var/log/hhvm/error.log
[Tue Sep 27 02:25:52 2016] [hphp] [11166:7ff676bff700:0:000001] [] Core dumped: Aborted
[Tue Sep 27 02:25:52 2016] [hphp] [11166:7ff676bff700:0:000002] [] Stack trace in /tmp/stacktrace.11166.log

**Comment by gsingh93** [comment]
@Ttech: your issue is that you're using HHVM 3.15, which has a bug that causes a crash. The latest version of the FBCTF script explicitly installs 3.14.5 to avoid this problem.

**Comment by Ttech** [comment]
@gsingh93: This was pulled as of yesterday.

**Comment by gsingh93** [comment]
Here's the code that should be doing it: https://github.com/facebook/fbctf/blob/master/extra/lib.sh#L235

You're running this on a clean box or are you reinstalling it on top of a previous install?

**Comment by Ttech** [comment]
Clean box, clean download as of noon yesterday.

**Comment by eeeehaw** [comment]
I installed latest download of FBCTF on a "clean" cloud VM (4 new ones to 
be exact, 2 each on Azure and Google Cloud).

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by gsingh93** [comment]
@eeeehaw do you also see that you have HHVM 3.15 installed? Or HHVM 3.14.5?

@javuto can you take a look?

**Comment by eeeehaw** [comment]
I have the HHVM v3.14.5 installed that comes with current download of FBCTF.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by eeeehaw** [comment]
I had time to return to this problem yesterday, and tried a few different start-up scripts in /etc/init & init.d folders to add Ian's suggested command to, but known worked ie caused problems.  Ubuntu 14.04 uses Upstart as its startup manager (16.04 has changed to systemd I hear), which processes startup scripts asynchronously which I suspect may be a reason why it wasn't working.  I don't know how to force the work-around for this problem to automatically run at the end of startup, so I created a script file that I run manually after the machine has completed its startup.  That file contains the following commands that Ian provided me (see above) and that gets HHVM working again:

sudo rm /var/run/hhvm/hhvm.hhbc
sudo hhvm-repo-mode enable "/var/www/fbctf"
sudo chown www-data:www-data /var/run/hhvm/hhvm.hhbc
sudo service hhvm start

I placed my file "repairhhvmforfnctf.sh" in the home directory, ie where the user is left after startup.  I changed permissions so that I could run it via 'chmod +x repairhhvmforfbctf.sh', and so am able to run it after startup completes via './repairhhvmforfbctf.sh'.  This saves time/hassle/expense over re-installing FBCTF every time I reboot the VM.

**Comment by javuto** [comment]
Did you try to avoid enabling hhvm-repo-mode and restarting the VM?

**Comment by wisco24** [comment]
I am having the same issue with the new build.  The above code fixes the issue upon reboot, but there clearly is still an issue with hhvm somwhere, even in the downgraded version.

**Comment by deepbreath** [comment]
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-98-generic x86_64)
   __               _                 _     _____ _______ ______  
  / _|             | |               | |   / ____|__   __|  ____| 
 | |_ __ _  ___ ___| |__   ___   ___ | | _| |       | |  | |__    
 |  _/ _' |/ __/ _ \  _ \ / _ \ / _ \| |/ / |       | |  |  __|   
 | || (_| | (_|  __/ |_) | (_) | (_) |   <| |____   | |  | |      
 |_| \__,_|\___\___|_.__/ \___/ \___/|_|\_\\_____|  |_|  |_|      
                                                                  
                                                                  
l don't know why . No hhvm.hhbc
vagrant@facebookctf-dev:~$ sudo rm /var/run/hhvm/hhvm.hhbc
rm: cannot remove ‘/var/run/hhvm/hhvm.hhbc’: No such file or directory

vagrant@facebookctf-dev:~$ hhvm --version
HipHop VM 3.14.5 (rel)
Compiler: tags/HHVM-3.14.5-0-gc6bf714e6468213eed377527b431e9cd4cec1432
Repo schema: 9ab3fe4281c731189b558d921eb7317b0eb2b2e6

**Comment by javuto** [comment]
I just reproduce this problem with the HHVM package 3.14.5 and our latest code. The problem is reproducible when provisioning in production mode, since the root cause is the ```hhvm-repo-mode```. Once I disabled that, the platform worked with no problems after restarting the machine.

**Comment by gsingh93** [comment]
We need to figure out a solution without disabling it though. The performance benefits are very good. Maybe we should fill an issue on the HHVM repo.
