### ISSUE TITLE
Translate fbctf platform to French

### ISSUE THREAD

**Issue by javuto** [facebook/fbctf#235]
At the moment, the fbctf platform is translated in Hungarian (thanks @markszabo!) and English. Let's have it in French too!

**Comment by lokhi** [comment]
Hi,
I think I can do it if i understand well i have to create a lang_fr.php file in  fbctf/src/language/ and translate the content of lang_en.php ?

**Comment by javuto** [comment]
@lokhi correct, that is it

**Comment by MishaLarionov** [comment]
@lokhi's looks machine-translated, I'll make my own and let you decide.
