### ISSUE TITLE
Translate fbctf platform to German

### ISSUE THREAD

**Issue by javuto** [facebook/fbctf#236]
At the moment, the fbctf platform is translated in Hungarian (thanks @markszabo!) and English. Let's have it in German too!

**Comment by danielbayerlein** [comment]
@javuto I'm working on it.

**Comment by javuto** [comment]
Awesome! Thank you @danielbayerlein

**Comment by leeniu** [comment]
I'd like to help with that @danielbayerlein! But I am fairly new to GitHub. Would you mind guiding me to a starting point?

**Comment by danielbayerlein** [comment]
@leeniu Thank you for your offer, but the translation is already complete.
