### ISSUE TITLE
Translate fbctf platform to Portuguese

### ISSUE THREAD

**Issue by javuto** [facebook/fbctf#237]
At the moment, the fbctf platform is translated in Hungarian (thanks @markszabo!) and English. Let's have it in Portuguese too!

**Comment by lucasloisp** [comment]
I would love to contribute here! I'll make a pull request once it is done

**Comment by RuanAragao** [comment]
https://github.com/RuanAragao/fbctf/blob/lang-pt/src/language/lang_pt.php

**Comment by javuto** [comment]
The translation to Brazilian Portuguese just merged (https://github.com/facebook/fbctf/pull/
