### ISSUE TITLE
Translate fbctf platform to Spanish

### ISSUE THREAD

**Issue by cixtor** [facebook/fbctf#238]
Hello, I noticed that you are requesting help from German, French, and Portuguese speakers to translate this project into those languages. I am a native Spanish speaker and would like to collaborate. Spanish seems to be missing from `./src/language/`. Would you be interested in a Spanish translation?

**Comment by javuto** [comment]
Hi! There is an open pull request to add the Spanish translation. It has been open for a while, so if the author does not reply soon, you can just open a new one. Here it is: https://github.com/facebook/fbctf/pull/189
