### ISSUE TITLE
Possibly use Let's Encrypt when provisioning in prod mode

### ISSUE THREAD

**Issue by gsingh93** [facebook/fbctf#24]
When provisioning in prod mode, users need to specify the path to their certificates they've generated themselves. For some users, this is fine, but others don't want to go through the hassle of creating their own certs. We should consider using Let's Encrypt to generate a cert during provisioning.

**Comment by javuto** [comment]
We can have an unified solution for both development and production, using Let's Encrypt. For development instead of generating a self signed certificate, we can use the flag `--test-cert`. More info here: [https://letsencrypt.org/getting-started/](https://letsencrypt.org/getting-started/)

**Comment by kelunik** [comment]
@javuto `--test-cert` just uses the staging server instead of the production one, so will generate non-trusted certificates. You still have to provide the challenges publicly available, so that's probably not an option.

**Comment by javuto** [comment]
Done and committed!

**Comment by javuto** [comment]
For tracking purposes: https://github.com/facebook/fbctf/commit/1efd073a88dbf6abc30cdf303133d62dae5b7879
