### ISSUE TITLE
Filter module reset view on refresh, maintaining the applied filter

### ISSUE THREAD

**Issue by javuto** [facebook/fbctf#241]
When the filter module reloads (top right corner), it does reset the filter in the view but the filter applied remains. For example, if we do apply a filter to display only the "Quiz" challenges, it will refresh and go back to "All", but the view is not consistent.

**Comment by gsingh93** [comment]
I think making a new cookie makes sense to persist this over page refreshes.

**Comment by slayerjain** [comment]
expertise in Php is necessary ?

**Comment by javuto** [comment]
Yes, this requires previous experience with PHP/Hack.
