### ISSUE TITLE
Translate fbctf platform to Chinese

### ISSUE THREAD

**Issue by javuto** [facebook/fbctf#246]
Add support for the platform in Chinese:

https://github.com/facebook/fbctf/tree/master/src/language

**Comment by slayerjain** [comment]
knowledge about Chinese required ?

**Comment by javuto** [comment]
Ideally, yes. Using Google translate is not the point here.

**Comment by fifiteen82726** [comment]
Traditional chinese or simplified chinese?

**Comment by javuto** [comment]
Up to you @fifiteen82726. If there is a big difference then we could have both! Thank you!

**Comment by theaulait** [comment]
If no one is assigned, I like to give it a try.

**Comment by qazbnm456** [comment]
Traditional Chinese translation is added. #360

**Comment by zyjs2016** [comment]
What's about  Simplified Chinese ?

**Comment by javuto** [comment]
Traditional Chinese is added. @zyjs2016 you can submit a PR with Simplified Chinese if you want!
