### ISSUE TITLE
Translate fbctf platform to Indonesian

### ISSUE THREAD

**Issue by javuto** [facebook/fbctf#250]
Add support for the platform in Indonesian:

https://github.com/facebook/fbctf/tree/master/src/language

**Comment by riyadd** [comment]
Does `dec` mean `decrement`? Which makes `Default Bonus Dec` means the number of bonus decreased from default value.

I guessed that based on the Hungarian translation.

**Comment by javuto** [comment]
Correct, that ```dec``` comes from decrement.

**Comment by MuzTank** [comment]
#248
