### ISSUE TITLE
What is the best debugging method?

### ISSUE THREAD

**Issue by brandonbryan12** [facebook/fbctf#258]
What debugging methods do you all use for this project? I'm trying to delve into the contents of a variable. Should I log the contents to a file, or is there a better way?

**Comment by javuto** [comment]
For me it works to just develop in the development machine (or using ```unison``` to sync files between host and dev machine) and using ```error_log()``` I can see the contents of variables in ```/var/log/hhvm/error.log```. You can modify the HHVM configuration file (```/etc/hhvm/server.ini```) to use a debugger, there are instructions to do that here: https://docs.hhvm.com/hhvm/configuration/INI-settings#debugger
