### ISSUE TITLE
Game Admin -> Controls -> Import levels (Does it work?)

### ISSUE THREAD

**Issue by englieh** [facebook/fbctf#262]
I did the quiz levels in my local machine. I export the levels and saw the generated json file.

However when I try to import the levels to the real game machine, no quiz levels are imported. I clicked on the Game Admin -> Controls -> Import Levels. I check the quiz levels and none are imported. Did I miss out something?

I will check the code but since the competition is 24 hours away, if there is a quick answer, it would be great.

Thanks.

**Comment by englieh** [comment]
Follow the fix from #231. No error but records are not inserted in mysql. Temporary fix by dumping the whole mysql DB which works.

**Comment by javuto** [comment]
Does it work if you apply the solution proposed in #231?

**Comment by englieh** [comment]
No error in logs or on browser. In fact, the browser message is successfully imported. Tried listing the rows in levels tables but not there. No time for further debugging for now. Dumping out the whole mysql db easier for me for now.

**Comment by englieh** [comment]
Found out that the issue is because the json output for entity is full name of the country but the codes and database are looking for iso_code. E.g Current output entity name is "Germany" but the value to compare is "DE" in the database.

**Comment by ffahrenholz** [comment]
Did you try to import a .json from the offical version? That does not work. In my fix the exporter also was changed. But an import of exported files within the fixed version should work.

**Comment by javuto** [comment]
I just verified that with the fix proposed by @ffahrenholz, it does work properly.
