### ISSUE TITLE
Reloading after code change.

### ISSUE THREAD

**Issue by koddsson** [facebook/fbctf#265]
Hey hey 👋 !

I'm wondering how I can get the vagrant machine to pick up code changes and refresh the app. Maybe I shouldn't be running in vargrant for developing?

Thanks!

**Comment by gsingh93** [comment]
Let me know if this answers your question: https://github.com/facebook/fbctf/issues/255#issuecomment-251053242

**Comment by koddsson** [comment]
It sure does! Thanks 😄
