### ISSUE TITLE
import doesn't work after "New PR to add import/export after rebase"

### ISSUE THREAD

**Issue by iMHLv2** [facebook/fbctf#266]
The "export full game" as JSON works fine, but clicking "import full game" doesn't work. Unfortunately I didn't save the error messages, but clicking import will dump a bunch of backtraces to /var/log/hhvm/error.log. It never opens a dialog to browse to the file you'd like to import. 

I'm not sure if its related, but while trying to troubleshoot, I saw some SQL queries that reference a `name` column in the `countries` table:

https://github.com/facebook/fbctf/blob/master/src/models/Level.php#L953

However according to the latest schema for the `countries` table, there is no `name` column defined:

https://github.com/facebook/fbctf/blob/master/database/countries.sql#L8

**Comment by javuto** [comment]
The fix for this was merged in https://github.com/facebook/fbctf/pull/292
