### ISSUE TITLE
Adding a basic problem viewer option

### ISSUE THREAD

**Issue by tjgerot** [facebook/fbctf#268]
I raise this issue as a suggestion towards potential enhancement of the FBCTF platform. Recently, H4ckIt CTF completed, but to the disappoint of many, was incredibly slow. Obviously this was an issue of the server not the CTF platform, taking minutes to display challenges. While I understand the platform should have instead been run on a faster server, I do think adding a "Switch to basic problem viewer" option (similar to that of picoCTF) that contains a list of all challenges, country names, point values, and drop-down descriptions and details would be quite helpful. Although the theme and UI/UX associated with the individual countries is fantastic, however for slow servers, and easy reading in general, I (and my fellow CTF writers/participants) would greatly appreciate such an option.

This is an enhancement suggestion. Thank you for your time.

**Comment by javuto** [comment]
Thanks for the feedback. Using the ```fbctf``` platform for an event with a large number of participants requires quite few tweaks in how the server is setup and also some changes in the platform itself. These changes are not ready yet to be part of the platform, as it is used by a majority of users. We are working on providing documentation on how to use the platform in a extreme performing scenario.
About your request, there is an issue open for exactly the same (https://github.com/facebook/fbctf/issues/16) and it is definitely needed. In the meantime, to just retrieve the challenges details you can use the endpoints exposed in ```https://FBCTF/data/...``` to get different JSON data files, with information such as teams, challenges, scoring...
Thank you for you suggestion and for using the platform! :)

**Comment by tjgerot** [comment]
Duplicate #16

**Comment by gsingh93** [comment]
@tjgerot: we also tried to email the organizer based on the email we got from CTF time so we could help out with server issues, but we didn't get a response.
