### ISSUE TITLE
Development mode: Vagrant can't read your current NFS exports

### ISSUE THREAD

**Issue by jashsayani** [facebook/fbctf#27]
I followed the README to run the project in development mode. I see the following error:

> Vagrant can't read your current NFS exports

I am not very familiar with Vagrant, so I am not sure if its an issue with the config file.

**Comment by mpomarole** [comment]
What OS are you running this in?
Could you past here the output of `vagrant --version``?

**Comment by jashsayani** [comment]
Im running: Mac OS X 10.11.5 Public Beta 

Vagrant 1.8.1

**Comment by javuto** [comment]
This seem to be a known issue with vagrant and OSX. Not directly caused by the fbctf platform: https://github.com/mitchellh/vagrant/issues/6360
