### ISSUE TITLE
Login Problem Ubuntu

### ISSUE THREAD

**Issue by KED323** [facebook/fbctf#270]
What username and password to login I need to use?

**Comment by lorentedford** [comment]
If its Debian root and debian i think

Loren Tedford (KC9ZHV)
Phone:
Fax:
Email: lorentedford@gmail.com
Email: KC9ZHV@KC9ZHV.com
http://www.lorentedford.com
http://www.kc9zhv.com
http://forum.kc9zhv.com
http://hub.kc9zhv.com
http://Ltcraft.net <http://ltcraft.net/>
http://voipham.com

**Comment by gsingh93** [comment]
Do you mean to log in to the platform? The username is admin, and the password is admin if you've provisioned in dev mode. If you've provisioned in production mode, the password was generated and printed out at the end of provisioning. If you need to reset that password, it's described in the readme.
