### ISSUE TITLE
Can't access or ping 10.10.10.5

### ISSUE THREAD

**Issue by rickyspanishh** [facebook/fbctf#275]
I am a student and i decided to take this on as a free time project, i followed the commands in the readme.md, i am not using vagrant. At the end of the installation it says fbctf is ready to use and i should open https://10.10.10.5, but i cant access it in my broswer and i cant ping it either. Is there something i am meant to do?

**Comment by Thewsomeguy** [comment]
If you're not using Vagrant, then it will be located at a different location. 10.10.10.5 is the private IP that the Vagrant instance uses.

**Comment by rickyspanishh** [comment]
I am running it on ubuntu 14.04, do you by any chance know what ip it is on? or where i can find the ip

**Comment by rdenman** [comment]
Login to the VM and run the command ifconfig, that will give you the IP address of the server. You'll probably have to configure the VM's network settings to be host-only or something along those lines if you're using VirtualBox

**Comment by javuto** [comment]
I just merged some code, that it will only will display the vagrant IP address 10.10.10.5 if the code is running within a vagrant environment. I hope that helps to clarify situations like this.
