### ISSUE TITLE
How-To: Upgrade Production

### ISSUE THREAD

**Issue by wisco24** [facebook/fbctf#277]
Team,

Is there any directions/method to upgrade in production mode?  I see merge's are happening, but I'm not sure how to enhance my current install without rebuild....

-Thanks

**Comment by javuto** [comment]
This is a fair request. Currently you will have to pull the latest updates in the code and make sure that autoload, javascript and hhvm index are all up to date. Let me add a mode of operation in the provisioning script that takes care of all this. Thanks for the suggestion!

**Comment by javuto** [comment]
Actually, this is already implemented with the ```--update``` parameter to the ```provision.sh``` script. However I am going to document this in the README.
