### ISSUE TITLE
/vendor/autoload not found causing a 500 server error code (blanc page of death)

### ISSUE THREAD

**Issue by vincentcox** [facebook/fbctf#28]
When using the development installation I get a 500 error code when browsing to the page. This is causing a blanc page.
This is the output of `tail /var/log/hhvm/error.log` :

`[Thu May 12 03:29:09 2016] [hphp] [2074:7f53877ff700:2:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Thu May 12 03:29:14 2016] [hphp] [2074:7f53877ff700:3:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Thu May 12 03:29:15 2016] [hphp] [2074:7f53877ff700:4:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Thu May 12 03:36:24 2016] [hphp] [2326:7fb626bff700:1:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
`
Any idea what went wrong?

**Comment by qazbnm456** [comment]
/vendor/autoload.php should be there if your installation is successful. Thus, I believe that there are some errors in your installation.

**Comment by vincentcox** [comment]
Strange, I used a fresh installation of the recommend Ubuntu 14.04 and followed the installation instructions from the readme file. Unfortunately, I am not experienced with hhvm or node.js to find the root cause.

**Comment by qazbnm456** [comment]
If you are willing to try another method, maybe you could try running with docker. I wrote some instructions [here](https://github.com/qazbnm456/dockerized_fbctf). But now can only run under dev mode.

To your question, maybe you could paste some installation logs here that you think it's some kind of error, which can help fbctf members to fix those potential problems.

**Comment by vincentcox** [comment]
Thanks! Docker seems a good option to test it out. 
I tried with another server, but now I allocated 4Gig Swap to ensure there was no memory issue. I also set the locales to avoid potential errors. But unfortunately I got the same 500 server error.
The output is listed here: http://pastebin.com/p2iXpuhR

**Comment by mpomarole** [comment]
@vincentcox Do you have your locale settings configured correctly? The vendor folder won't get created properly if you don't. I recommend following the instructions on this thread: http://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue

**Comment by vincentcox** [comment]
Thanks! It turns out it's indeed the locale problem. I configured my locales and now I have successfully installed it!

**Comment by colbyjoe1919** [comment]
I would recommend not wasting any more time and money on this matter.  I'm thinking we cut our losses not waste any more time on this guy.  He's got some kind of a fluke that's destroying giant wads of company resources.   Let's put it to the big man and u know let this guy and his broken bots go bounce around a rubber room.  

In hindsight I'd we stay on it and we really don't learn much more we are way in dutch.  Let's let this sleeping dog alone. What do you say gang?

**Comment by colbyjoe1919** [comment]
Ps we should maybe slip this guy a whole bunch of petty cash/visa cards you know for any "misunderstanding "  you never know with these drama queens .  Might as well stay on the safe sidem
