### ISSUE TITLE
Upload failure

### ISSUE THREAD

**Issue by Hestat** [facebook/fbctf#280]
I have set up two systems using the dev docker build and am unable to upload attachments to the flag levels, I saw someone previously had a similar issue they said they resolved it by changing the permissions in the attachments folder, I can't seem to resolve unless i am changing permission in the wrong place, 

I am editing /fbctf/src/data/attachments

any thoughts or someone who can point me in the right direction?

**Comment by Hestat** [comment]
Still no way I figured how to resolve the folder permissions in docker, saw someone else post a link to this setup guide, with it I have a fully functioning game environment, maybe you should add it to the main page as an alternate guide to installing, could resolve a lot of question I think.

https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki/Installing-FBCTF

**Comment by qazbnm456** [comment]
@Hestat Do you still have problems uploading attachments to flag levels? I've tried to build from the latest repo today with dev environment through docker, and I did not encounter that problem, which means I can upload attachments to flag levels successfully.

You may try the latest build again :)

**Comment by jtylers** [comment]
I also have this problem.  I am not using docker, but it is a production environment on the master branch.  File uploads were working a previous commit and then after upgrading it stopped working.

**Comment by shreyanshu7101904** [comment]
how to start this web server on 10.0.2.15  m
on my mozilla firrefox browser

**Comment by iangcarroll** [comment]
Please open your own issue, @shreyanshu7101904.

**Comment by stevcoll** [comment]
Permissions should be fixed with #535
