### ISSUE TITLE
It finishes installing but it doesnt prompt for the ssl key or cert

### ISSUE THREAD

**Issue by farooqy** [facebook/fbctf#30]
If finishes installing all but it shows these few errors 
at the top:-
[+] Copying all CTF code to destination folder
rsync: change_dir "/home/ubuntu/workspace/fbctf//pwd" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]

and then at the end:-

chmod: cannot access ‘/var/www/fbctf/src/data/attachments’: No such file or directory
chmod: cannot access ‘/var/www/fbctf/src/data/attachments/deleted’: No such file or directory
./extra/provision.sh: line 99: log: command not found

I ran both prod and dev, none of them worked. Please help.

**Comment by mpomarole** [comment]
You need to run provision with 
```
./extra/provision.sh dev `pwd`
```
Instead of 
```
./extra/provision.sh dev pwd
```

pws is a unix command that will print out your correct directory. Which is the path where you cloned fbctf.

**Comment by farooqy** [comment]
Thanks it worked, I entered the ssl cert and key directories, it was successful, but the nginx seems to fail again, and mysql server. Below is where the error begins to the end.

nginx: [emerg] PEM_read_bio_X509_AUX("/etc/nginx/certs/fbctf.csr") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: configuration file /etc/nginx/nginx.conf test failed
 * Restarting nginx nginx                                              [fail] 
[+] Installing Unison 2.48.3
[+] Remember install the same version of unison (2.48.3) in your host machine
[+] Creating DB - fbctf
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[+] Importing schema...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[+] Importing countries...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[+] Importing logos...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[+] Creating user...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[+] DB Connection file
[+] Adding default admin user
[+] The password for admin is: cf5acb5ee161c98d55c962d79b345f03
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[+] fbctf deployment is complete! Ready in https://10.10.10.5

**Comment by qazbnm456** [comment]
@farooqy You should double check if certs are loading correctly, and typing `service mysql start` to solve "Can't connect to local MySQL server through socket" problem.

**Comment by farooqy** [comment]
@qazbnm456 I started mysql but now access is denied, but it generates the password for the site, but the site doesnt load.

ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by qazbnm456** [comment]
After mysql server started, you are supposed to import db like extra/lib.sh did.

**Comment by gsingh93** [comment]
Let us know if you're still having issues.
