### ISSUE TITLE
Fatal hphp error after fresh install: ../vendor/autoload.php not found. 

### ISSUE THREAD

**Issue by rverton** [facebook/fbctf#31]
I just did a fresh install (development install instructions without vagrant) to test this platform and see how it works. After installing successful on Ubuntu 14.04, I get a HTTP ERROR 500 when connection via https.

_/var/log/hhvm/error.log_

    [Thu May 12 14:36:44 2016] [hphp] [7068:7f3385fff700:3:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3

**Comment by mpomarole** [comment]
@rverton, you seem to have the same problem detailed on #28. Could you follow the steps posted there?
