### ISSUE TITLE
HOW TO

### ISSUE THREAD

**Issue by shargon** [facebook/fbctf#314]
How can i made a dynamic flag with dynamic attachment. Only valid for this user session?

Sample:
Decode this message 0101001010101010101010101

Next time...
Decose this message: 111101010100101010

Thanks

**Comment by gsingh93** [comment]
We don't support this, and I don't think we ever will. You should give the link to a server in the problem, and the server can take care of making a different message each time.

**Comment by shargon** [comment]
But the flag must be diferent for prevent copy&paste
