### ISSUE TITLE
Test OK but with Warning:  N8facebook6common12mysql_client16AsyncMysqlClientE

### ISSUE THREAD

**Issue by inche-ali** [facebook/fbctf#316]
PR #315 Test succeed, but this warning..
I'm not sure what is the problem is it hhvm or phpunit
![warning](https://cloud.githubusercontent.com/assets/15242910/19837722/b4157242-9efa-11e6-9fc3-189ba0cbf231.gif)

**Comment by iangcarroll** [comment]
facebook/hhvm#6653?
