### ISSUE TITLE
Error in HHVM

### ISSUE THREAD

**Issue by landmanmanc** [facebook/fbctf#32]
Installed the source with the dev option on ubuntu 14.04 (64Bit)  

Had to install hhvm manually because it failed with the script. After installation nginx gives a http 500 error.

In /var/log/hhvm/error.log the following does occure :  

Catchable fatal error: Hack type error: Unbound name: :xhp (an object type) at /var/www/fbctf/src/Router.php line 26

Any idea how to fix this ?

**Comment by mpomarole** [comment]
I am going to guess `composer install` didn't finish properly and didn't create the autoload map correctly. 
Could you try running the provision script again?

```
./extra/provision.sh dev `pwd`
```

**Comment by cmtzco** [comment]
I tried running the provision script again, had to manually install hhvm.  Instructions here https://docs.hhvm.com/hhvm/installation/linux#ubuntu-14.04-trusty 


Used the following for 14.04
```
sudo apt-get install software-properties-common

sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
sudo add-apt-repository "deb http://dl.hhvm.com/ubuntu $(lsb_release -sc) main"
sudo apt-get update
sudo apt-get install hhvm
```

**Comment by mpomarole** [comment]
I am closing this. Feel free to re-open if you are still having issues.
