### ISSUE TITLE
Display a different message to the user when they submit an answer and scoring is off

### ISSUE THREAD

**Issue by gsingh93** [facebook/fbctf#321]
When scoring is off, we tell the user their answer is wrong. Instead we should tell them whether or not their answer is correct, but also say scoring is disabled and not give them any points.

**Comment by javuto** [comment]
This also can apply when the solution is correct and we want them to have a follow up link or some other information.

**Comment by javuto** [comment]
Integrate this issue with the previous one: https://github.com/facebook/fbctf/issues/167

**Comment by gsingh93** [comment]
They feel like two separate issues to me. This issue is about changing the "incorrect" text to something like "scoring is off". The issue you closed requires more UI work, as well as adding the relevant form inputs to the admin UI.

**Comment by javuto** [comment]
This is implemented in https://github.com/facebook/fbctf/pull/420
