### ISSUE TITLE
/tmp/SCORE_POINTS

### ISSUE THREAD

**Issue by sergiownd** [facebook/fbctf#326]
In the base levels y should use a agent running the SCORE_POINTS.
So where can I find the file?

**Comment by inche-ali** [comment]
Target System (eg. 192.168.1.3)
------------------------------------------------
_/tmp/SCORE_POINTS_   

- this is a file that a team should write their team name on

_score_base.py_   

- this is an agent ( always running) act as http server (eg. listen on port 12345) 
- this agent will read the content of /tmp/SCORE_POINTS and serve a json response containing the team name

Scoring system (this fbctf server)
------------------------------------------------
_bases.php_ 
- this is a file that run as a daemon every 5 min. will do http request to the target system.
- it will receive the latest team name from the json response & gives point that team

-------------------------------------------------

So in the base level settings:  
- create a new base level and save.
- then edit it, add a link with this value **192.168.1.3:12345**  and save

I hope this will help..

**Comment by sergiownd** [comment]
Thank you for your answer it helps a lot

**Comment by Console** [comment]
Checking this due to the reference.

Interesting info that should be in the wiki but does not resolve a core issue.
