### ISSUE TITLE
forget password

### ISSUE THREAD

**Issue by lazybootsafe** [facebook/fbctf#327]
may i ask a question：i don't know ‘admin’ password，plz tell me password or how to change password.
i have test ：
bash lib.sh
set_password new_password root root fbctf $PWD
but it says ：set_password：command not found

what should i do now？help，THX

**Comment by gsingh93** [comment]
Follow the exact instructions in the README:
```
. ./extra/lib.sh
set_password new_password ctf ctf fbctf $PWD
```
