### ISSUE TITLE
Vagrant up fails on Windows Host

### ISSUE THREAD

**Issue by jonygrimes** [facebook/fbctf#33]
Running `vagrant up` to do local development on a Windows host fails due to the default [git line endings behavior](https://help.github.com/articles/dealing-with-line-endings/).  This causes the provisioning script to fail when it sources `extra/lib/.sh`.

This behavior can be fixed with a `.gitattributes` file forcing `LF` line endings for `*.sh` files.

Output of `vagrant up` on Windows 7:
```
...
==> default: [+] Provisioning in dev mode
==> default: [+] Creating code folder /var/www/fbctf
==> default: [+] Copying all CTF code to destination folder
==> default: [+] Setting permissions
==> default: /var/www/fbctf/extra/lib.sh: line 2: $'\r': command not found
==> default: /var/www/fbctf/extra/lib.sh: line 5: $'\r': command not found
==> default: /var/www/fbctf/extra/lib.sh: line 6: syntax error near unexpected token `$'{\r''
'=> default: /var/www/fbctf/extra/lib.sh: line 6: `function log() {
==> default: /tmp/vagrant-shell: line 38: set_motd: command not found
==> default: /tmp/vagrant-shell: line 41: package: command not found
...
```

**Comment by mpomarole** [comment]
I am closing this since the PR is in. @jonygrimes feel free to re-open if you are still having issues.
