### ISSUE TITLE
admin cannot login

### ISSUE THREAD

**Issue by jonghorhee** [facebook/fbctf#349]
I did install FBCTF vagrant way with hhvm v3.14.5 on 10 Sep, working good previously.
And I've got login fail with 'admin' in 2 months. password is correct.
Fbctf is latest version via 'git pull'.

Fbctf does just redirect to /index.php from /index.php?page=login
I attach some hhvm error.log when admin login.

> [Tue Nov  8 10:19:21 2016] [hphp] [1206:7fe1b7bff700:135:000001] [] Unhandled server exception: exception 'AsyncMysqlQueryException' with message 'Error executing AsyncMysql operation: Failed (mysql error: 1054: Unknown column 'last_page_access' in 'field list')' in /var/www/fbctf/src/SessionUtils.php:69\nStack trace:\n#0 (): HH\\WaitHandle->join()\n#1 /var/www/fbctf/src/SessionUtils.php(69): HH\\Asio\\join()\n#2 (): SessionUtils::write()\n#3 (): call_user_func()\n#4 (): __SystemLib\\SessionForwardingHandler->write()\n#5 {main}
[Tue Nov  8 10:19:21 2016] [hphp] [1206:7fe1b7bff700:135:000002] [] stream error
[Tue Nov  8 10:19:21 2016] [hphp] [1206:7fe1b7bff700:135:000003] [] Unable to compress response: level=3 len=0
[Tue Nov  8 10:19:21 2016] [hphp] [1206:7fe1b7bff700:136:000001] [] #0 /var/www/fbctf/src/Router.php(69): SessionUtils::enforceLogin()\n#1 /var/www/fbctf/src/Router.php(19): Router::genRouteNormal()\n#2 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#3 /var/www/fbctf/src/index.php(17): genInit()\n#4 {main}
[Tue Nov  8 10:19:21 2016] [hphp] [1206:7fe1b7bff700:136:000002] [] Unhandled server exception: exception 'AsyncMysqlQueryException' with message 'Error executing AsyncMysql operation: Failed (mysql error: 1054: Unknown column 'last_page_access' in 'field list')' in /var/www/fbctf/src/SessionUtils.php:69\nStack trace:\n#0 (): HH\\WaitHandle->join()\n#1 /var/www/fbctf/src/SessionUtils.php(69): HH\\Asio\\join()\n#2 (): SessionUtils::write()\n#3 (): call_user_func()\n#4 (): __SystemLib\\SessionForwardingHandler->write()\n#5 {main}
[Tue Nov  8 10:19:21 2016] [hphp] [1206:7fe1b7bff700:137:000001] [] Unhandled server exception: exception 'AsyncMysqlQueryException' with message 'Error executing AsyncMysql operation: Failed (mysql error: 1054: Unknown column 'last_page_access' in 'field list')' in /var/www/fbctf/src/SessionUtils.php:69\nStack trace:\n#0 (): HH\\WaitHandle->join()\n#1 /var/www/fbctf/src/SessionUtils.php(69): HH\\Asio\\join()\n#2 (): SessionUtils::write()\n#3 (): call_user_func()\n#4 (): __SystemLib\\SessionForwardingHandler->write()\n#5 {main}
[Tue Nov  8 10:19:21 2016] [hphp] [1206:7fe1b7bff700:137:000002] [] stream error
[Tue Nov  8 10:19:21 2016] [hphp] [1206:7fe1b7bff700:137:000003] [] Unable to compress response: level=3 len=0

**Comment by jonghorhee** [comment]
I solved this issue now.
Drop table sessions then create sessions (changed scheme.sql in database dir) on mysql.

$ **mysql -u ctf -p fbctf**
Enter password: **ctf**

mysql> **select * from sessions;**
mysql> **DROP TABLE IF EXISTS `sessions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cookie` text NOT NULL,
  `data` text NOT NULL,
  `team_id` int(11) NOT NULL,
  `created_ts` timestamp NOT NULL DEFAULT 0,
  `last_access_ts` timestamp NOT NULL,
  `last_page_access` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;**

**Comment by javuto** [comment]
Yup, the DB schema has changed since Sept 10th so the fix would be to just update it. However we could warn the users that the schema has changed, instead of just fail gracefully...

**Comment by wisco24** [comment]
I had this same issue after running an update command.  The above fixed it for me as well!.  Thanks!

**Comment by shargon** [comment]
Dosen't work for me...
