### ISSUE TITLE
CPU Leak

### ISSUE THREAD

**Issue by wisco24** [facebook/fbctf#353]
I used the software for a small test event last week.  I noticed that before the game, the CPU was at 1-2%,  during the game it jumped to about 20-25%, and then after the game ended (no more users accessing at all), it stayed at 20-25%.  It stayed at that overnight, then when I rebooted it, it was back to the normal 1-2%.

Any ideas?  This is an issue for me since I use burstable instances on AWS, and the 20-25% burns the credits when there really isn't a load on it.  When I run "top" it appears to be hhvm that is consuming the CPU.......

**Comment by javuto** [comment]
Did you stop the game? Were there any bases running? If you keep a game running indefinitely there are things that happen in the backend, for example, every 5 minutes (300 seconds) we take the current score for all teams and write them in the table ```progressive_log```. If there are active bases, this is even more often (5 seconds by default).

**Comment by wisco24** [comment]
Game was stopped. 

Only used flags in this game. No bases.

**Comment by javuto** [comment]
@gsingh93 suggested to downgrade the package to use the oldest LTS (3.12) and see how that goes. For now, the only mitigation seems to be running ```sudo service hhvm restart``` after the CTF is finished.

**Comment by javuto** [comment]
@wisco24 in the last few days there has been critical changes to how the access to the DB is done and I believe that will have an impact in the performance of the platform. Please try again with the new changes and let us know. If there is no changes and the CPU usage remains high, you can mitigate by running ```sudo service hhvm restart``` in any case I will close this issue for now. Thank you!
