### ISSUE TITLE
How do you solve  Hash Sum mismatch during installation of fbctf in ubuntu 14.04 

### ISSUE THREAD

**Issue by ezracyber** [facebook/fbctf#354]
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/i18n/Translation-en  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by gsingh93** [comment]
I've never seen this. Is this after running our provision script? Is this on Vagrant?

**Comment by javuto** [comment]
If this happened if a brand new Vagrant, must be a problem with the image. In any case, you can solve it easily running this ```sudo rm -rf /var/lib/apt/lists/*```. After that just ```sudo apt-get update``` and you should be good to go.

**Comment by ezracyber** [comment]
Thanks for response, but i have tried this but it didnt work, does your ubuntu server 14.04 don`t give this error during sudo apt-get update before starting installation, which result to failed fbctf installation?

**Comment by ezracyber** [comment]
All the ubuntu 14.04  images
 am trying to use has this issue.

**Comment by iangcarroll** [comment]
Is something interfering with your internet connection? You should try `curl`ing one of those files and see if something is being injected into them, or see if you can `apt update` on a normal Ubuntu machine.

**Comment by ezracyber** [comment]
Thanks iangcarroll will try , see what will come out.

**Comment by ezracyber** [comment]
Thanks guys lastly i was able to resolve, it was network issue, thank you
