### ISSUE TITLE
HHVM Cache Rebuild

### ISSUE THREAD

**Issue by jeszicawii** [facebook/fbctf#361]
Thank you for the help with issue #358 , really appreciated!

I have a simple question. I often populate the database with my own categories, when I come to delete them it often still shows they are there. I have to perform an action through the admin interface before they will disappear.

Just wondering if there is anyway to reset the cache after I perform such database functions?
It wasn't an issue until the memcache updates yesterday.

**Comment by justinwray** [comment]
You can clear all cache in Memcached via the command line:

`echo 'flush_all' | nc localhost 11211`

This will reset all the cache and rebuild it as needed.

**Comment by jeszicawii** [comment]
It works, thank you!
This has solved all my problems.
