### ISSUE TITLE
Fatal error when delete a team registered with token

### ISSUE THREAD

**Issue by johnny-y-wang** [facebook/fbctf#364]
`[hphp] [35102:7fda383ff700:2:000001] [] \nCatchable fatal error: Value returned from async method MultiTeam::genTeam() must be of type Team, null given in /var/www/fbctf/src/models/MultiTeam.php on line 81
`

When a team registered with token is deleted, the admin front page could not be loaded because in the token table the token used for registration is still linked to the teamID, and the teamID could not be found.

**Comment by gsingh93** [comment]
cc: @justinwray

**Comment by justinwray** [comment]
This is related to the larger issue with various team data remaining after a team has been deleted.  See issue #111.  For a quick (temporary) fix see Issue #206.

@gsingh93 We should look at a PR for a permanent fix to the overall team deletion process, either with cascading deletes to the relevant tables in #206, or with a delete flag on deleted data.

**Comment by justinwray** [comment]
This issue should be resolved in PR #372.
