### ISSUE TITLE
overhaul for session

### ISSUE THREAD

**Issue by kazenomamani210** [facebook/fbctf#368]
1. When admin user changed team's password, that team's session should be invalidated.

2. When admin user set team off on team, that team's session should be invalidated.

Problem: The team can still capture the flag after team off.

3. When admin user set login off, all team's session should be invalidated(except admin's session).

4. When admin user deletes team, that team's session should be deleted completely.

Problem: If team has multiple sessions, that team can still remain on the game after account deletion.

5. When admin user removed admin privilege from another admin user, that admin user's session should be changed to non-admin user's session immediately.

Problem: non-admin user can work as admin user until that user logs out after admin user removed admin privilege from another admin user.

**Comment by kazenomamani210** [comment]
There are so many problem on session... who made this platform? I hope someone can fix these issues...

**Comment by justinwray** [comment]
Session Invalidation is actual in progress, the PR was pending the merge of PR #347. Now that #347 has been merged this will be addressed.

**Comment by kazenomamani210** [comment]
@justinwray Please try these steps. 

1. User login from 2 different browser in order to create 2 sessions.

2. Admin user deletes team.

Problem: This will only delete 1 session, not all sessions(session invalidation).  After this step, admin user won't be able to access "session" page from admin panel.

3. Reload #1 browsers, you will see one is logout, the other has still session.

**Comment by justinwray** [comment]
@kazenomamani210 Yes, the new invalidation code has not been submitted via PR yet.

**Comment by kazenomamani210** [comment]
New PR adreesses this issue. I am going to close this. Thanks @justinwray

**Comment by kazenomamani210** [comment]
close
