### ISSUE TITLE
Issuer Certificate Not Found

### ISSUE THREAD

**Issue by putthik** [facebook/fbctf#37]
I installed the source with the dev option on ubuntu 14.04 (64Bit) 

After finish i got this error

`rm: cannot remove ‘/etc/nginx/sites-enabled/default’: No such file or directory
ln: failed to create symbolic link ‘/etc/nginx/sites-enabled/fbctf.conf’: File exists
`
`nginx: [warn] "ssl_stapling" ignored, issuer certificate not found`

`* Restarting nginx nginx                                                [fail]`

`[+] Installing Unison 2.48.3
[+] Remember install the same version of unison (2.48.3) in your host machine
[+] Creating DB - fbctf
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
[+] Importing schema...
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
`

[http://s32.postimg.org/typ9544qt/error.png](url)

Noted: my sql don't have password, i mean it's blank password. 
Anyone can solved this problem? i really need your help. :(
Thanks b4 hands,

**Comment by sundw2014** [comment]
Password of mysql is set in ```extra/provision.sh``` (line 2).
```
P_ROOT="root"
```

You can just ignore the nginx warning  ```issuer certificate not found```. It does't matter.

**Comment by putthik** [comment]
Sundw2014: thanks :)
