### ISSUE TITLE
unable to login as admin

### ISSUE THREAD

**Issue by fvleminckx** [facebook/fbctf#373]
When logging in as admin I get redirected to the index page again, unable to login.

error from 

> /var/log/hhvm/error.log

`[Mon Nov 28 10:40:52 2016] [hphp] [17:7f155d7ff700:29:000001] [] #0 /var/www/fbctf/src/Router.php(70): SessionUtils::enforceLogin()\n#1 /var/www/fbctf/src/Router.php(19): Router::genRouteNormal()\n#2 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#3 (): genInit()\n#4 (): HH\\WaitHandle->join()\n#5 /var/www/fbctf/src/index.php(17): HH\\Asio\\join()\n#6 {main}`

I run the docker way in dev mode.

**Comment by wisco24** [comment]
Take a look at #349.  Your logs look very similar.

**Comment by KALRONG** [comment]
Same issue with the same log also in docker dev mode

**Comment by viennaoperator** [comment]
i got the same issue, I used vagrant to install the vm
