### ISSUE TITLE
Teamdata

### ISSUE THREAD

**Issue by johnny-y-wang** [facebook/fbctf#374]
Team data (players names etc) on the registration form doesn't get submitted to server. More precisely they are not even included in the registration AJAX request. Could someone take a look into it?

**Comment by javuto** [comment]
Looking into it

**Comment by javuto** [comment]
Just tried this in the current master revision (17b4782a0f66e3110cdf84d7173512eadfd88602) and it does register the names and email addresses in the ```teams_data``` table.
Make sure you have enabled registration and teams names and you are running the latest code.
