### ISSUE TITLE
Cannot Logon as Admin (fresh install)

### ISSUE THREAD

**Issue by BinaryWasp** [facebook/fbctf#375]
I did a prod install with self-signed cert. 
I took note of the long password and was able to sign in. I entered new categories and questions and all was fine. Now I'm unable to logon. After entering bad credentials, it still stays at the logon page. Upon entering good credentials, I am pushed to the index.php page and cannot progress further. 

I ran the following code as the site suggested and neither the old or new password (new_password) work. I'm now unable to logon. Please help!

`./extra/lib.sh
set_password new_password ctf ctf fbctf $PWD`

I am able to logon to the dabase and check the hash value before and after the password reset script and the value does not change, so I don't think it's successfully running. 

Upon a "successful" logon (attempting to logon with known good credentials) the file , /var/log/hhvm/error.log produces the following error: 
`[Thu Dec 1 15:13:31 2016] [hphp] [10420:7f4d80fff700:2642:000001] {} #0 /var/www/fbctf/src/Router.php(70): SessionUtils::enforceLogin()\n#1 /var/www/fbctf/src/index.php(17): genInit*(\n$4 [main]`

![good_logon](https://cloud.githubusercontent.com/assets/6795391/20817088/4e608d2e-b7eb-11e6-8c04-15db1a5f4a52.png)

**Comment by BinaryWasp** [comment]
Lovely! Now upon rebooting the machine I get 502 Bad Gateway. 
Please help!

**Comment by javuto** [comment]
The fix for the 502 Bad Gateway on reboot is on the way (https://github.com/facebook/fbctf/pull/376). Have you just cloned the repository?

**Comment by BinaryWasp** [comment]
Yes, this was a simple clone of the repository. 
Output of git rev-parse HEAD:
`a71b7a772e2cb6bcde49d317ad431f52376bc063`

**Comment by javuto** [comment]
The fix for the 502 Bad Gateway on reboot is already merged.
I just cloned the repo, provisioned it with a self-signed certificate and in production mode and then tried to change the admin password and it worked perfectly. Try to run these commands to change the admin password:
```cd /var/www/fbctf```
```source extra/lib.sh```
```set_password my_new_password ctf ctf fbctf $PWD```

**Comment by BinaryWasp** [comment]
Confirmed working now. The syntax @javuto provided was different in the implementation documenting the password change...but now it's working great. Thanks so much for your assistance. This is a great CTF platform. I'm planning on demoing this for the Dallas Hackers Association soon. The InfoSec community of North Texas thanks you greatly!

**Comment by javuto** [comment]
It may be inconsistency in the sessions, there is a PR up to address some of that. In any case, I am glad it is (or was) working. I am going to modify the documentation to make it more clear. Thank you for using it and provide feedback! 👍

**Comment by iangcarroll** [comment]
I cannot login with the Docker image either. Something is resetting the session whenever a POST request is made. `/var/lib/hhvm/sessions` is empty, which I suspect is the issue, but HHVM runs as root inside the Docker container and I'm not sure why it wouldn't be writing.

**Comment by KALRONG** [comment]
Im having the same issue as iangcarrol, fresh docker image, every time i put the admin credentials im just redirected to the home page without any kind of error.
