### ISSUE TITLE
Unable to Edit Main Home Page after LDAP Integration

### ISSUE THREAD

**Issue by Mugonta** [facebook/fbctf#377]
I have tried everything that I can think of to be able to edit the main IndexController.php file located in the /var/www/fbctf/src/controllers to be able to edit the text displayed on the homepage as well as updating the rules to be more inline with what I am doing. After the LDAP update this information is now being ignored. I have tried clearing the cache in the browser as well as temporary files. The changes are saved to the IndexController.php file but the website does not reflect these changes. I have also attempted to update the language file to see if that resolved the issues and still that does not work. Any suggestions would be extremely helpful to be able to edit the homepage as well as the rules again and to allow them to be shown.

**Comment by javuto** [comment]
Can you specify what is the LDAP update? You mean after this commit? https://github.com/facebook/fbctf/commit/17b4782a0f66e3110cdf84d7173512eadfd88602

**Comment by Mugonta** [comment]
Juvuto yes It would have had to have been after that commit. I have an older commit that it works fine on that came out just before the LDAP integration push on 17b4782.

**Comment by javuto** [comment]
I seriously doubt that has anything to do with that specific commit but whatever. I believe you are running the platform in production mode, which by default enables HHVM Repo Authoritative mode and compiles all php code into bytecode, never reading the source for changes. So here are the steps you need to follow after making changes to ```src/language/lang_en.php```, to change the displayed text in the main page (presuming you have the platform in ```/var/www/fbctf```:
```
sudo rm -Rf /var/cache/hhvm/hhvm.hhbc
sudo sudo hhvm-repo-mode enable "/var/www/fbctf"
sudo chown www-data:www-data /var/cache/hhvm/hhvm.hhbc
sudo service hhvm restart
```
After that you should see your changes live.

**Comment by Mugonta** [comment]
Thank you and yes you are correct I am in production mode.


Thank you for assisting Javier
