### ISSUE TITLE
maybe router or SSL issue

### ISSUE THREAD

**Issue by zky001** [facebook/fbctf#38]
I installed it with README.md,and I type my ip with https://, open my chrome,the out put as follows
`{ try { $response = await Router::genRoute(); echo $response; } catch (RedirectException $e) { error_log($e->getTraceAsString()); http_response_code($e->getStatusCode()); Utils::redirect($e->getPath()); } } /* HH_IGNORE_ERROR[1002] */ \HH\Asio\join(genInit());`

**Comment by mpomarole** [comment]
Could you paste the output of the provision script and `/var/log/hhvm/error.log`?

**Comment by zky001** [comment]
I haven't find `/var/log/hhvm/error.log` such file and my ubuntu's ip is 115.159.190.235

**Comment by gsingh93** [comment]
Were there any errors in the output of the provision script? Can you describe the _exact_ steps you took to install it?

**Comment by zky001** [comment]
sure,I just follow the introduction by typing `git clone https://github.com/facebook/fbctf
cd fbctf
./extra/provision.sh prod $PWD`

**Comment by gsingh93** [comment]
Can you paste the exact output of running that script?

**Comment by zky001** [comment]
`[+] Installing Unison 2.48.3
[+] Remember install the same version of unison (2.48.3) in your host machine
[+] Creating DB - fbctf
ERROR 1007 (HY000) at line 1: Can't create database 'fbctf'; database exists
[+] Importing schema...
[+] Importing countries...
[+] Importing logos...
[+] Creating user...
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'ctf'@'localhost'
[+] DB Connection file
[+] Adding default admin user
[+] The password for admin is: 9cdc81f372aa0d3ff9921824aaf0bb55
/var/www/fbctf/extra/lib.sh: line 176: hhvm: command not found
[+] fbctf deployment is complete! Ready in https://10.10.10.5
`

**Comment by zky001** [comment]
这个问题一直存在
`/var/www/fbctf/extra/lib.sh: line 176: hhvm: command not found`
[+] Installing hhvm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hhvm

**Comment by mehnomy** [comment]
Hello @zky001,

> E: Unable to locate package hhvm


Could you please follow my guide, this will resolve your current issue and upcoming issues.
https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki

**Comment by gsingh93** [comment]
Please reopen if you're still having issues.
