### ISSUE TITLE
Stabilize master branch by introducing GitFlow process

### ISSUE THREAD

**Issue by bkimminich** [facebook/fbctf#380]
It would be great if the `master` branch wouldn't be used for ongoing development but act as a _latest release_ or _stable_ branch instead. If development would instead happen on a separate `develop` branch, it would be less likely to end up with a broken environment after an unlucky pull from `master`.

> Instead of a single master branch, this workflow uses two branches to record the history of the project. The master branch stores the official release history, and the develop branch serves as an integration branch for features. It's also convenient to tag all commits in the master branch with a version number.

(see https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

Depending on the number of contributors this models works perfectly fine without any feature branches. And since GitHub allows to choose the target branch for PRs now when merging, it has become even easier to apply.

**Comment by javuto** [comment]
We are starting a new branch `dev` to make sure `master` will be always stable. Also, eventually we will tag the first version, once we have closed off some requested features and we feel we are in a good position.
