### ISSUE TITLE
What is score_base.py actually doing?

### ISSUE THREAD

**Issue by jake-walker** [facebook/fbctf#382]
I am organising a CTF game and I'm not sure about bases. I saw this `score_base.py` file but after reading it I don't get what it's doing and what `/tmp/SCORE_POINTS` is for. Please can someone explain what this does?

**Comment by javuto** [comment]
Bases are the type of levels that allow you to have a type of game called king of the hill. It means that there is one resource that will be owned by one team only at a time. For example, imagine there is a server that is vulnerable and allows to execute code remotely, the first team that is able to compromise that server will get the points. One way to distribute the points in these scenarios is to have the teams putting their team names in the file ```/tmp/SCORE_POINTS```. Then ```score_base.py``` will be running in the machine and polling that file regularly. The scoreboard will then retrieve the content of that file (every 300 seconds/5 minutes by default) sending a HTTP request to the port ```:12345``` and ```score_base_py``` handles that too. We are working on having better documentation with bases and also the ability to customize some of their parameters (file to check, port to use...). Does this clarify at least a bit?

**Comment by jake-walker** [comment]
Yes that's great.

**Comment by jake-walker** [comment]
Also one more thing. What exactly is the python script sending on a get request? Is it just the teams name?

**Comment by javuto** [comment]
As you can see here https://github.com/facebook/fbctf/blob/master/extra/score_base.py#L61 it sends a JSON blob, with the team name and the team name md5 hash. That is requested from the platform here https://github.com/facebook/fbctf/blob/master/src/models/Level.php#L1083 and processed here https://github.com/facebook/fbctf/blob/master/src/scripts/bases.php#L23
Like I said, this part of the platform requires more work to make it more easy to use and customize.

**Comment by jake-walker** [comment]
Ok thanks very much.
