### ISSUE TITLE
Most recent update issue 

### ISSUE THREAD

**Issue by deathburnz** [facebook/fbctf#386]
Hello,

I was doing a fresh installation and when using:
./extra/provision.sh -m prod -s $PWD

The script stops at the point shown on the attachment.
I think either the folder should be changed from cache to run or the "/" in the end is an extra.

![script](https://cloud.githubusercontent.com/assets/24357489/20925219/09063a5c-bbcf-11e6-9e67-8e8dc7995f29.PNG)

**Comment by javuto** [comment]
Just landed the fix for it. Thanks for reporting it!
