### ISSUE TITLE
Sizing Question

### ISSUE THREAD

**Issue by wisco24** [facebook/fbctf#388]
All,

What is the largest event anyone has run with this software?  I'm looking at using it for a 70 team event (1 user per team) in late January.   Has anyone tried it at that scale?    

Also is there a slack group or message board for discussions like this instead of the Issues list?

Thanks!

**Comment by gsingh93** [comment]
Questions like this are fine here, we don't have a slack.

We've hosted an event about that large on a single large EC2 instance. I occasionally had to restart HHVM (`sudo service hhvm restart`), but I think that problem should be fixed now.
