### ISSUE TITLE
Admin Error Cant Login ?

### ISSUE THREAD

**Issue by NeoVilsonWong** [facebook/fbctf#39]
Admin Error Cant Login ?
[fbctferror.log.txt](https://github.com/facebook/fbctf/files/263697/fbctferror.log.txt)

**Comment by NeoVilsonWong** [comment]
@mpomarole ,hi sorry for disturb can you help me see this? success but cant login with admin account~

**Comment by mpomarole** [comment]
@NeoVilsonWong  what was the user and password you used to login?

**Comment by NeoVilsonWong** [comment]
@mpomarole admin : password right? after finished install there mention like this~

**Comment by NeoVilsonWong** [comment]
@mpomarole 
<img width="369" alt="screen shot 2016-05-14 at 1 07 14 am" src="https://cloud.githubusercontent.com/assets/7342012/15255702/3b6fb2a4-1970-11e6-863e-08f5a1fe2d53.png">

**Comment by christ0ph3r** [comment]
I had a similar issue.  I installed it on a brand new ubuntu 14.04 server on the dev mode with out Vagrant.

```
sudo apt-get install git
git clone https://github.com/facebook/fbctf
cd fbctf
./extra/provision.sh dev `pwd`
```

Once I got to the login page I put 

admin
password

and it did not work and the form fields turned red.  I copied and pasted it from the terminal and it did not work.

**Comment by NeoVilsonWong** [comment]
@christ0ph3r ,

same issue here~

**Comment by christ0ph3r** [comment]
I tried again.  The only thing I did differently was use a $10 server instead of a $5.  The login works now.

**Comment by NeoVilsonWong** [comment]
@christ0ph3r ,

lol? seriously???? damn!!

you got fix the locale?

**Comment by mpomarole** [comment]
@christ0ph3r, @NeoVilsonWong could you paste the contents of `/var/log/hhvm/error.log` after you fail to login into admin panel?

**Comment by gsingh93** [comment]
> The only thing I did differently was use a $10 server instead of a $5.

HHVM does use a good amount of RAM, which may be why this helped.

**Comment by NeoVilsonWong** [comment]
@mpomarole  here FYI

<img width="1274" alt="screen shot 2016-05-15 at 2 02 09 am" src="https://cloud.githubusercontent.com/assets/7342012/15269937/1d8dc236-1a41-11e6-8fa1-3f7debb902fe.png">

**Comment by smileboywtu** [comment]
use vagrant as password to login and get access to see the log

**Comment by NeoVilsonWong** [comment]
@smileboywtu same 
<img width="1274" alt="screen shot 2016-05-15 at 2 02 09 am" src="https://cloud.githubusercontent.com/assets/7342012/15270002/68b993f0-1a43-11e6-8790-78302bba4d5a.png">

**Comment by mpomarole** [comment]
@NeoVilsonWong thanks for letting us know. There were a couple more people that had this problem. 

If you follow what @waelsv posted in https://github.com/facebook/fbctf/issues/46#issuecomment-219206374 you will fix that issue.

**Comment by NeoVilsonWong** [comment]
@mpomarole ,follow by the following but still same 

openssl passwd -1 password

mysql --user=root --password=root
use fbctf;
UPDATE teams
 SET password_hash='hash_generated_before'
 WHERE name='admin';

**Comment by NeoVilsonWong** [comment]
@mpomarole , update status ~ Solve done ~ Thanks Alot

**Comment by darkclownstein** [comment]
So what is the password then?
