### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by dodoa123** [facebook/fbctf#397]
## I want to know how to install Facebook CTF

I have
1- windows 7 x64 SP1 installed
2- vagrant installed
3- virtualbox installed

i run these commands
cd Desktop
cd FolderName
vagrant up

then i left it 2 hour downloading required ubuntu 14.04 x64
after that i see ubuntu is running and asking for login i entered username: root ,Password: vagrant
nothing happened

i opened google chrome while ubuntu was running and entered "https://10.10.10.5"
i received error from google chrome saying  "10.10.10.5 refused to connect."

i read official installation
what is solution with steps please :+1:

**Comment by gsingh93** [comment]
> i read official installation

Did you read the part where it said to run `vagrant ssh`?

**Comment by dodoa4** [comment]
I wrote this command in ubuntu but come with this message that vagrant wasn't installed on this system and i can install it with a command ( i don't remember it now ). 
So what's solution 🤔🤔🤔

**Comment by gsingh93** [comment]
Try `sudo apt-get install vagrant` in a terminal.

**Comment by dodoa123** [comment]
I installed vagrant on ubuntu what should  i do after that ?

Do you mean to have vagrant installed on windows and ubuntu ?

Thanks for replying me

**Comment by gsingh93** [comment]
On ubuntu:

```
git clone https://github.com/facebook/fbctf
cd fbctf
vagrant up
```

You can run `vagrant ssh` to ensure the VM is running, but you can just check the IP address to see if the site is up. If you can SSH but you can't connect to the site, paste the contents of /var/log/hhvm/error.log here.

**Comment by dodoa4** [comment]
When I wrote vagrant up on ubuntu it comes with message that i need to install VirtualBox !!!

Note : ubuntu installed on virtualBox on win 7 

Thanks for replying :)

**Comment by gsingh93** [comment]
You'll need to install Virtualbox in Ubuntu. `sudo apt-get install virtualbox` should do it.

**Comment by dodoa123** [comment]
I have 
vagrant 1.8.1 installed
virtualBox 4.1.44 installed

i run "sudo vagrant up" it comes with this error
![screenshot1](https://cloud.githubusercontent.com/assets/24574761/21354470/e5c31588-c6d2-11e6-9369-eba4149ec626.jpg)

i opened virtualbox and i didnt find anything installed 
![screenshot2](https://cloud.githubusercontent.com/assets/24574761/21354602/6e8239c6-c6d3-11e6-9116-8140b72f61b8.jpg)

About System i am running on it
![screenshot2](https://cloud.githubusercontent.com/assets/24574761/21354647/9b8f4de6-c6d3-11e6-9999-77264e6bb5db.jpg)

**Comment by javuto** [comment]
I just tried to run the platform on a Windows 10 host and it worked perfectly out of the box. My steps were:
```
git clone https://github.com/facebook/fbctf.git
cd fbctf
vagrant up
```
And after that I had the platform up and running in ```https://10.10.10.5```. If that did not work for you, can you please submit the full vagrant output after you run ```vagrant up```? That will help us understand what went wrong.
If you want to run the platform in an existing VM, then you can just provision it yourself without installing vagrant or virtualbox inside of the virtual machine. My recommendation is to create a vanilla Ubuntu 14.04 because the ```provision.sh``` makes some changes to your system that you may not want.

**Comment by dodoa123** [comment]
where you write these commands

**Comment by dodoa123** [comment]
i post the output of vagrant up in first image ;(

**Comment by javuto** [comment]
That is the output for vagrant *inside* of a virtual machine already. It will run but very slowly so I would recommend run vagrant, which is basically a tool to control virtual machines, either natively in Windows or provision the platform inside of the Linux VM.
