### ISSUE TITLE
change map / country definitions

### ISSUE THREAD

**Issue by Epivalent** [facebook/fbctf#40]
how deeply embedded into the code is the current map? 
it'd be nice to swap in differently titled and shaped areas for bases/flags/etc.

**Comment by Epivalent** [comment]
I see they're defined here: https://github.com/facebook/fbctf/blob/5d75a0a5b71d724ff71ac301e99ad5ed99a7947b/database/countries.sql

**Comment by javuto** [comment]
Map is drawn using d3. Will you be more interested in modifying the current map with other shapes or have a total different UI?

**Comment by Epivalent** [comment]
It would be nice to be able to customise the UI entirely or plug in modular solution types. We'd like to have interactive levels with different kinds of user interaction for a more educationally-targeted challenge system to teach basic infosec concepts.

**Comment by gsingh93** [comment]
Looks like @javuto made https://github.com/facebook/fbctf/issues/41 to track this, so closing this one.
