### ISSUE TITLE
Some ODD problem on Docker

### ISSUE THREAD

**Issue by nyacat** [facebook/fbctf#403]
I'm using debian jessis with Docker 1.12.1
But,when I following the instruction https://github.com/facebook/fbctf#using-docker,I get an error...

[+] Provisioning in dev mode
[+] Using self certificate
[+] Source code folder /root
[+] Destination folder /var/www/fbctf
[+] Creating code folder /var/www/fbctf
[+] Copying all CTF code to destination folder
[+] Configuring git to ignore permission changes
error: could not lock config file .git/config: No such file or directory
The command '/bin/sh -c apt-get update   && apt-get install -y   rsync   curl   ca-certificates   && chown www-data:www-data $HOME   && ./extra/provision.sh -m $MODE -c $TYPE -k $KEY -C $CRT -D $DOMAIN -e $EMAIL -s `pwd` --docker   && rm -f /var/run/hhvm/sock   && apt-get clean   && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 255

**Comment by iangcarroll** [comment]
Did you use GitHub's Download as ZIP button? You'll need to clone the repository with git itself.

**Comment by nyacat** [comment]
I was using git  clone

**Comment by qazbnm456** [comment]
@nyacat Okay, I found the problem is introduced by https://github.com/facebook/fbctf/pull/287. I've already sent a PR https://github.com/facebook/fbctf/pull/404. Thanks :)

**Comment by nyacat** [comment]
OK...
git fetch origin +refs/pull/404/merge:
Still the same error

**Comment by nyacat** [comment]
ok/.\
I saw the changes.
Thanks Dude
