### ISSUE TITLE
Error 500 when accessing

### ISSUE THREAD

**Issue by cybertronic** [facebook/fbctf#406]
I'm getting an error 500, and this in the logs.
Haven't touched anything. vagrant up, and then browser to site...
Any ideas?
[Thu Jan  5 18:08:01 2017] [hphp] [12907:7f3c437ff700:1:000001] [] \nFatal error: Unexpected character in input: '.' (ASCII=46) (Line: 21, Char: 69)\nsyntax error, unexpected '.', expecting '/' or T_XHP_LABEL or T_XHP_TAG_GT in /var/www/fbctf/src/controllers/Controller.php on line 21

**Comment by javuto** [comment]
Related to https://github.com/facebook/fbctf/pull/405

**Comment by cybertronic** [comment]
Works now, thanks!
