### ISSUE TITLE
Question about modifiying DB directly

### ISSUE THREAD

**Issue by wisco24** [facebook/fbctf#408]
All,  

Is there any risk to making changes to the DB directly, then flushing memcached?   For my CTF event we turn flags on and off at different times, so I scripted the change in the db levels table, then flush memcached so that the gameboard show up correctly/quickly.   Is there any risk in doing this?  Is there a better way to do this?

Also looking at doing this to start/stop/pause the game.    

Thanks!

**Comment by stevcoll** [comment]
That should be fine, as long as you match all the DB calls that take place during the event in question with the GUI. What I usually do is turn on the general query log and run the function desired in the GUI to ensure I have all the DB calls. Then afterwards flush memcached as you said.

At this time I don't believe there is a better solution if you want to automate it.

**Comment by SriHarshaGajavalli** [comment]
If you change DB directly, then there might be a chance of crashing
