### ISSUE TITLE
FBCTF not working on Ubuntu 14.04

### ISSUE THREAD

**Issue by wrinkl3** [facebook/fbctf#409]
Setting up the production version with a self-signed certificate. The index page remains blank, the nginx error.log shows:  
 `"ssl_stapling" ignored, issuer certificate not found`   

The issue has manifested on three separate machines. Any idea why?

**Comment by iangcarroll** [comment]
That's an informative message by nginx; it has no relation to fbctf and won't cause any problems (it's because you're using a self signed certificate). Do you see anything in `/var/log/hhvm/error.log`?

**Comment by wrinkl3** [comment]
`\nFatal error: Unexpected character in input: '.' (ASCII=46) (Line: 21, Char: 69)\nsyntax error, unexpected '.', expecting '/' or T_XHP_LABEL or T_XHP_TAG_GT in /var/www/fbctf/src/controllers/Controller.php on line 21`   

This message is repeated a few times. Sounds like it might have something to do with the `$language` variable.

**Comment by iangcarroll** [comment]
This is fixed in #405; if you apply that patch you should be OK.

**Comment by wrinkl3** [comment]
Applied the patch by changing the line and running the provision script again. Accessing the index page now produces the following error:  

> [Wed Jan 11 12:09:58 2017] [hphp] [2531:7fbb32bff700:1:000001] [] \nFatal error: Uncaught exception 'XHPInvalidChildrenException' with message 'Element `head` was rendered with invalid children.\n\n/var/www/fbctf/src/controllers/Controller.php:42\n\nVerified 7 children before failing.\n\nChildren expected:\n(%metadata*)\n\nChildren received:\n:meta[%metadata,%flow,%phrase],:meta[%metadata,%flow,%phrase],:meta[%metadata,%flow,%phrase],:meta[%metadata,%flow,%phrase],:title[%metadata],:link[%metadata],:link[%metadata],pcdata' in /var/www/fbctf/vendor/facebook/xhp-lib/src/core/ComposableElement.php:588\nStack trace:\n#0 /var/www/fbctf/vendor/facebook/xhp-lib/src/core/Primitive.php(51): xhp_x__composable_element->validateChildren()\n#1 /var/www/fbctf/vendor/facebook/xhp-lib/src/core/Primitive.php(36): xhp_x__primitive->__flushSubtree()\n#2 /var/www/fbctf/vendor/facebook/xhp-lib/src/core/Primitive.php(49): xhp_x__primitive->__flushElementChildren()\n#3 /var/www/fbctf/vendor/facebook/xhp-lib/src/core/Primitive.php(36): xhp_x__primitive->__flushSubtree()\n#4 /var/www/fbctf/vendor/facebook/xhp-lib/src/core/Primitive.php(49): xhp_x__primitive->__flushElementChildren()\n#5 /var/www/fbctf/vendor/facebook/xhp-lib/src/core/Primitive.php(26): xhp_x__primitive->__flushSubtree()\n#6 /var/www/fbctf/vendor/facebook/xhp-lib/src/core/Primitive.php(22): xhp_x__primitive->asyncToString()\n#7 /var/www/fbctf/vendor/facebook/xhp-lib/src/core/XHP.php(57): xhp_x__primitive->toString()\n#8 /var/www/fbctf/src/Router.php(20): xhp_xhp->__toString()\n#9 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#10 /var/www/fbctf/src/index.php(17): genInit()\n#11 {main}

**Comment by javuto** [comment]
Fixed in https://github.com/facebook/fbctf/pull/417
