### ISSUE TITLE
Using fbctf ubuntu mirror, can not cross-segment communication problems.

### ISSUE THREAD

**Issue by IamQiuTian** [facebook/fbctf#410]
Fbctf installed, 10 normal network of communications, network communications can be 11 normal. All the firewalls in the network environment have been emptied.
Fbctf_ubuntu specific parameters in the following:

Dr34m @ ubuntu: / $ sudo uname -a
Linux ubuntu 4.2.0-27-generic # 32 ~ 14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU / Lin

Dr34m @ ubuntu: / $ sudo ufw status
Status: inactive

                                                                                                   Happy New Year, Qiudays.

**Comment by iangcarroll** [comment]
I don't really understand your question, sorry. Are you having trouble connecting to something?

**Comment by gsingh93** [comment]
Yea, I'm not sure what you're asking. I'm closing until you can clarify your question.
