### ISSUE TITLE
Points not updating for team

### ISSUE THREAD

**Issue by talqual** [facebook/fbctf#411]
Hi, 

When I manually update the points in teams table via SQL, the points are not added in any of the views, except in the scoreboard timeline (see image, the score table is zero). 

Please advise in which other table I need to change the points, I've tried the ones I could see in the code but still doesn't work. 

Thanks, Tal

![image](https://cloud.githubusercontent.com/assets/23124448/21804407/844670aa-d737-11e6-8e74-f09193de273d.png)

**Comment by talmanor** [comment]
![image](https://cloud.githubusercontent.com/assets/23124448/21804546/1cc0bafc-d738-11e6-8cf6-cb70f629d18b.png)

**Comment by iangcarroll** [comment]
This is probably because of Memcache; try flushing it by sending it `flush_all`.

On the fbctf machine:
`echo 'flush_all' | nc localhost 11211`

**Comment by talqual** [comment]
Great, that solved it! Thank you Sir!

Cheers, Tal
