### ISSUE TITLE
Inefficent SQL queries causes large games to lock up.

### ISSUE THREAD

**Issue by wisco24** [facebook/fbctf#416]
Ran the CTF system for 48 teams and 60-65 questions.   The first 20 questions worked well, but as the number of questions answers grew the mysql process when out of control and made the gameboard system unusable.   Gave it 16 vcpu and 32 gigs of RAM and the database consumed it all and still couldn't keep up.  I am still working to find the querys causing the most issues, but it appears that  activity section on the gameboard and the leaderboard section are being re-looked up every page refresh instead of being cached some where.  I'm going to try to monitor the DB queries during a test game to see if I can identify which ones are not working well.     Also, after looking through the DB, I feed that the data is not being stored efficiently.   There is no need for most tables to have the full team name.  There should just be the teams table that assigns a team id, and that team id should be stored instead..

**Comment by gsingh93** [comment]
Do you have MySQL binlogs enabled? If so, disable it. Otherwise, I've never anything like this before...

**Comment by wisco24** [comment]
I will have to check. I used the default provision script for prod

**Comment by gsingh93** [comment]
The default provision script doesn't touch this setting, so if you didn't enable it yourself it's probably not on.

We've held CTFs just as big or bigger than the one you've described and haven't seen problems like this (except when we enabled binlogs). If you're fine with it, maybe you could send us the credentials for your server and we could take a look at it ourselves? If you're not comfortable with doing that while the competition is running, we can take a look at it afterwards as well.

**Comment by juliannagler** [comment]
@wisco24 as @gsingh93 said, we're more than happy to check out the logs if you'd like. Just shoot the credentials over to jnagler@fb.com

**Comment by wisco24** [comment]
I think I found the issue with why you all haven't seen it.  This was a 8 hour one. Not multiple days.  All the teams were all working at the same time.

**Comment by wisco24** [comment]
I can't provide access to it as we had to restart the game to clear the DB.  (I did backup the DB prior, but the backup is corrupted for some reason and can't be reimported.     When looking at the queries,  on the gameboard, why is it going though and running a "SUM" query against the scores_log table for each team.   That seems like over kill since in my case, that would be 48 queries running per signed-in user, multiplied by 45 users = 2160 SUM queries per gameboard refresh.  There has to be a  more efficient way then summing it each time, especially when I had 50+ flags it was trying to sum by the end of the day.....

**Comment by wisco24** [comment]
I also had an issue where a team got 60 points for a 30 point question.  I did have to manually restart hhvm a couple times, and figure that might have part of it where it didn't lock the question out fast enough during the service restart.

**Comment by stevcoll** [comment]
In regards to your 60 points for a 30 point question, that sounds like the _Default Bonus_ which you can set in the Admin Configuration. The first team to capture a level will get this bonus for each level (which is by default set to 30 points).

As far as the queries problem, this sounds like an issue with memcached not running. I tested your scenario with 48 teams, and once there is any type of capture event (whether it be a flag, quiz, or base), the _SUM_ query you mentioned will only run once per subsequent capture event, regardless of the number of teams. This is true for most queries once a capture event takes place.

**Comment by wisco24** [comment]
Steve, 

I'll look into the memcached idea.   The default bonus was definitely not used.   First thing I checked myself.....

**Comment by wisco24** [comment]
All,  I just dug in and it looks like binlogs were enabled, and have been for a while.... Now I just need to figure out how they got enabled......

**Comment by gsingh93** [comment]
> it looks like binlogs were enabled

Thanks for sharing. If you find out how they got enabled, let us know.
