### ISSUE TITLE
After testing on several versions of ubuntu and debian, I would like to know, in which S.O. Linux can I install FB CTF in development mode, without docker or vagrant?  Thank you !!!

### ISSUE THREAD

**Issue by kinomakino** [facebook/fbctf#418]
After testing on several versions of ubuntu and debian, I would like to know, in which S.O. Linux can I install FB CTF in development mode, without docker or vagrant?

Thank you !!!

**Comment by javuto** [comment]
Right now only Ubuntu 14.04 is supported.
