### ISSUE TITLE
Documentation for how to set up Base Levels

### ISSUE THREAD

**Issue by dylanjacob** [facebook/fbctf#43]
There is documentation for setting up quizzes and Flag Levels, but none for Base Levels.

**Comment by javuto** [comment]
Just added this documentation in the Wiki section. Let me know if there is something not clear enough.
https://github.com/facebook/fbctf/wiki/FBCTF-Challenge-Overview

**Comment by dylanjacob** [comment]
Using the new wiki section, I was able to get a base up and running.

Thanks for adding that.  I will close the issue now.

**Comment by ryanw42675** [comment]
Not clear enough for me. I think that I've set up the platform correctly. Quiz and Flag work fine. I've set up a Linux VM to use for base target, but don't know what to put on it. What do I do with score_base.py

**Comment by uclanetsec** [comment]
The platform doesn't seem to be fetching the question for us. We've set up the problem exactly as outlined in the documentation linked above and used the given score_base.py with the default port. The problem works and we can manually fetch the request and get the correct output using score_base.py, but the platform isn't updating the points or scoreboard accordingly.
