### ISSUE TITLE
 starting container process caused "exec: \"./extra/service_startup.sh\": permission denied"

### ISSUE THREAD

**Issue by vincentcox-ordina** [facebook/fbctf#431]
I used docker for the installation.

If I run: `docker run -p 80:80 -p 443:443 fbctf_in_dev`, I get the following error:
```
container_linux.go:247: starting container process caused "exec: \"./extra/service_startup.sh\": permission denied"
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"./extra/service_startup.sh\\\": permission denied\"\n".
```
Anybody an idea?

**Comment by joebloggs12** [comment]
I had this problem a couple of days ago too but I managed to fix it.
After you clone the repo but before you build the container, navigate to the directory that you cloned the rep and run:

`sudo chmod +x ./extra/service_startup.sh`

That should fix the problem.

**Comment by qazbnm456** [comment]
It seems `service_startup.sh` has been chmod to ordinary file due to [this commit](https://github.com/facebook/fbctf/commit/089542d57a03620f0f41d5c08067fb6d9f3fec99).

Would send a PR to fix this issue soon.
