### ISSUE TITLE
Unable to access fbctf(10.10.10.5)

### ISSUE THREAD

**Issue by kamikaze123** [facebook/fbctf#435]
After running "vagrant up," I went to 10.10.10.5. However I got blank page(http response is 500 hphp invoke). 

Is latest fbctf working correctly?

**Comment by david-sykora** [comment]
No, it isn't. For me worked reseting to https://github.com/facebook/fbctf/commit/5e3679848c6cbeded68d65e0d37352a33ef603f2

**Comment by javuto** [comment]
There was an issue with `src/controllers/IndexController.php` but it has been fixed now. Just get the latest version and it will work.

**Comment by gsingh93** [comment]
Travis CI should have caught this regression before the PR was merged, but it didn't and that worries me. @justinwray, can you take a look to see how this got through? I think https://travis-ci.org/facebook/fbctf/builds/195824430 is what should have failed. I think we might just be missing a call to `hh_client` in our test script.
