### ISSUE TITLE
Install script not working?

### ISSUE THREAD

**Issue by 0duck0** [facebook/fbctf#44]
I tried the provision.sh script several times but was unsuccessful until I created the path /var/www/ and moved the fbctf folder there.  Then ran the script from that location.  I am running Ubuntu 14 LTS

**Comment by javuto** [comment]
Hi there, can you attach the output of the provision?

**Comment by mpomarole** [comment]
Also please take a look at the other open issues about provision with possible solutions to your problem.

**Comment by gsingh93** [comment]
If you're still having an issue, please reopen.
