### ISSUE TITLE
split services in Dockerfile out into docker-compose.yaml

### ISSUE THREAD

**Issue by Davidsoff** [facebook/fbctf#440]
currently, the Dockerfile runs multiple services. Docker best practices state that it is best to run only a single process per container and string them together using docker-compose (which is shipped with the docker CLI). I, therefore propose splitting up the different services into their own container.

**Comment by anuthamn** [comment]
can i know the steps for splitting up  the services??

**Comment by Davidsoff** [comment]
The extra/service_startup.sh file starts 4 services. Split those services
into separate dockerfiles and create a docker-compose file to start them
and link them together.

Looking through the codebase this also means splitting up the provision.sh
script and possibly even more.

I'd be happy to help out but only have limited time to do so.

**Comment by anuthamn** [comment]
Thank you
