### ISSUE TITLE
Can Anyone tell me wft is going on?

### ISSUE THREAD

**Issue by hashtag29** [facebook/fbctf#45]
when i call vagrant up.... i receive this messages.....

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "e3114779-f57e-440b-a7a4-fbc9f4c4f476", "--type", "headless"]

Stderr: VBoxManage: error: Could not open the medium '/root/VirtualBox VMs/fbctf_default_1463173658455_80619/box-disk1.vmdk'.
VBoxManage: error: VMDK: inconsistency between grain table and backup grain table in '/root/VirtualBox VMs/fbctf_default_1463173658455_80619/box-disk1.vmdk' (VERR_VD_VMDK_INVALID_HEADER).
VBoxManage: error: VD: error VERR_VD_VMDK_INVALID_HEADER opening image file '/root/VirtualBox VMs/fbctf_default_1463173658455_80619/box-disk1.vmdk' (VERR_VD_VMDK_INVALID_HEADER)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MediumWrap, interface IMedium

**Comment by javuto** [comment]
Have you tried to get the VM image again? You can run ```vagrant destroy -f``` and then ```rm -Rf /root/VirtualBox VMs/fbctf_default_1463173658455_80619``` to clear things up, and run ```vagrant up``` right afterwards

**Comment by hashtag29** [comment]
Ill try

**Comment by hashtag29** [comment]
Everything gone Ok.... thank you @javuto  for the instructions!!!

**Comment by javuto** [comment]
Happy to help!

**Comment by danmbugua** [comment]
👍 @javuto
