### ISSUE TITLE
bxslider.js error

### ISSUE THREAD

**Issue by rocnfire** [facebook/fbctf#455]
Please include the following information when filing an issue 
• Current version of FBCTF installed (commit head)
• System and Installation details, such as the Linux distribution used, and installation method you chose.
• Detailed description of the problem. Include steps to reproduce the problem when possible.
• Screenshots to help describe the problem when appropriate.
• Relevant output from any logs examined.
• Any steps you have taken to resolve the issue.

**Comment by iangcarroll** [comment]
What is the error?

**Comment by rocnfire** [comment]
Thank you for responding.

Using the ‘Vagrant Up’ after running the git clone.

The setup runs for about 7-8 minutes but errors out when it is looking for bxslider

“error bxslider module missing” is thrown when trying to launch grunt browserify.

Appears the exception is in fbctf<https://github.com/facebook/fbctf>/src<https://github.com/facebook/fbctf/tree/master/src>/static<https://github.com/facebook/fbctf/tree/master/src/static>/js/ as the installer is looking for ‘bxslider’ jquery module and it is not there?

Thanks in advance.
Ben

**Comment by hankosborne** [comment]
I am running the following command and getting a similar error:

sudo ./extra/provision.sh -m dev -s $PWD

Below is how my command ends before returning to the terminal prompt after several minutes:

Running "browserify:dist" (browserify) task
>> Error: Cannot find module 'bxslider' from '/var/www/fbctf/src/static/js'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.

**Comment by justinwray** [comment]
I can confirm reproduction of the error.  In fact, the project is failing to build due to the same issue (https://travis-ci.org/facebook/fbctf).

Oddly, it does seem the bxslider is being downloaded:

```
npm WARN engine bxslider@4.2.7: wanted: {"node":"~0.10.28"} (current: {"node":"0.10.25","npm":"2.15.11"})

...

bxslider@4.2.7 node_modules/bxslider
```

But then _grunt_ is unable to find it.
