### ISSUE TITLE
Provisioning physical server

### ISSUE THREAD

**Issue by rlb1961** [facebook/fbctf#457]
Please include the following information when filing an issue 
• Current version of FBCTF installed (commit head)
• System and Installation details, such as the Linux distribution used, and installation method you chose.
• Detailed description of the problem. Include steps to reproduce the problem when possible.
• Screenshots to help describe the problem when appropriate.
• Relevant output from any logs examined.
• Any steps you have taken to resolve the issue.

I was able to get the CTF server running on a VM, but I was wanting to provision a physical server instead of a VM.  When I try to do so following the same directions I use for the VM, the process fails and I get an error saying “The installation directory ‘/var/www/fbctf’ is not writable.”  Even if I change the permissions on the folder and run the script again, it resets the permissions on the folder and gives me the same error again.  I have updated all the server software, deleted all of the CTF folders and files and started the project from scratch, but get the same issue.
 
The commands I am running to execute the scripts are:

sudo git clone https://github.com/facebook/fbctf
cd fbctf
sudo ./extra/provision.sh –m prod –s $PWD

OS: Ubuntu 14.04.05 x64
Intel Xeon processor
8 GB RAM
250GB HDD

I have attached the output from the script execution:

[install.txt](https://github.com/facebook/fbctf/files/781177/install.txt)

**Comment by justinwray** [comment]
Are you running the commands from your home directory?  Also you shouldn't need sudo before the provision script, it will prompt you for sudo access as necessary.

Here are the commands you should be running, from your home directory or elsewhere, just not from anywhere within /var/www/

```
sudo apt-get update
sudo apt-get install git
git clone https://github.com/facebook/fbctf
cd fbctf
./extra/provision.sh -m dev -s $PWD
```

Give the above a try again against the latest commit head.

**Comment by rlb1961** [comment]
That worked!  I’m not sure why it didn’t work before – the only difference was I was trying to install prod instead of dev – but as long as it works!

Best regards,

Skip Brewer, CCE, EnCE
Computer Security and Special Projects Manager
Elk Grove Unified School District
916-686-7710 x.68054

[Description: Description: cid:image002.gif@01CA03D0.FBEF8620][Description: Description: cid:image003.jpg@01CA03D0.FBEF8620]
Member, International Society of Forensic Computer Examiners (http://www.isfce.com/)
Member, Information Systems Security Association (http://www.issa.org/)

**Comment by justinwray** [comment]
Glad you were able to get it working!
