### ISSUE TITLE
Login credentials in dev build.

### ISSUE THREAD

**Issue by MatsAnd** [facebook/fbctf#46]
Hi! 
I did just setup a clean server with ubuntu so I could test this as the documentation said.

When I setup the server the console outputs this:
**[http://matsa.no/i/CSFclk](http://matsa.no/i/CSFclk)**
And when I try to login with the credentials admin, password I get the "wrong password" notification.

Does someone know about a fix on this issue?

**Comment by javuto** [comment]
Is the data properly created in the DB? There is a message that seems to be a out of memory error and that may make things to break. Can you show what is being output to ```/var/log/hhvm/error.log```?

**Comment by MatsAnd** [comment]
@javuto [error.log.txt](https://github.com/facebook/fbctf/files/264201/error.log.txt)

**Comment by mpomarole** [comment]
@MatsAnd could you paste here the whole output from the provisioning script as well?

**Comment by gsingh93** [comment]
```
[Fri May 13 18:56:04 2016] [hphp] [920:7efd497ff700:3:000001] [] \nNotice: crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash.
```

That's interesting...

**Comment by waelsv** [comment]
Generate the missing password hash for the admin account:
```
openssl passwd -1 password
```

Then update the fbctf table like so:
```
mysql --user=root --password=root
use fbctf;
UPDATE teams
 SET password_hash='hash_generated_before'
 WHERE name='admin';
```

You should be able to login after that.

**Comment by MatsAnd** [comment]
@waelsv Thank you! That worked.
