### ISSUE TITLE
getBasesResponses should specify 'Content-Type:application/json' in curl options

### ISSUE THREAD

**Issue by jtylers** [facebook/fbctf#466]
The function getBasesResponses() in /src/models/Level.php should specify that it is expecting to receive json data in the curl options.  This gives greater flexibility to the server hosting the base challenge.

Basically, the following line of code needs to be added to line 1136 of /src/models/Level.php:
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));

**Comment by mptap** [comment]
@jtylers: Please could you review? https://github.com/facebook/fbctf/pull/597

**Comment by justinwray** [comment]
@mptap 

Your PR looked great.  You will just need to resubmit to the `dev` branch.

**Comment by mptap** [comment]
@justinwray: Done! https://github.com/facebook/fbctf/pull/610
