### ISSUE TITLE
Team Page Fails to Load

### ISSUE THREAD

**Issue by tmsteen** [facebook/fbctf#467]
Please include the following information when filing an issue 
• Current version of FBCTF installed: be35c6ba17f3b8de4a924d4c9af014ae020f4a53
• Ubuntu 14.04.5 LTS, installed for production by cloning the Git repo and following the instructions.  Imported questions and categories from a previous installation.
• Problem: Logged in as admin, navigate to the Teams page (index.php?p=admin&page=teams) and get a 500 error. Similar issue when trying to load the Game Logs page. 

The categories page also looks weird.  Only one of the imported categories has the "Delete" link. 

 
The only related error I can find is in HHVM Error Log: 
[Thu Feb 23 18:34:54 2017] [hphp] [1296:7f813fbff700:1310:000001] [] \nWarning: 'Autorun Cycle (s)' has no translation in the selected language. Using the English version instead.
[Thu Feb 23 18:34:54 2017] [hphp] [1296:7f813fbff700:1310:000002] [] \nWarning: 'Game Schedule' has no translation in the selected language. Using the English version instead.
[Thu Feb 23 18:34:54 2017] [hphp] [1296:7f813fbff700:1310:000003] [] \nWarning: 'Game Start Year' has no translation in the selected language. Using the English version instead.
[Thu Feb 23 18:34:54 2017] [hphp] [1296:7f813fbff700:1310:000004] [] \nWarning: 'Game End Year' has no translation in the selected language. Using the English version instead.
[Thu Feb 23 18:34:54 2017] [hphp] [1296:7f813fbff700:1310:000005] [] \nWarning: 'Month' has no translation in the selected language. Using the English version instead.
[Thu Feb 23 18:34:54 2017] [hphp] [1296:7f813fbff700:1310:000006] [] \nWarning: 'Month' has no translation in the selected language. Using the English version instead.
[Thu Feb 23 18:34:54 2017] [hphp] [1296:7f813fbff700:1310:000007] [] \nWarning: 'Day' has no translation in the selected language. Using the English version instead.
[Thu Feb 23 18:34:54 2017] [hphp] [1296:7f813fbff700:1310:000008] [] \nWarning: 'Day' has no translation in the selected language. Using the English version instead.
[Thu Feb 23 18:34:54 2017] [hphp] [1296:7f813fbff700:1310:000009] [] \nWarning: 'Minute' has no translation in the selected language. Using the English version instead.
[Thu Feb 23 18:34:54 2017] [hphp] [1296:7f813fbff700:1310:000010] [] \nWarning: 'Minute' has no translation in the selected language. Using the English version instead.
[Thu Feb 23 18:34:58 2017] [hphp] [1296:7f813b3ff700:1284:000001] [] \nFatal error: Uncaught exception 'HH\\InvariantException' with message 'level not found' in /var/www/fbctf/src/models/Level.php:880\nStack trace:\n#0 /var/www/fbctf/src/models/Level.php(880): HH\\invariant_violation()\n#1 /var/www/fbctf/src/controllers/AdminController.php(2869): Level::gen()\n#2 (): AdminController->genGenerateTeamScores()\n#3 /var/www/fbctf/src/controllers/AdminController.php(3234): HH\\Asio\\m()\n#4 /var/www/fbctf/src/controllers/AdminController.php(3854): AdminController->genRenderTeamsContent()\n#5 /var/www/fbctf/src/controllers/AdminController.php(3873): AdminController->genRenderPage()\n#6 /var/www/fbctf/src/controllers/Controller.php(12): AdminController->genRenderBody()\n#7 /var/www/fbctf/src/Router.php(73): Controller->genRender()\n#8 /var/www/fbctf/src/Router.php(20): Router::genRouteNormal()\n#9 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#10 (): genInit()\n#11 (): HH\\WaitHandle->join()\n#12 /var/www/fbctf/src/index.php(17): HH\\Asio\\join()\n#13 {main}

**Comment by stevcoll** [comment]
Just a few questions to clarify:

1. What data existed in your DB before the imports? Any levels, teams, captures, etc?
2. Did you import using the Control buttons "Import Levels" and "Import Categories"?
3. Did you import any Levels?
4. Did you get "Success" messages on any imports performed using the Control import buttons?

**Comment by tmsteen** [comment]
1. I have imported Categories and Levels.  I think I may have imported levels twice. 
2. Used only the buttons
3. Did not import any teams
4. Did get a success but I do not think I did on all of them.  Initially, the imports were not happening, then I updated the Dev instance I was trying to import from and it worked. 

Best case is to re-provision and re-import with updated export probably?

**Comment by stevcoll** [comment]
That's probably the easiest solution for now. I did test both levels and category imports and didn't have any issues with the current version.

**Comment by tmsteen** [comment]
Reset database and reimported and everything is working now. Thanks!

**Comment by juliannagler** [comment]
Closing issue
