### ISSUE TITLE
Permanent Cookie

### ISSUE THREAD

**Issue by bbucklin95** [facebook/fbctf#469]
Hi,
I was working on a capstone where I wanted to create an interface that would bypass the fbctf interface (this capstone is having 5 different cybersecurity games, and having an interface for each one is inefficient). 
I was able to successfully send a message to the fbctf server using PHP and capturing the message sent with Burp, however, I wanted to create a permanent cookie in SystemUtils.php so that I wouldn't have to get a new cookie every so often. How would I go about creating this?

The current version of FBCTF installed is the latest one (not sure about how to find version)

**Comment by gsingh93** [comment]
I'm not completely sure what you're doing, but if I understand correctly your problem is you're not saving the cookie on your initial login request and then sending it back on subsequent requests.
