### ISSUE TITLE
Can't import Levels with newest commit.  

### ISSUE THREAD

**Issue by wisco24** [facebook/fbctf#470]
Please include the following information when filing an issue 
• Current version of FBCTF installed (commit head)
• System and Installation details, such as the Linux distribution used, and installation method you chose.
• Detailed description of the problem. Include steps to reproduce the problem when possible.
• Screenshots to help describe the problem when appropriate.
• Relevant output from any logs examined.
• Any steps you have taken to resolve the issue.

Using newest version.  Got this issue when trying to use the Import Levels control.  

 \nFatal error: Uncaught exception 'HH\\InvariantException' with message 'Index links not found in container' in /var/www/fbctf/src/Utils.php:13\nStack trace:\n#0 /var/www/fbctf/src/Utils.php(13): HH\\invariant_violation()\n#1 /var/www/fbctf/src/models/Level.php(175): must_have_idx()\n#2 /var/www/fbctf/src/models/Control.php(374): Level::importAll()\n#3 /var/www/fbctf/src/controllers/ajax/AdminAjaxController.php(484): Control::importLevels()\n#4 /var/www/fbctf/src/controllers/ajax/AjaxController.php(14): AdminAjaxController->genHandleAction()\n#5 /var/www/fbctf/src/Router.php(58): AjaxController->genHandleRequest()\n#6 /var/www/fbctf/src/Router.php(14): Router::genRouteAjax()\n#7 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#8 (): genInit()\n#9 (): HH\\WaitHandle->join()\n#10 /var/www/fbctf/src/index.php(17): HH\\Asio\\join()\n#11 {main}

**Comment by stevcoll** [comment]
This is due to the new implementation not being backwards compatible. [Here](https://github.com/facebook/fbctf/pull/451#issuecomment-284664477) is a quick fix for now.

**Comment by stevcoll** [comment]
PR #523 should fix this issue.
