### ISSUE TITLE
how can i change the file in src while i had install the fbctf

### ISSUE THREAD

**Issue by dr34-m** [facebook/fbctf#471]
i'm a chinese,i install the fbctf on my computer,but it don't have the chinese language ,so i change the file in var/www/fbctf/src/language/lang_zh-tw.php ,but it couldn't work ,so i want a way to change it ,thanks for people who answer me~

**Comment by Harrybebst** [comment]
Not that path, becauser our operation system is Ubuntu. Mr.stevcoll think it run in redhat? When I input those command,it's error. So the current path is  `/var/cache/hhvm/hhvm.hhbc`

**Comment by stevcoll** [comment]
Definitely stick with Ubuntu 14.04 that is the OS supported.

You are correct, the path has changed and I find that the updated commands above work now. Also added an nginx restart as sometimes that needs to be restarted as well.

**Comment by dr34-m** [comment]
Although not fully understand, but I have been successful in your instructions, Thank you very much!
