### ISSUE TITLE
Unable to access gameboard once imported levels enabled

### ISSUE THREAD

**Issue by HC118** [facebook/fbctf#472]
[be35c6](https://github.com/facebook/fbctf/commit/be35c6ba17f3b8de4a924d4c9af014ae020f4a53)
Ubuntu Server 16.04, cloned repository and running in PROD

Whenever I enable any imported levels, all users are immediately unable to access the gameboard and are stuck in an infinite 'Initializing' screen. Attempting to export these levels returns an HTTP 500 error. However, any levels created within the GUI work fine, and editing then saving the imported levels allows them to work normally.

**Comment by wisco24** [comment]
From the Install Notes:  Note that the only supported system is 64 bit Ubuntu 14.04. Ubuntu 16.04 is not supported at this time,

**Comment by wisco24** [comment]
I also had import issues after the latest merge (#451)

**Comment by stevcoll** [comment]
This is due to the new implementation not being backwards compatible. Here is a quick fix for now: [https://github.com/facebook/fbctf/pull/451#issuecomment-284664477](url)

**Comment by HC118** [comment]
I'm closing this myself since it's a

**Comment by stevcoll** [comment]
PR #523 should fix this issue.
