### ISSUE TITLE
Code edits for custom rules?

### ISSUE THREAD

**Issue by BitSledge** [facebook/fbctf#476]
This is more of a question than an issue. I need to add to and make some edits to the rules page, when I edit the /fbctf/src/language/lang_en.php  the changes are not reflected in the application. Is there another file or different way to do this?

**Comment by wisco24** [comment]
sudo rm /var/cache/hhvm/hhvm.hhbc
sudo hhvm-repo-mode enable "/var/www/fbctf"
sudo chown www-data:www-data /var/cache/hhvm/hhvm.hhbc
sudo service hhvm start
sudo service nginx restart

**Comment by gregtampa** [comment]
doing what wisco24 said resulted in errors cap_set_proc failed: Operation not permitted

inside of hhvm
Restarting HHVM FastCGI Daemon hhvm
[Thu Jun 21 04:29:45 2018] [hphp] [24:7f8c66361380:0:000001] [] Can't open log file: /var/log/hhvm/error.log
[Thu Jun 21 04:29:45 2018] [hphp] [24:7f8c66361380:0:000002] [] Log file not specified under daemon mode.\n\n

should just edit then restart nginx
