### ISSUE TITLE
Docker Volumes

### ISSUE THREAD

**Issue by ItsDaGeek** [facebook/fbctf#477]
I'm trying to create a persistent data volume for when the container needs to be reloaded. I've attempted creating a Volume at `/var/lib/mysql`, but it just caused a crash loop for MySQL. (I got that directory from AlexGaspar/docker-fbctf, but is on a much older release)

**Comment by frite** [comment]
Although I don't propose Docker for production cause I had issues with certificates,
`docker run --name fbctf -v /var/lib/mysql -d -p 80:80 -p 443:443 fbctf`
Assuming at some point you want to backup and continue.
`docker run --rm --volumes-from fbctf -v $(pwd):/backup ubuntu tar cvfz /backup/backup.tar /var/lib/mysql
docker rm fbctf
mkdir backup
tar -xvf backup.tar -C backup
echo "Well, brace yourselves."
docker run -d --name fbctf -v $(pwd)/backup/var/lib/mysql:/var/lib/mysql -p 80:80 -p 443:443 fbctf`
