### ISSUE TITLE
The Problem of Map

### ISSUE THREAD

**Issue by rtcatc** [facebook/fbctf#479]
Taiwan is a city of China，not a country.
But the map show that Taiwan is a country.

**Comment by rtcatc** [comment]
![Taiwan](http://i1.piimg.com/567571/de1ad063b998a7e9.png)

**Comment by rtcatc** [comment]
http://i1.piimg.com/567571/de1ad063b998a7e9.png

**Comment by gsingh93** [comment]
This is a complicated issue that has no clear right or wrong side, so we will err on the side of leaving Taiwan as a country.
