### ISSUE TITLE
500 Errors after a few days

### ISSUE THREAD

**Issue by BitSledge** [facebook/fbctf#481]
We are getting 500 errors after running for 1 week with 100 participants. A reboot was fixing it at first, however now that isnt working anymore.

Any suggestions?

**Comment by iangcarroll** [comment]
Do you see anything relevant in /var/log/hhvm/error.log?

**Comment by BitSledge** [comment]
That log file is essentially only comprised of these errors:

"“[hphp] [1222:7f34923ff700:14425:000001] [] \nFatal error: Uncaught exception ‘IndexRedirectException’ with message ‘’ in /var/www/fbctf/src/SessionUtils.php:113\nStack trace:\n#0 /var/www/fbctf/src/data/teams.php(7): SessionUtils::enforceLogin()\n#1 {main}" 

Nothing that seems relevant. 
I wonder if there is a cache somewhere that is only allowed to get to a certain size?
