### ISSUE TITLE
Import/Export issues

### ISSUE THREAD

**Issue by BitSledge** [facebook/fbctf#483]
Currently running an event with 115 players, 30 teams, 50 flags and 35 quiz questions. The hardware and resources being used is completely overkill.

Do to an unknown issue (issue currently opened for that) I want to export this game to a new server running the latest fbctf code to see if the issue was fixed. 
1. Import full game isnt working
2. Import Levels isnt working
3. After Importing Categories, some levels get imported but its inconsistent. I need 50 flags to be imported and have tried a few times. Sometimes it imports 3, other times it imported 1. 
4. Backing up the game database and then restoring on new server gave the same results. (1 flag, 1 quiz question,)

**Comment by iangcarroll** [comment]
Check #470, it might be your issue. There is a patch in one of the comments, if the error is the same: https://github.com/facebook/fbctf/issues/470#issuecomment-284666259.

**Comment by BitSledge** [comment]
Thanks! I see the patch but am not seeing how to implement it.

**Comment by stevcoll** [comment]
See section 2 on [this site](http://www.thegeekstuff.com/2014/12/patch-command-examples/). It's a standard patch file.

**Comment by stevcoll** [comment]
PR #523 should fix this issue.
