### ISSUE TITLE
Hint is not getting displayed

### ISSUE THREAD

**Issue by nikhilgeo** [facebook/fbctf#484]
• fbctf  version: "0.0.1",
• OS is Ubuntu 14.04.4 LTS

Added questions with hints. but after the game is launched hints are not seen anywhere.
We configured free hints

Can anyone point out what could be the issue here..?

**Comment by stevcoll** [comment]
Apologies for the long delay. I know it's been a while, but do you have any updates on this?

**Comment by nikhilgeo** [comment]
The issue still exist, I have a deployment running on code synced from Aug 30. The "Flag levels" are manually fed. Instead of the hints, it shows "Need more points". And to my surprise I have a test instance which runs on the same code base but the  "Flag levels" are imported from the first said instance and "Requests Hints" are shown.

Any idea why "Request Hints" are not shown and "Need more points" are shown instead ?

**Comment by nikhilgeo** [comment]
Sorry false positive. The user didn't have enough points to view the hints.

Keep in mind that when Hint Penalties are set to a non-zero value, teams will need to capture at least one level in order to generate the points to buy the hint. (https://github.com/facebook/fbctf/wiki/Admin-Guide  Levels:Quiz)
