### ISSUE TITLE
Team deletion during gameplay

### ISSUE THREAD

**Issue by BitSledge** [facebook/fbctf#486]
Two questions:

Can a team be deleted during game play without repercussions?

Im getting 500  errors when trying to access the team management page, can one be removed via terminal?

**Comment by stevcoll** [comment]
Yes teams can be deleted during gameplay, that was addressed in #372 

To fix the 500 error, you'll need to remove any entries relating to deleted levels or teams. This depends on the version you're running, but the following tables should be checked. Afterwards, you'll need to clear memcached as well. Check the following tables for references to deleted teams/levels:

failures_log
hints_log
scores_log
levels

Clear memcached from the command line:

`echo 'flush_all' | nc localhost 11211`
