### ISSUE TITLE
Bases example

### ISSUE THREAD

**Issue by sergiownd** [facebook/fbctf#488]
I've already seen the Base that is on the code.
But this base all that it does is just search in a file ('TMP/Score_points') and use this name to update points.
Has someone create a more specefic Base to make users really fight for a server?
Thanks.

**Comment by javuto** [comment]
The idea behind writing to a file (in this case `/tmp/SCORE_POINTS`) is that the machine holding that file is already under control of the team that can write to it. Now is up to the organizers to make that system vulnerable. The platform just provides a scoring mechanism for those scenarios.
