### ISSUE TITLE
Live sync API - Error

### ISSUE THREAD

**Issue by punkdis** [facebook/fbctf#489]
Please include the following information when filing an issue 
• Current version of FBCTF installed (commit head)
• System and Installation details, such as the Linux distribution used, and installation method you chose.
• Detailed description of the problem. Include steps to reproduce the problem when possible.
• Screenshots to help describe the problem when appropriate.
• Relevant output from any logs examined.
• Any steps you have taken to resolve the issue.

Commit head
d3265647b95eaedcdb7b6f87253f7ad6aedf313c

Linux Ver
Ubuntu 14.04.5 LTS 

I am trying to invoke the live sync API

hhvm -vRepo.Central.Path=/var/run/hhvm/.hhvm.hhbc_liveimport /var/www/fbctf/src/scripts/liveimport.php --url "https:// /data/livesync.php" --sleep 30

I get the error

Warning: Unable to execute ''/usr/bin/hh_client' --timeout 5 --retries 0 --json                                             '/var/www/fbctf/src/scripts' 2>&1'

Warning: Invalid operand type was used: implode() expects a container as one of                                             the arguments

**Comment by punkdis** [comment]
rebooted the server and now I get this error

[Wed Apr 5 3:12:53 2017] [https:// /data/livesync.php] !!! Download Error: SSL certificate problem: unable to get local issuer certificate
[Wed Apr 5 3:12:53 2017] [https:// /data/livesync.php] !!! JSON Missing or Invalid: No error

**Comment by punkdis** [comment]
I was thinking maybe the permission for the file is wrong but it is the following stat -c %a livesync.php
664

**Comment by justinwray** [comment]
Did you provide a fully valid URL within the --url argument? The usage pasted above doesn't show the domain/IP, but I realize you may have censored that purposely.

If you are using a full URL and are receiving an SSL error, the error is usually due to a self-signed or otherwise invalid certificate on the server from which you are importing. You can disable the SSL certificate verification with the --disable-ssl-verification argument.

**Comment by punkdis** [comment]
yes I censored it but there should be no reason. I have two web apps

Main site: https://ctf.securityadvisoralliance.org
another site: https://ctf-west.securityadvisoralliance.org

I am running this command from CLI on the main site

hhvm -vRepo.Central.Path=/var/run/hhvm/.hhvm.hhbc_liveimport /var/www/fbctf/src/scripts/liveimport.php --disable-ssl-verification --url "https://ctf-west.securityadvisoralliance.org/data/livesync.php" --sleep 30

The bring problem maybe is this error

 [Wed Apr 5 3:12:53 2017] [https://ctf-west.securityadvisoralliance.org /data/livesync.php] !!! JSON Missing or Invalid: No error

It seems this is causing none of the syncing to work. Also I am not getting any of these options as described in the user documentation to create accounts to link them together.

USER GUIDE (Documentation):

  * Users must first have an account on all FBCTF instances they wish to link.

  * The user must then login and access the game board.

  * From the navigation menu, the user should select "Account."

  * The user must then set a Live Sync username and password.  The Live Sync username and password must not be their login credentials.  In fact, users are prohibited from using their account password as their Live Sync password.

  * The user would repeat the above steps for each FBCTF instance they wish to link.  The Live Sync credentials must be the same on each FBCTF instance or their accounts will not be linked.

**Comment by justinwray** [comment]
Do you have levels setup on the other server already?

Are you able to manually navigate to the livesync URL in your browser on the other server? Can you provide us the output shown in the browser?

**Comment by punkdis** [comment]
Yes all of the levels are setup

https://ctf-west.securityadvisoralliance.org/data/livesync.php

![image](https://cloud.githubusercontent.com/assets/19276988/24782592/cae2ff4c-1b0c-11e7-8789-b319ae895530.png)

**Comment by justinwray** [comment]
It looks like you are getting an HTTP 500 error on the ctf-west system, can you please check your logs (the log file should be here: /var/log/hhvm/error.log) and provide any of the errors you are seeing.

**Comment by punkdis** [comment]
[Fri Apr  7 04:10:08 2017] [hphp] [32522:7feb603ff700:1807:000001] [] \nFatal error: Uncaught exception 'IndexRedirectException' with message '' in /var/www/fbctf/src/SessionUtils.php:113\nStack trace:\n#0 /var/www/fbctf/src/data/teams.php(7): SessionUtils::enforceLogin()\n#1 {main}
[Fri Apr  7 04:10:08 2017] [hphp] [32522:7feb60bff700:1845:000001] [] \nFatal error: Uncaught exception 'IndexRedirectException' with message '' in /var/www/fbctf/src/SessionUtils.php:113\nStack trace:\n#0 /var/www/fbctf/src/data/country-data.php(7): SessionUtils::enforceLogin()\n#1 {main}
[Fri Apr  7 04:10:08 2017] [hphp] [32522:7feb603ff700:1808:000001] [] \nFatal error: Uncaught exception 'IndexRedirectException' with message '' in /var/www/fbctf/src/SessionUtils.php:113\nStack trace:\n#0 /var/www/fbctf/src/data/map-data.php(7): SessionUtils::enforceLogin()\n#1 {main}
[Fri Apr  7 04:10:13 2017] [hphp] [32522:7feb603ff700:1809:000001] [] \nFatal error: Uncaught exception 'IndexRedirectException' with message '' in /var/www/fbctf/src/SessionUtils.php:113\nStack trace:\n#0 /var/www/fbctf/src/data/command-line.php(7): SessionUtils::enforceLogin()\n#1 {main}
[Fri Apr  7 04:10:13 2017] [hphp] [32522:7feb60bff700:1847:000001] [] \nFatal error: Uncaught exception 'IndexRedirectException' with message '' in /var/www/fbctf/src/SessionUtils.php:113\nStack trace:\n#0 /var/www/fbctf/src/data/configuration.php(7): SessionUtils::enforceLogin()\n#1 {main}
[Fri Apr  7 04:10:13 2017] [hphp] [32522:7feb603ff700:1810:000001] [] \nFatal error: Uncaught exception 'IndexRedirectException' with message '' in /var/www/fbctf/src/SessionUtils.php:113\nStack trace:\n#0 /var/www/fbctf/src/data/map-data.php(7): SessionUtils::enforceLogin()\n#1 {main}
[Fri Apr  7 04:10:13 2017] [hphp] [32522:7feb60bff700:1848:000001] [] \nFatal error: Uncaught exception 'IndexRedirectException' with message '' in /var/www/fbctf/src/SessionUtils.php:113\nStack trace:\n#0 /var/www/fbctf/src/data/teams.php(7): SessionUtils::enforceLogin()\n#1 {main}
[Fri Apr  7 04:10:13 2017] [hphp] [32522:7feb603ff700:1811:000001] [] \nFatal error: Uncaught exception 'IndexRedirectException' with message '' in /var/www/fbctf/src/SessionUtils.php:113\nStack trace:\n#0 /var/www/fbctf/src/data/country-data.php(7): SessionUtils::enforceLogin()\n#1 {main}

**Comment by punkdis** [comment]
[Fri Apr  7 04:13:31 2017] [hphp] [32522:7feb603ff700:1896:000001] [] \nFatal error: Call to undefined method Team::genLiveSyncExists() in /var/www/fbctf/src/data/livesync.php on line 14

**Comment by punkdis** [comment]
here are the first few lines of livesync.php that I have on the server

<?hh // strict

require_once ($_SERVER['DOCUMENT_ROOT'].'/../vendor/autoload.php');

class LiveSyncDataController extends DataController {

  public async function genGenerateData(): Awaitable<void> {
    $data = array();

    $teams_array = array();
    $all_teams = await Team::genAllTeams();
    foreach ($all_teams as $team) {
      $team_livesync_exists =
        await Team::genLiveSyncExists($team->getId(), "fbctf");
      if ($team_livesync_exists === true) {
        $team_livesync_key =
          await Team::genGetLiveSyncKey($team->getId(), "fbctf");
        $teams_array[$team->getId()] = strval($team_livesync_key);
      }
    }

    $scores_array = array();
    $scored_teams = array();

**Comment by stevcoll** [comment]
Does your /var/www/fbctf/src/models/Team.php file contain the genLiveSyncExists method? Something weird is going on, that method definitely exists in the latest commit here.

Was your platform upgraded or installed from scratch on the latest commit?

**Comment by punkdis** [comment]
This was a platform upgrade and I did review the Team.php file and the genLiveSynExists method is not there.

**Comment by justinwray** [comment]
@punkdis 

I would suggest updating via `git` and then re-running the provision script.  You can use the upgrade option, but if you are still having issues you may want to do a full provision run.

**Comment by punkdis** [comment]
I rebuilt the servers and it fixed everything
