### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [facebook/fbctf#49]
Hi there, 

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. **CTF** was in my list. However, I observed that the software history of when the software was developed as a proprietary software was not kept after the transition to Github.

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask **CTF** developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the _core developers_ faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the _newcomers_ faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by mpomarole** [comment]
@gustavopinto regarding question 1, we have kept the history. If you look at commit history you will see the whole history of development of this project.

**Comment by gustavopinto** [comment]
Hi @mpomarole, 

Thanks for your super fast reply.

While browsing the commits history, this is the first page that Github shows to me:

https://github.com/facebook/fbctf/commits/master?page=11

The second commit from bottom to top seems to import the existing code all at once (52k additions in one commit):

https://github.com/facebook/fbctf/commit/df024decdcdee03e933a4138095f0b9ab17736bf

Was this code maintained elsewhere and was pushed in a single commit to Github, or was it wrote without any control version system?

Thanks again,

Gustavo

**Comment by gsingh93** [comment]
I think @javuto might have made a mistake during the import.

This code was maintained in a separate Git repo, and then moved to this Git repo. The histories should be the exact same, but I think something went wrong with how @javuto moved it. It doesn't look like there was any loss in history, as the rest of the commits seem fine.

**Comment by gustavopinto** [comment]
Dear @javuto, do you mind in clarifying this issue.

Thank you all,

Gustavo

**Comment by gsingh93** [comment]
I clarified with @javuto offline, there was no mistake importing the code to the new repository. He simply did not use Git before that point.

**Comment by gustavopinto** [comment]
Hi @gsingh93 and @mpomarole, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
