### ISSUE TITLE
Admin ability to modify team points

### ISSUE THREAD

**Issue by jtylers** [facebook/fbctf#490]
There are many reasons why adjustments may need to be made to a team's score. Administrators should have the ability to modify team points.

**Comment by websecctf** [comment]
Admin of the CTF based on what I know do have access to edit overall points of the team.

**Comment by frite** [comment]
You can modify team's points. Login as admin -> teams -> score and you edit. I had to use it to subtract points from a team a couple of weeks ago. Hope that helps :)
