### ISSUE TITLE
TYPO in Admin Guide

### ISSUE THREAD

**Issue by PhilippBehmer** [facebook/fbctf#491]
Paragraph: Timer

completed -> completely

"The Timer is enabled automatically during the start of an event, and shows a game timer on team displays, based on the values utilized below. Note that the game timer is currently display only, and games must be started, paused, and ended manually by admins. The Timer can be disabled **completed** for events which have no time limit."

**Comment by juliannagler** [comment]
Nice catch @PhilippBehmer! Fixed!
