### ISSUE TITLE
Improvement for Live Sync API

### ISSUE THREAD

**Issue by nobu0000** [facebook/fbctf#493]
When user visits https://ip-address/data/livesync.php, user can see all levels while admin user set login off. The problem is... if user can enumerate all levels before beginning the game, user can take advantage. If admin user does not want to open the gameboard(i.e. login off), livesync.php should not be accessed by non-admin user.

When user visits livesync.php, inactive level's title and description are visible to user. Admin user can not hide levels witch admin user wants to activate later. Game participant can solve questions before admin user activate levels. Inactive level's title and description should not be visible to game participant.

How to solve these issue?

**Comment by justinwray** [comment]
With PR #494 Live Sync API is disabled by default and requires the admin to enable it. Additionally, an admin can set an authentication key that is required in the Live Sync API request.

This change should prevent users from viewing the Live Sync data until/unless an admin desires to make it public/visible.

**Comment by nobu0000** [comment]
thanks @justinwray
