### ISSUE TITLE
LiveSync API not syncing

### ISSUE THREAD

**Issue by punkdis** [facebook/fbctf#495]
I would like to live sync west and sw to the main CTF. The scores are not syncing between each other. 

Also I would like to create accounts with their respected livesync credentials before a game is started. In some events the age group is younger and I would like to be able to give them username and passwords prior to the game. Then display the main site on a screen to keep score.

Commit:
d3265647b95eaedcdb7b6f87253f7ad6aedf313c
 

I have 3 servers 
https://ctf.securityadvisoralliance.org (Main)
https://ctf-west.securityadvisoralliance.org
https://ctf-sw.securityadvisoralliance.org

I ran the following command to pull 2 servers (west and sw) to the main server (ctf)
`hhvm -vRepo.Central.Path=/var/run/hhvm/.hhvm.hhbc_liveimport /var/www/fbctf/src/scripts/liveimport.php --url "https://ctf-west.securityadvisoralliance.org/data/livesync.php" --url "https://ctf-sw.securityadvisoralliance.org/data/livesync.php" --sleep 30`

Error:

[Sun Apr 16 2:04:31 2017] [https://ctf-west.securityadvisoralliance.org/data/livesync.php] !!! Download Error: SSL certificate problem: unable to get local issuer certificate
[Sun Apr 16 2:04:31 2017] [https://ctf-west.securityadvisoralliance.org/data/livesync.php] !!! JSON Missing or Invalid: No error
[Sun Apr 16 2:04:31 2017] [https://ctf-sw.securityadvisoralliance.org/data/livesync.php] !!! Download Error: SSL certificate problem: unable to get local issuer certificate
[Sun Apr 16 2:04:31 2017] [https://ctf-sw.securityadvisoralliance.org/data/livesync.php] !!! JSON Missing or Invalid: No error

**Comment by justinwray** [comment]
The error message seems to be due to invalid (or non-trusted) SSL certificates. Add the switch to disable the certificate verification. ```--disable-ssl-verification```

**Comment by punkdis** [comment]
ah ok I got it I switched to use the fullchain.pem instead of the cert.pem.
