### ISSUE TITLE
Upgrade HHVM to version 3.18

### ISSUE THREAD

**Issue by gsingh93** [facebook/fbctf#496]
We previously downgraded from HHVM 3.15 to HHVM 3.14.5 because of crashes. It's been a while, so let's check 3.18 (the last LTS version to support 14.04) to see if it works properly. If we supported Ubuntu 16.04 we could try version 3.21 instead, but we don't because TravisCI doesn't support it.

**Comment by ThetaGamma** [comment]
I accidentially did a "apt-get ugrade" on the CTF-machine and got hhvm 3.18.2 - and until now it seems to work...

**Comment by fredemmott** [comment]
FYI, we're currently expecting 3.21 on the 1st of August; 3.18 will still be supported for ~ 6 months, but 3.15 will become unsupported when 3.21 is released.
