### ISSUE TITLE
Begin Game Button not working

### ISSUE THREAD

**Issue by punkdis** [facebook/fbctf#497]
Committ
d3265647b95eaedcdb7b6f87253f7ad6aedf313c

O/S
Ubuntu Trusty 14.04

Problem:
After several games utilizing livesync the "Begin Game" button does not work. I have rebooted the servers several times with no luck. I have stopped the livesync script.

**Comment by punkdis** [comment]
I can't end the game either. However I did find a work around and I think it is related to the scheduler. I select begin game with the following configuration without any luck 

![image](https://cloud.githubusercontent.com/assets/19276988/25368097/ee216962-293f-11e7-93f8-9363dab29274.png)


If I put in a future date for start and finish such as this and click on begin game, it starts

![image](https://cloud.githubusercontent.com/assets/19276988/25368157/221a6df4-2940-11e7-9281-8527c4a757a9.png)

To end the game I have to pause it first then click on End game

![image](https://cloud.githubusercontent.com/assets/19276988/25368185/51514da4-2940-11e7-98cf-aa7b71e9fbba.png)

**Comment by punkdis** [comment]
To add the begin game is looking for some future times instead of zeros in the game schedule

**Comment by stevcoll** [comment]
Can you provide the output from the HHVM error log when you are attempting to start or stop the game? Are the buttons just not doing anything?
