### ISSUE TITLE
problem modifying frontpage

### ISSUE THREAD

**Issue by htsdeshi** [facebook/fbctf#498]
using the latest version of fbctf i got last night installed fine runs fine but when i go to modify text on the front page direct in code the changes are not showing up. edited IndexController.php to no avail.

**Comment by stevcoll** [comment]
Run these commands to rebuild the cache after your code changes:

```
sudo rm /var/cache/hhvm/hhvm.hhbc
sudo hhvm-repo-mode enable "/var/www/fbctf"
sudo chown www-data:www-data /var/cache/hhvm/hhvm.hhbc
sudo service hhvm start
sudo service nginx restart
```

**Comment by htsdeshi** [comment]
thanks that works is there a way to modify the nagivation menu entry names?

**Comment by stevcoll** [comment]
Are you talking about the admin menu on the left side, such as "Announcements"?

To change those you want to edit src/controllers/AdminController.php under genRenderMainNav.

Example: Line 3808 - {tr('Announcements')}
