### ISSUE TITLE
docker dev environment failing to build

### ISSUE THREAD

**Issue by m0jtaba** [facebook/fbctf#499]
Cloned master

command: docker build --build-arg MODE=dev -t="fbctf_in_dev" .

Only change I have made is in: /fbctf/extra/provision.sh: which is: **set -e -x**

anyone have any ideas?

Output:

`+ sudo npm install -g flow-bin
/usr/bin/flow -> /usr/lib/node_modules/flow-bin/cli.js
flow-bin@0.46.0 /usr/lib/node_modules/flow-bin
+ run_grunt /var/www/fbctf dev
+ local __path=/var/www/fbctf
+ local __mode=dev
+ cd /var/www/fbctf
+ grunt
Running "force:eslint" (force) task

Running "force-internal:pre:eslint" (force-internal) task
>> Enable force mode for task eslint.

Running "eslint:dist" (eslint) task

/var/www/fbctf/node_modules/eslint-plugin-flowtype/dist/rules/defineFlowType.js:37
    ClassImplements(node) {
                   ^
Warning: Failed to load plugin flowtype: Unexpected token ( Used --force, continuing.
Warning: Task "eslint:dist" failed. Used --force, continuing.

Running "force-internal:post:eslint" (force-internal) task
>> Reset force mode for task eslint.

Running "run:flow" (run) task
flow is still initializing; this can take some time. [processing] -Launching Flow server for /var/www/fbctf/src
Spawned flow server (pid=9037)
Logs will go to /tmp/flow/zSvarzSwwwzSfbctfzSsrc.log
Started a new flow server: \flow is still initializing; this can take some time. [merging inference] |src/static/js/admin.js:5
  5: var Dropkick = require('dropkickjs');
                            ^^^^^^^^^^^^ dropkickjs. Required module not found

src/static/js/admin.js:6
  6: var $ = require('jquery');
                     ^^^^^^^^ jquery. Required module not found

src/static/js/clock.js:3
  3: var $ = require('jquery');
                     ^^^^^^^^ jquery. Required module not found

src/static/js/fb-ctf.js:12
 12: var d3 = require('d3');
                      ^^^^ d3. Required module not found

src/static/js/fb-ctf.js:13
 13: var $ = require('jquery');
                     ^^^^^^^^ jquery. Required module not found

src/static/js/fb-ctf.js:14
 14: var Keycode = require('keycode');
                           ^^^^^^^^^ keycode. Required module not found

src/static/js/filter.js:3
  3: var $ = require('jquery');
                     ^^^^^^^^ jquery. Required module not found

Found 7 errors
Warning: non-zero exit code 2 Use --force to continue.

Aborted due to warnings.
The command '/bin/sh -c apt-get update   && apt-get install -y   rsync   curl   ca-certificates   && chown www-data:www-data $HOME   && ./extra/provision.sh -m $MODE -c $TYPE -k $KEY -C $CRT -D $DOMAIN -e $EMAIL -s `pwd` --docker   && rm -f /var/run/hhvm/sock   && apt-get clean   && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 3
`

**Comment by jeszicawii** [comment]
I am also having this issue. 
I have created a standard ubuntu container, made a fresh clone of this repo and tried using the provisioning script.

**Comment by stevcoll** [comment]
We're looking into the issue now. Will provide an update soon.

**Comment by me-dusa** [comment]
Having the same exact issue.

I've tried both the Docker installation as well as the provisioning script. I even downloaded the modules and specifically moved them to the /usr/lib/node_modules directory, but it seems as if they're not being read properly.

How would I do the `grunt --force` to make this properly work?

**Comment by stevcoll** [comment]
At this point it seems using --force is the only solution. You'll need to edit the lib.sh file as shown here:

https://github.com/facebook/fbctf/pull/502/commits/3e557d1f2ba420e42bc73725e01c6b9985b9daa2

@me-dusa make the above file change after cloning FBCTF and browsing to the fbctf directory (before running docker build). Let us know how that works out.

**Comment by me-dusa** [comment]
I made the fix you mentioned and everything went smoothly on an Ubuntu 14.04 x64 VM - thanks! @stevcoll

**Comment by wisco24** [comment]
This fix has been  merged, so this issue can be closed.
