### ISSUE TITLE
Adding new items (levels, teams) in batch

### ISSUE THREAD

**Issue by javuto** [facebook/fbctf#5]
Would be nice to have a way to import levels, teams and any other component with a JSON file. Also export existing ones to a JSON file instead of having to deal with MySQL dumps.

**Comment by dylanjacob** [comment]
👍 that would be especially useful for a massive amount of quiz levels

**Comment by javuto** [comment]
https://github.com/facebook/fbctf/pull/150 for reference

**Comment by javuto** [comment]
Implemented in https://github.com/facebook/fbctf/pull/208
