### ISSUE TITLE
[fedora]anyway run this on fedora?

### ISSUE THREAD

**Issue by smileboywtu** [facebook/fbctf#50]

**Comment by mpomarole** [comment]
I haven't tried it, so no promises it will work, but fedora can run vagrant. So after you clone the repo, run `vagrant up` and it will create a Ubuntu VM to run the site. Then you can access it on port 10.10.10.5.

**Comment by smileboywtu** [comment]
provider error:

==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/trusty64'
    default: URL: https://atlas.hashicorp.com/ubuntu/trusty64
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: ubuntu/trusty64
Address: https://atlas.hashicorp.com/ubuntu/trusty64
Requested provider: [:libvirt]

**Comment by gsingh93** [comment]
Are you using our Vagrantfile? Our file uses VirtualBox as the provider. Can you try it with that?

**Comment by smileboywtu** [comment]
cd /fbctf
vagrant up

now I just try other provider, I'm not very familiar with vagrant.

**Comment by smileboywtu** [comment]
``` shell

➜  fbctf git:(master) vagrant -v
Vagrant 1.8.1

```

virtualbox 5.0.20

**Comment by smileboywtu** [comment]
will this the reason for showing this error:

Bringing machine 'default' up with 'libvirt' provider...

**Comment by smileboywtu** [comment]
the answer is yes for newly installed vagrant, just add the line:

``` ruby

VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "10.10.10.5"
  config.vm.hostname = "facebookCTF-Dev"
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.provision "shell", path: "extra/provision.sh", privileged: false
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end
end

```
make sure to set the provider for vagrant first.
