### ISSUE TITLE
No auto generated username and password on install

### ISSUE THREAD

**Issue by grook14** [facebook/fbctf#501]
Using Ubuntu 16.04 I get to the last step in the development commands for installation and it gives me this error message, nor does it generate a password and username. 

Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for facebook/xhp-lib v2.3.2 -> satisfiable by facebook/xhp-lib[v2.3.2].
    - facebook/xhp-lib v2.3.2 requires hhvm ~3.12 -> you are running this with PHP and not HHVM.
  Problem 2
    - Installation request for fredemmott/type-assert v1.1 -> satisfiable by fredemmott/type-assert[v1.1].
    - fredemmott/type-assert v1.1 requires hhvm ~3.12 -> you are running this with PHP and not HHVM.

Any help woud be much appreciated!

**Comment by stevcoll** [comment]
We're looking into the issue now. Will provide an update soon.

**Comment by wisco24** [comment]
Have you tried it on Ubuntu 14.04?   Per the install guide, that is the only OS that is fully supported.

**Comment by grook14** [comment]
I have not! Can you still get that ISO from Ubuntu.com <http://ubuntu.com/>?

**Comment by stevcoll** [comment]
Yes you should only install it on 14.04 currently. However, there is a current issue with the install that we're looking into. A quick workaround is here:

https://github.com/facebook/fbctf/pull/502

**Comment by grook14** [comment]
Ok, excellent. I will try 14.04! Thank you for responding so quickly!

**Comment by stevcoll** [comment]
Let us know if 14.04 worked out for you @grook14.

**Comment by grook14** [comment]
So I was able to get further with it, but it still aborted. I am not using Ubuntu 14.04

I attached screen shots.

**Comment by stevcoll** [comment]
@grook14 don't see any attachments?

**Comment by grook14** [comment]
Odd. Let me know if it worked this time.

**Comment by wisco24** [comment]
@grook14   you need to upload images via the webui.  All attachments are striped from e-mails.
