### ISSUE TITLE
Change Scoreboard

### ISSUE THREAD

**Issue by der-Daniel** [facebook/fbctf#504]
Hi,

I wanna modify the scoreboard view visible by clicking 'scoreboard' in the main navigation on the landing page.
Changing the file `/var/www/fbctf/src/controllers/modals/ScoreboardModalController.php` did not show any changes.
Is there something cached or rebuild, when HHVM is restarted?
How do I make changes?

For Frodo,
Daniel

**Comment by khtq** [comment]
Run provision.sh with `-R` to disable [repo authoritative](https://docs.hhvm.com/hhvm/advanced-usage/repo-authoritative)
Maybe `sudo hhvm-repo-mode disable` work.

**Comment by der-Daniel** [comment]
at install time or can I run it right now?

**Comment by khtq** [comment]
@der-Daniel  
You should try with `sudo hhvm-repo-mode disable` first, if it doesn't work, stop your `nginx` and re-install fbctf, pay attention to #499 and #500

**Comment by justinwray** [comment]
You could disable repo mode; however, this is not recommended on a production installation.

While repo mod: Run these commands to rebuild the cache after your code changes:

```sudo rm /var/cache/hhvm/hhvm.hhbc
sudo hhvm-repo-mode enable "/var/www/fbctf"
sudo chown www-data:www-data /var/cache/hhvm/hhvm.hhbc
sudo service hhvm start
sudo service nginx restart```

**Comment by der-Daniel** [comment]
sorry for asking again :(

I did not get the picture.
I have cloned repo folder called 'fbctf'. From this folder I am initially building the CTF. Then there is the `/var/www/fbctf` folder.

Where do I change the file? And when do I run the commands?
It is just not obvious to me.

For Frodo
Daniel

**Comment by justinwray** [comment]
Edit the files in the `/var/www/fbctf/`

Then run the commands found in my above comment.

**Comment by der-Daniel** [comment]
awesome thanks!
