### ISSUE TITLE
switch from dev to prod?

### ISSUE THREAD

**Issue by htsdeshi** [facebook/fbctf#505]
latest version of fbctf wondering the process to switch from development to production mode without losing changes.

**Comment by stevcoll** [comment]
This depends somewhat on your specific installation. For example, do you plan to utilize a self-signed certificate, Let's Encrypt, or your own cert? Below is some general info on the process of moving from dev to prod. Take a backup just in case, but none of this should modify your database.

1. Enable HHVM Repo Authoritative Mode:

```
cat /etc/hhvm/server.ini | sed "s|/var/run/hhvm/hhvm.hhbc|/var/cache/hhvm/hhvm.hhbc|g" | sudo tee /etc/hhvm/server.ini
sudo hhvm-repo-mode enable /var/www/fbctf
sudo chown www-data:www-data /var/cache/hhvm/hhvm.hhbc
```

2. Generate Certificate:

Utilize your own SSL Certificate for production mode:

```
sudo mkdir /etc/nginx/certs
sudo cp [Path to SSL Cert PEM File] /etc/nginx/certs/fbctf.crt
sudo cp [Path to SSL Key File] /etc/nginx/certs/fbctf.key
```

Generate Let’s Encrypt Valid SSL Certificate for production mode only:

```
sudo mkdir /etc/nginx/certs
wget -q https://dl.eff.org/certbot-auto -O /usr/bin/certbot-auto
sudo chmod a+x /usr/bin/certbot-auto
/usr/bin/certbot-auto certonly -n --agree-tos --standalone --standalone-supported-challenges tls-sni-01 -m "[Email]" -d "[Domain]"
sudo ln -s "/etc/letsencrypt/live/[Domain]/fullchain.pem" /etc/nginx/certs/fbctf.crt || true
sudo ln -s "/etc/letsencrypt/live/[Domain]/privkey.pem" /etc/nginx/certs/fbctf.key || true
```
3. Set Certificate

`vi /var/www/fbctf/extra/nginx.conf`

Replace "/etc/nginx/certs/dev.crt" with path to prod cert
Replace "/etc/nginx/certs/dev.key" with path to prod key

4. Reconfigure Nginx and restart:

```
sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -sf /etc/nginx/sites-available/fbctf.conf /etc/nginx/sites-enabled/fbctf.conf
sudo nginx -t
sudo service nginx restart
```
