### ISSUE TITLE
updating menus

### ISSUE THREAD

**Issue by htsdeshi** [facebook/fbctf#506]
im using the current release of the platform in production mode. I notice css now updates fine, but when i modify php im not seeing any changes. someone else had told me to run some stuff to update it all and when i ran that on this version it froze creating the hhbc binary part and i had to completely re-install my OS and the platform. What is the proper way of updating for production?

**Comment by stevcoll** [comment]
Yes after your code changes you need to run these commands to rebuild the HHVM cache:

```
sudo rm /var/cache/hhvm/hhvm.hhbc
sudo hhvm-repo-mode enable "/var/www/fbctf"
sudo chown www-data:www-data /var/cache/hhvm/hhvm.hhbc
sudo service hhvm start
sudo service nginx restart
```
