### ISSUE TITLE
Competition Time Format

### ISSUE THREAD

**Issue by MKansagra** [facebook/fbctf#507]
I just installed the latest version of FBCTF on Ubuntu 14.04 x64 and everything is working fine as expected.
However, I am little confused when setting the competition time. I have already looked at almost all Issues that were created about the topic and did not find information about the format.

There is no format of how it should be inputted in FAQ or other files.
_Do I have to enter time in 24 Hours aka Military Time or 12-Hour time?_

It would be useful if you can create a text field mask that instructs users to enter time in a certain format like HH:MM or HHMM etc.

**Comment by stevcoll** [comment]
Yes it's 24-hour time and utilizes your system time.

That's a good idea on the text field mask, we will look into adding that!

**Comment by MKansagra** [comment]
Great. Thanks for the help. Appreciate it.

**Comment by MKansagra** [comment]
Uh oh, Not sure what's going on.

So I enter the time as shown in the picture (Before.png), but when I refresh the page, it changes to some random time every time and doesn't stay as my inputted time. 
![after](https://cloud.githubusercontent.com/assets/9116740/26290899/d19aed74-3e78-11e7-9b6c-7ce04197e145.PNG)
![before](https://cloud.githubusercontent.com/assets/9116740/26290900/d1a8153a-3e78-11e7-96a5-1fb161637429.PNG)

Is there a bug or something I have to change?

**Comment by stevcoll** [comment]
That looks like a time zone issue. I think the autostart/stop may be using GMT time. Try setting your system time to GMT. If that doesn't work change the database time to GMT.

**Comment by stevcoll** [comment]
Or is your system time set to GMT, and you're setting the start time on another time zone?

**Comment by MKansagra** [comment]
I was actually just going to say the exact same thing. I just changed the timezone and rebooted. It works flawlessly. I am in EST timezone.

I saw that there seems to be a lot of issues about the timing issue. It would be good to add that to documentation too on top of Textbox mask.
Thanks for the help.
