### ISSUE TITLE
Team_members display issue. 

### ISSUE THREAD

**Issue by ufo009e** [facebook/fbctf#508]
When click team, nothing shows under team_members. I checked the source code and noticed in src/data/teams.php did no define the data source of team_members. So current php code did not pull the data from database at all. I fixed this but since I am not a developer so I'd better do not put my ugly code here. Hope you guys can fix it. 

        'team_members' => array(),  <<<<<

**Comment by stevcoll** [comment]
You would want to look at the files under src/models/

In this case src/models/Team.php. The function is genTeamData(). It returns the team members from the database, if they were created.
