### ISSUE TITLE
Failed to add flag level

### ISSUE THREAD

**Issue by xiaji261** [facebook/fbctf#51]
I tried to add flag level. When I completed details and clicked "create" button, but no new flag level was created. It seems that the create button doesn't make sense. Could you kindly help me to solve this issue? Thanks very much

**Comment by javuto** [comment]
Can you check for errors in ```/var/log/hhvm/error.log```? Do other operations that involve database write access work? For example, can you create new teams or categories? Can you create new Quiz levels?

**Comment by mpomarole** [comment]
Did you refresh the page after adding the level? We don't have those actions ajaxified yet so you would need a refresh to see the new challenge.

**Comment by gsingh93** [comment]
If the challenge was created but the page required a manual refresh, that's a bug as well. The page should refresh automatically.

I'd like to see `/var/log/hhvm/error.log` as well.

**Comment by xiaji261** [comment]
Thanks for your kingly help. As you have suggested, I check these aspects:
1. I can create create new teams or categories successfully. 
2. I tried to refresh the page but no new flag level was created. 
3. For /var/log/hhvm/error.log. Once I click create button in adding flag level, there will be a new line in /var/log/hhvm/error.log:
> [Sat May 14 19:50:44 2016] [hphp] [1014:7f1661fff700:7:000001] [] \nFatal error: Uncaught exception 'HH\\InvariantException' with message 'Expected points to be an int' in /var/www/fbctf/src/Utils.php:30\nStack trace:\n#0 /var/www/fbctf/src/Utils.php(30): HH\\invariant_violation()\n#1 /var/www/fbctf/src/controllers/ajax/AdminAjaxController.php(202): must_have_int()\n#2 /var/www/fbctf/src/controllers/ajax/AjaxController.php(14): AdminAjaxController->genHandleAction()\n#3 /var/www/fbctf/src/Router.php(54): AjaxController->genHandleRequest()\n#4 /var/www/fbctf/src/Router.php(13): Router::genRouteAjax()\n#5 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#6 /var/www/fbctf/src/index.php(19): genInit()\n#7 {main}
So it seems that clicking create button result in an error.

**Comment by xiaji261** [comment]
The error message is a call stack:
Fatal error: Uncaught exception 'HH\\InvariantException' with message 'Expected points to be an int' in /var/www/fbctf/src/Utils.php:30
Stack trace:
#0 /var/www/fbctf/src/Utils.php(30): HH\\invariant_violation()
#1 /var/www/fbctf/src/controllers/ajax/AdminAjaxController.php(202): must_have_int()
#2 /var/www/fbctf/src/controllers/ajax/AjaxController.php(14): AdminAjaxController->genHandleAction()
#3 /var/www/fbctf/src/Router.php(54): AjaxController->genHandleRequest()
#4 /var/www/fbctf/src/Router.php(13): Router::genRouteAjax()
#5 /var/www/fbctf/src/index.php(7): Router::genRoute()
#6 /var/www/fbctf/src/index.php(19): genInit()\n#7 {main}
It seems that the code has some defects.

**Comment by mpomarole** [comment]
@xiaji261 what version of hhvm are you running? You can call `hhvm --version` to check it out.

**Comment by xiaji261** [comment]
@mpomarole I executed your command and this is the result:
lhy@ubuntu:~$ hhvm --version
HipHop VM 3.13.1 (rel)
Compiler: tags/HHVM-3.13.1-0-g4f382ad928a6e2a0607a8dcb251002aca77f11f6
Repo schema: 655b5912cb8136e9df6f9be972153e38ac446e0f

**Comment by gsingh93** [comment]
> Expected points to be an int

What value are you using for points?

**Comment by xiaji261** [comment]
@gsingh93 Thanks for your kindly help. Previously I input a string for points. Now my problem is solved. Thanks for all your help.

**Comment by gsingh93** [comment]
No problem. I will add some client side validation in the future to make sure that's an int.
