### ISSUE TITLE
xz: (stdin): File format not recognized

### ISSUE THREAD

**Issue by khtq** [facebook/fbctf#524]
Ubuntu Server 14.04 x64
After steps by [Production Installation Guide](https://github.com/facebook/fbctf/wiki/Installation-Guide,-Production), received  an error as bellow:
![untitled](https://user-images.githubusercontent.com/14858490/27046231-ce5b2852-4fcd-11e7-8ac2-2c4739e7f926.png)

Command executed:

> sudo ./extra/provision.sh -m prod -s $PWD

**Comment by stevcoll** [comment]
This is likely a system time issue, preventing a successful SSL negotiation on the curl download. Make sure your date/time is set correctly, then rerun provision.

**Comment by khtq** [comment]
I found the problem was locate at `extra/lib.sh`

> function install_unison() {
>   log "Installing Unison 2.48.4"
>   cd /
>   curl -sL https://www.archlinux.org/packages/extra/x86_64/unison/download/ | sudo tar Jx
> }
`curl` couldn't receive any files, so it lead to that error
I ran `curl -sLv https://www.archlinux.org/packages/extra/x86_64/unison/download/` that say invalid certificate
```
* Hostname was NOT found in DNS cache
*   Trying 138.201.81.199...
*   Trying 2a01:4f8:172:1d86::1...
* Immediate connect fail for 2a01:4f8:172:1d86::1: Network is unreachable
* Connected to www.archlinux.org (138.201.81.199) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS alert, Server hello (2):
* SSL certificate problem: certificate is not yet valid
* Closing connection 0
```
Maybe my machine problem, not cert itself. So for any one who meet that same problem, edit `extra/lib.sh` (install_unison function) to:
`curl -sLk https://www.archlinux.org/packages/extra/x86_64/unison/download/`

**Comment by stevcoll** [comment]
Yes definitely a time issue, your computer has the wrong date/time set so it thinks the cert is invalid.
