### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by MuTouRend** [facebook/fbctf#527]
Development 
Runing :  apt-get update 

Err http://dl.hhvm.com trusty InRelease                                        
  
Err http://dl.hhvm.com $(lsb_release InRelease                                 
  
Err http://dl.hhvm.com trusty Release.gpg                                      
  Could not resolve 'dl.hhvm.com'
Err http://dl.hhvm.com $(lsb_release Release.gpg                               
  Could not resolve 'dl.hhvm.com'
Get:13 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [620 kB]
Fetched 2,670 kB in 1min 2s (42.9 kB/s)                                        
Reading package lists... Done
W: Failed to fetch http://dl.hhvm.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://dl.hhvm.com/ubuntu/dists/$(lsb_release/InRelease  

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/multiverse/source/Sources  Hash Sum mismatch

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/restricted/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/universe/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/multiverse/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/main/binary-i386/Packages  Hash Sum mismatch

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/main/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/restricted/i18n/Translation-en  Hash Sum mismatch

W: Failed to fetch http://extras.ubuntu.com/ubuntu/dists/trusty/main/binary-i386/Packages  Hash Sum mismatch

W: Failed to fetch http://dl.hhvm.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'dl.hhvm.com'

W: Failed to fetch http://dl.hhvm.com/ubuntu/dists/$(lsb_release/Release.gpg  Could not resolve 'dl.hhvm.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.
but this site is through  http://dl.hhvm.com/
what should i do
thanks

**Comment by iangcarroll** [comment]
Are you actually connected to the internet? What do `ping security.ubuntu.com` and `curl http://security.ubuntu.com/ubuntu/ubuntu/dists/trusty-security/multiverse/binary-amd64/Release` give you?

Is this in the Docker image or your own server?

> W: Failed to fetch http://dl.hhvm.com/ubuntu/dists/$(lsb_release/Release.gpg Could not resolve 'dl.hhvm.com'

This is messed up too; you may need to check your `sources.list` and replace `$(lsb_release` with `trusty`.
