### ISSUE TITLE
Failed to fetch repository.

### ISSUE THREAD

**Issue by rajeshmajumdar** [facebook/fbctf#528]
I am using the current version of fbctf, just cloned and tried to run that production installation script. 
There I got an error.
Failed to fetch http://dl.hhvm.com/ubuntu/dists/zesty/main/binary-i386/Packages  404  Not Found [IP: 2600:3402:200:227::2%4 80].
I tried to manually add this repo, but same error exists.

**Comment by iangcarroll** [comment]
HHVM has no packages for zesty; you can check the supported versions at http://dl.hhvm.com/ubuntu/dists/.

The only Ubuntu version FBCTF supports is 14.04.
