### ISSUE TITLE
Title Tag "Facebook CTF" is not able change 

### ISSUE THREAD

**Issue by sandeepl337** [facebook/fbctf#529]
Please include the following information when filing an issue 
• Current version of FBCTF installed (503)
We have installed with Ubuntu 14.04 and followed the manual step. 

I'm finding difficulty to change the Title Tag of the CTF script. I've found that /src/controller/ folder has some file which contain the string "Facebook CTF" which will be printed in the title bar. 

I've changed all the text and still it shows the old title bar i.e. "Facebook CTF". Used multiple browsers and other stuff but still shows the same. It might some problem with server cache or may be I'm unable to find why it is displaying "Facebook CTF". 

Kindly help to resolve this issue.

**Comment by wisco24** [comment]
You need to run these commands to rebuild the HHVM cache:

`sudo rm /var/cache/hhvm/hhvm.hhbc
sudo hhvm-repo-mode enable "/var/www/fbctf"
sudo chown www-data:www-data /var/cache/hhvm/hhvm.hhbc
sudo service hhvm start
sudo service nginx restart

**Comment by juliannagler** [comment]
@sandeepl337 if this answers you're question, please close out the open issue. Thanks for the help @wisco24!

**Comment by contivero** [comment]
Just in case others have a similar issue, I found what was needed in /var/run/* instead of /var/cache,
i.e. I got inside the VM with `vagrant ssh`, and then did:
```
sudo rm /var/run/hhvm/hhvm.hhbc
sudo hhvm-repo-mode enable "/var/www/fbctf"
sudo chown www-data:www-data /var/run/hhvm/hhvm.hhbc
sudo service hhvm start
sudo service nginx restart
```
