### ISSUE TITLE
white page after the install finish and said ready in https://10.10.10.5 

### ISSUE THREAD

**Issue by mikimaine** [facebook/fbctf#53]
after i have run the commands as the instruction, it downloaded all the files and give me the message fbctf deployment is complete! ready in https://10.10.10.5 when i hit that server in my browser it is a white page. no error message or nothing simply empty. 

what did i have done wrong ??

**Comment by mpomarole** [comment]
Could you please paste the output of the provision script and `/var/log/hhvm/error.log` for us to help debug your problems?

**Comment by mikimaine** [comment]
[Fri May 13 21:04:39 2016] [hphp] [10503:7f23283ff700:1:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 21:04:44 2016] [hphp] [10503:7f23283ff700:4:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 21:04:53 2016] [hphp] [10503:7f23283ff700:5:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 21:05:24 2016] [hphp] [10503:7f23283ff700:7:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 21:05:52 2016] [hphp] [10503:7f23283ff700:9:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 21:06:20 2016] [hphp] [10503:7f23283ff700:10:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 21:06:23 2016] [hphp] [10503:7f23283ff700:11:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 21:07:19 2016] [hphp] [10503:7f23283ff700:12:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 21:08:45 2016] [hphp] [10503:7f23283ff700:13:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 21:08:45 2016] [hphp] [10503:7f23283ff700:14:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 21:10:21 2016] [hphp] [10503:7f23283ff700:15:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 21:21:01 2016] [hphp] [10503:7f23283ff700:20:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 22:53:56 2016] [hphp] [10503:7f23283ff700:21:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 22:53:57 2016] [hphp] [10503:7f23283ff700:22:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 22:53:58 2016] [hphp] [10503:7f23283ff700:23:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 22:53:59 2016] [hphp] [10503:7f23283ff700:24:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 22:54:27 2016] [hphp] [10503:7f23283ff700:25:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3
[Fri May 13 22:54:40 2016] [hphp] [10503:7f23283ff700:27:000001] [] \nFatal error: require_once(../vendor/autoload.php): File not found in /var/www/fbctf/src/index.php on line 3

**Comment by mikimaine** [comment]
what did i miss why is not composer available?

**Comment by smileboywtu** [comment]
just use ssh to connect to you vagrant, and clone this repo, run the provision.sh, to see what's wrong with it. i get some error duo to network and without install g++, fail to install nodejs module,you shoulh check it.

**Comment by javuto** [comment]
Also, if you could attach the provisioning log, it would be great. It lets us understand if there is a problem within the provisioning of the platform.

**Comment by mpomarole** [comment]
@mikimaine this is the same issue as https://github.com/facebook/fbctf/issues/31. Please follow the steps linked there to solve this issue.
