### ISSUE TITLE
Where to point a certificate to in order to make it secure?

### ISSUE THREAD

**Issue by sbszachara** [facebook/fbctf#531]
Hello all,

I've never worked with certificates before so I'm sorry in advance for the noob question. I followed the steps here: https://help.ubuntu.com/lts/serverguide/certificates-and-security.html to get a key and certificate for my machine. I am running a fresh 14.04 ubuntu server with fbctf freshly installed. I generated the key for the entire machine, and not within the fbctf app itself. I don't know if that's a problem, but I figured I should mention it. I sent my certificate to the internal office to get their certificate, and now I'm confused as to what I do next. Basically, I want the https:// to be green and say secure. I was told that I need to have the certificate stored somewhere in order for it to be correctly pointed to, I just don't know where/how to do that. Any help would be appreciated!

Best!

Steven

**Comment by stevcoll** [comment]
If you want a valid certificate then it cannot be self-signed which I believe is what you generated. The platform utilizes Let's Encrypt which can generate a valid certificate for you. Below is the general command you would use to install FBCTF. You would replace domain and email with your information. You have to own the domain of course. Run provision.sh with --help for more information:

`./extra/provision.sh -m prod -s $PWD -c certbot -D "domain" -e "email"`

Below you will find the FBCTF Wiki Installation Guide, where we have some information on different types of certificates in the manual installation section.

[Wiki - Installation Guide](https://github.com/facebook/fbctf/wiki/Installation-Guide,-Production)
