### ISSUE TITLE
how to install ubuntu?

### ISSUE THREAD

**Issue by balagpy** [facebook/fbctf#533]
how to install ubuntu? i  m getting errors

**Comment by iangcarroll** [comment]
Are you asking how to install the operating system Ubuntu or how to install fbctf on Ubuntu?

**Comment by balagpy** [comment]
how to install fbctf on Ubuntu? and how to share that 10.10.10.5 to another systems connected in same network

**Comment by stevcoll** [comment]
Please see the Development and Production guides on the [main page](https://github.com/facebook/fbctf).
