### ISSUE TITLE
Problems running development in docker

### ISSUE THREAD

**Issue by izabellamatos** [facebook/fbctf#534]
Hi!

I was testing CTF development version using Docker, but since this Monday I wasnt't able to build the image. I was having this error:

> compilation terminated.
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     
>     ----------------------------------------
> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-akZxK5/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yAUmzO-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-akZxK5/cryptography/
> /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
>   InsecurePlatformWarning
> The command '/bin/sh -c apt-get update   && apt-get install -y   rsync   curl   ca-certificates   && chown www-data:www-data $HOME   && ./extra/provision.sh -m $MODE -c $TYPE -k $KEY -C $CRT -D $DOMAIN -e $EMAIL -s `pwd` --docker   && rm -f /var/run/hhvm/sock   && apt-get clean   && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 1

So, I created a VM with ubuntu and followed the instalation guide and reproduced the same problems. After some searches I discovered that I needed to install "build-essential libssl-dev libffi-dev python-dev curl" . After that the provision script worked fine. In my dockerfile I inserted this line "**apt-get build-essential libssl-dev libffi-dev python-dev curl -y**".

I don't know if this is a problem with me, but I'm sharing what I've done.

Ps.: I'm using the FBCTF latest version avaliable on GIT

**Comment by stevcoll** [comment]
Thanks @izabellamatos! I have tested and confirmed this problem exists in Docker, as well as your solution fixing the issue.

Would you like to submit a PR for this since you came up with the solution? You can add each package name to its own line starting at line 20 (adding the trailing backslash and newline after each one). You will not ned -y as it's implemented at the top of that batch apt-get install. Also curl is already being installed so you won't need that one.

**Comment by izabellamatos** [comment]
I've already done the PR!
Sorry the delay.
