### ISSUE TITLE
docker production doesn't work

### ISSUE THREAD

**Issue by swarajd** [facebook/fbctf#536]
• **Current version of FBCTF installed (commit head)**: 51e06a7094df9d9e66249b40cae387d2150a52fd
• **System and Installation details, such as the Linux distribution used, and installation method you chose**: Amazon Linux, docker
• **Detailed description of the problem. Include steps to reproduce the problem when possible**: I made an EC2 instance of this type: (Amazon Linux AMI 2017.03.1 (HVM), SSD Volume Type), sshed in, installed git, installed docker, cloned the fbctf repo, ran this command: `docker build --build-arg MODE=prod --build-arg DOMAIN=vtfbctf.com --build-arg EMAIL=admin@vtfbctf.com --build-arg TYPE=certbot -t="fbctf_in_prod" .` 
• Screenshots to help describe the problem when appropriate.

![image](https://user-images.githubusercontent.com/1250084/28495839-412a0946-6f29-11e7-8891-3cd5663ed56a.png)

• **Relevant output from any logs examined**:
• **Any steps you have taken to resolve the issue**: I tried to use different image types on amazon, but I realized that might not make much sense. I'm using docker, and the ssl cert wasn't generated, but I'm not sure that should affect the rest of the install. I don't know at all why both nginx and mysql won't start. 

extra notes:
- `docker run` doesn't work
- `docker ps` returns an empty list after I attempt to `docker run`

**Comment by stevcoll** [comment]
First I'm curious why you decided to use Docker on EC2? It sounds like this is for a production server installation. I would definitely recommend installing using the [manual](https://github.com/facebook/fbctf/wiki/Installation-Guide,-Production#manual-preferred) method, especially on EC2. Make sure you use a Ubuntu 14.04 x64 instance.

The log indicates that connections were being refused to your domain.  Assuming the domain was pointing to the EC2 instance the following may have been the cause:

1. Web connections aren't being allowed through to the EC2 instance (Security Groups or Network Access Control).
2. Traffic needs to be properly routed heading from the EC2 instance to docker.
3. Both of the above.

You should at least be able to solve the second potential problem by provisioning manually.

**Comment by javuto** [comment]
Agree with @stevcoll here, a quick solution would be to re-provision that machine in EC2 and skip docker altogether, just provision it in prod mode. That will also take care of the certificate (using let's encrypt).

I am also curious, is there a reason why you want to use docker inside of an EC2 instance?

**Comment by swarajd** [comment]
Yeah I manually provisioned it on digital ocean instead (for some reason I couldn't ssh onto an ubuntu 14.04 EC2 instance, that's another story). That solved everything but the ssl cert is still invalid, which tbh I'm fine with atm and I can probably figure out how to fix that.
