### ISSUE TITLE
code used

### ISSUE THREAD

**Issue by gregtampa** [facebook/fbctf#545]
looks like some codebase was used from https://github.com/rgajendran/ctf_marker

any credit given?

**Comment by gsingh93** [comment]
> looks like some codebase was used from https://github.com/rgajendran/ctf_marker

What makes you think that? First of all, FBCTF has been around for a lot longer than that project, so we definitely did not use any code from it. Second of all, I just took a look at the code for that project, and it's not similar at all. We're using Hack for the backend, and they're using plain PHP. It's completely different.
