### ISSUE TITLE
When the changes are made in the code, it isn't rebuilding.

### ISSUE THREAD

**Issue by 0x1bitcrack3r** [facebook/fbctf#546]

**Comment by juanrossi** [comment]
Do you have `hhvm.repo.authoritative` set to `true`? If that's the case, then you are running the CTF from the already pre-compiled build. The only way I know of to run the code without re-building is setting that variable to `false` and restarting hhvm.

**Comment by stevcoll** [comment]
Please reference the [Wiki](https://github.com/facebook/fbctf/wiki/FAQ#how-do-i-make-a-code-change-to-fbctf-in-production-mode) for instructions on making code changes to production installs.
