### ISSUE TITLE
Uncaught 500 in Admin Login

### ISSUE THREAD

**Issue by mike-bailey** [facebook/fbctf#547]
• Version: Latest as of this issue
• System: t2.xlarge AWS Ubuntu instance
• When cancelling out standard login and only allowing admin login, I get 500's when trying to log in as admin login.
Logs say 
```

[Sat Aug 19 07:24:53 2017] [hphp] [11952:7f745c3ff700:1:000001] [] \nFatal error: Uncaught exception 'HH\\InvariantException' with message 'Index team_id not found in container' in /var/www/fbctf/src/Utils.php:10\nStack trace:\n#0 /var/www/fbctf/src/Utils.php(10): HH\\invariant_violation()\n#1 /var/www/fbctf/src/Utils.php(27): must_have_idx()\n#2 /var/www/fbctf/src/controllers/ajax/IndexAjaxController.php(79): must_have_int()\n#3 /var/www/fbctf/src/controllers/ajax/AjaxController.php(14): IndexAjaxController->genHandleAction()\n#4 /var/www/fbctf/src/Router.php(54): AjaxController->genHandleRequest()\n#5 /var/www/fbctf/src/Router.php(14): Router::genRouteAjax()\n#6 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#7 /var/www/fbctf/src/index.php(17): genInit()\n#8 {main}

```
Attempted remediation: I can't get in now. I tried resetting the login bit and it won't reset. I'll update god forbid I pop the actual code.

**Comment by stevcoll** [comment]
We will definitely look into that ASAP. In the meantime, can you get into the MySQL client? [Backup your database](https://github.com/facebook/fbctf/wiki/FAQ#how-can-i-backup-and-restore-an-event-using-the-database), and then run this. It should enable login again:

`UPDATE configuration SET value = 1 WHERE field = "login";`

**Comment by mike-bailey** [comment]
Thank you. Did that and tried to bump someone who was in team_data (since default admin isn't) to admin, still no dice. Also restarted hhvm and nginx.

**Comment by stevcoll** [comment]
Try to [flush Memcached](https://github.com/facebook/fbctf/wiki/FAQ#when-and-how-should-i-flush-memcached) too.

Is your teams table looking OK in MySQL?

**Comment by mike-bailey** [comment]
After flipping bits around in configuration and flushing memcached I'm in. Problem is still probably legit though. 
Teams table is literally:
```
+----+--------+-----------+--------------------------------------------------------------+--------+---------------------+---------+-------+-----------+---------+---------------------+
| id | active | name      | password_hash                                                | points | last_score          | logo    | admin | protected | visible | created_ts          |
+----+--------+-----------+--------------------------------------------------------------+--------+---------------------+---------+-------+-----------+---------+---------------------+
|  1 |      1 | admin     | $2y$muhhashgoeshere. |      0 | 2017-08-19 04:26:26 | admin   |     1 |         1 |       1 | 2017-08-19 04:26:26 |
|  2 |      1 | Test Team | $2y$muhhashgoeshere |      0 | 2017-08-19 08:04:51 | alien-2 |     1 |         0 |       1 | 2017-08-19 06:52:16 |
+----+--------+-----------+--------------------------------------------------------------+--------+---------------------+---------+-------+-----------+---------+---------------------+
2 rows in set (0.00 sec)
```

**Comment by stevcoll** [comment]
Great, thanks for reporting the issue! We will see if that can be reproduced.

**Comment by mike-bailey** [comment]
No problem, thanks for the platform and the prompt response! I have maybe a little downtime between when the competition ends and when I have to kill the EC2 instance so if you have issues replicating LMK.

**Comment by stevcoll** [comment]
I was unable to reproduce this issue. Memcached is not being used to store login verification in terms of whether a team is active or protected. This query is run on every attempted login:

`SELECT * FROM teams WHERE id = %d AND (active = 1 OR admin = 1) LIMIT 1`

We will keep an eye out regarding this issue, but I went through a bunch of different scenarios and could not duplicate the 500 errors.

**Comment by gsamuelhays** [comment]
I was able to reproduce the issue (accidentally). After setting the database flag to login = 1  (it was 0) and restarting the CTF box, didn't work. Turns out (and, unfortunately I did not investigate this too deeply...) I just cleared my cookies for that site and tried again and everything worked as expected. May look into it further if there is interest.
