### ISSUE TITLE
Provision Failing - Dropkickjs SyntaxError: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by stevcoll** [facebook/fbctf#554]
The following error is currently printed during provisioning:

```
Running "browserify:dist" (browserify) task
>> SyntaxError: 'import' and 'export' may only appear at the top level (2:0) while parsing /var/www/fbctf/node_modules/dropkickjs/src/dropkick.js while parsing file: /var/www/fbctf/node_modules/dropkickjs/src/dropkick.js
```
This causes the entire copy:browserify task to fail. Provision completes, but the entire dist directory is missing, and thus the platform is unusable.

**Comment by stevcoll** [comment]
This issue is caused by the recent release of dropkickjs 2.2.0, which is incompatible with ES6 specs. The solution is to force dropkickjs to version 2.1.10

The package.json file must be updated. Remove the carrot from the dropkickjs line, as seen below.

`"dropkickjs": "2.1.10",`

This issue will be resolved with a PR imminently.

**Comment by justinwray** [comment]
PR #555 has been submitted to address this issue.
