### ISSUE TITLE
Changes for running on 10.10.10.x networks

### ISSUE THREAD

**Issue by w3bm0nk3y** [facebook/fbctf#56]
When the end user's network is 10.10.10.x and runs `vagrant up` they will run into the following error:
`The specified host network collides with a non-hostonly network!`

**Comment by gsingh93** [comment]
First of all, you mean `10.0.1.x`. Secondly, just change the IP in the Vagrantfile before running `vagrant up`: https://github.com/facebook/fbctf/blob/master/Vagrantfile#L8

We may add a troubleshooting section in the future with this info.

**Comment by w3bm0nk3y** [comment]
Thank you for the response. I did mean 10.10.10.x as my ip address is 10.10.10.21 that caused the error.  I changed the IP address in the Vagrantfile from this:
`config.vm.network "private_network", ip: "10.10.10.5"`
to 
`config.vm.network "private_network", ip: "10.10.11.5"`
as well as trying 
`config.vm.network "private_network", type: "dhcp"`

All of the changes ended up giving the following error:
```
502 Bad Gateway
nginx
```
