### ISSUE TITLE
Failure during install

### ISSUE THREAD

**Issue by pyrodie18** [facebook/fbctf#560]
When attempting to do a fresh install following the directions for a production manual install I eventually get the following error while running the "`./extra/provision.sh -m prod -s $PWD`" command

> /usr/local/lib/node_modules/npm/lib/config/cmd-list.js:113 module.exports.aliases = Object.assign({}, shorthands, affordances)
>                                 ^
> 
> TypeError: Object function Object() { [native code] } has no method 'assign'
>     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/cmd-list.js:113:33)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at /usr/local/lib/node_modules/npm/lib/npm.js:37:17
>     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:471:3)
>     at Module._compile (module.js:456:26)

Doing some googling, I found https://stackoverflow.com/questions/44988592/npm-command-not-working-on-ubuntu and tried doing the accepted answer.  When I do that and then rerun the script I get....

> [+] Installing npm
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  npm : Depends: nodejs but it is not going to be installed
>        Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
>        Depends: node-ansi but it is not going to be installed
>        Depends: node-archy but it is not going to be installed
>        Depends: node-block-stream but it is not going to be installed
>        Depends: node-fstream (>= 0.1.22) but it is not going to be installed
>        Depends: node-fstream-ignore but it is not going to be installed
>        Depends: node-github-url-from-git but it is not going to be installed
>        Depends: node-glob (>= 3.1.21) but it is not going to be installed
>        Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
>        Depends: node-inherits but it is not going to be installed
>        Depends: node-ini (>= 1.1.0) but it is not going to be installed
>        Depends: node-lockfile but it is not going to be installed
>        Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
>        Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
>        Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
>        Depends: node-gyp (>= 0.10.9) but it is not going to be installed
>        Depends: node-nopt (>= 2.1.1) but it is not going to be installed
>        Depends: node-npmlog but it is not going to be installed
>        Depends: node-once but it is not going to be installed
>        Depends: node-osenv but it is not going to be installed
>        Depends: node-read but it is not going to be installed
>        Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
>        Depends: node-request (>= 2.25.0) but it is not going to be installed
>        Depends: node-retry but it is not going to be installed
>        Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
>        Depends: node-semver (>= 2.1.0) but it is not going to be installed
>        Depends: node-sha but it is not going to be installed
>        Depends: node-slide but it is not going to be installed
>        Depends: node-tar (>= 0.1.18) but it is not going to be installed
>        Depends: node-which but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

This is being installed on a google cloud instance with Ubuntu 14.04

**Comment by ethanaldrich9986** [comment]
@pyrodie18 On other issues this has been asked. [Here](https://github.com/facebook/fbctf/issues/550) is a link to the most recent one. =)

**Comment by justinwray** [comment]
@pyrodie18 / Others:

The `master` branch was just updated with some fixes to the failing build process.  Please try the setup process again and see if the new updates have resolved your issue.  Take a look at the [Quick Setup Guide](https://github.com/facebook/fbctf/wiki/Quick-Setup-Guide) as well.

**Comment by pyrodie18** [comment]
Latest PR took care of the issue.  Just reran a clean install without issues.
