### ISSUE TITLE
Setting the game schedule is really buggy. 

### ISSUE THREAD

**Issue by Ysagi** [facebook/fbctf#584]
Hi.

Setting the game schedule is really buggy. I'm trying to change the "Game start" and "Game end" under "Game Schedule" in "Configuration". I'm setting the “hours” from "13" to "15", but nothing happens. It seems that the request is not updated. Other setting will result in that the "index.php?p=admin&page=configuration" will be reloaded with the new values/setting but not the "game schedule". 
Maybe it is better to have a button at the end of the page for "Configuration", and when the button is pressed the values being changed will get reloaded.

• Version of FBCTF installed: commit 1f236bba7e5e7a3e7169ff61037502a6928a94ba
• Linux system: Ubuntu 14.04 (x86_64)

Best regards Matthew

**Comment by stevcoll** [comment]
@Ysagi 

Just tested this and you should indeed see this request whenever game schedule values are changed:

`index.php?p=admin&ajax=true`

If not are you seeing any errors in the console?

**Comment by Ysagi** [comment]
@stevcoll 

Hi again.
The problem is when is change the date or time nothing is happening. Seems like the ajax-routine is not working for me. I have to go e.g. to the "Language" and choose English / English. Then the date/time seems to work for me.

When going with "https://<IP address>/index.php?p=admin&ajax=true" 
I get "This page isn’t working.  <IP address> is currently unable to handle this request.
HTTP ERROR 500".

Best regards Matthew

**Comment by stevcoll** [comment]
@Ysagi I am testing it with various languages, still working for me. Is there a particular language you're having issues with?

**Comment by Ysagi** [comment]
@stevcoll

Hi again.
The problem is when is change the date or time nothing is happening. Seems like the ajax-routine is not working for me. The screen doesn't update after I change the date/time. I have to do something else to get it updated e.g. change the language. So the issue is not any particular language settings. Should the ajax-routine kick-in (refresh/reload the page) immediately after I change the date/time?

Best regards Matthew

**Comment by stevcoll** [comment]
@Ysagi Yes for me it's immediately performing the requests when any schedule fields are modified (after clicking off of the field)

What are you getting in the HHVM [error log](https://github.com/facebook/fbctf/wiki/FAQ#how-can-i-debug-issues-with-fbctf)?

**Comment by Ysagi** [comment]
@stevcoll 

The log doesn't say much:

I'm in the "Configuration" part and change the date/time. No Ajax-routine is invoked so I go to "Controls" and back to "Configuration". The time/date is not changed :-(

/var/log/hhvm$ tail -f error.log
[Mon Oct 16 06:56:01 2017] [hphp] [1071:7f05023ff700:35:000012] [] \nWarning: 'Minute' has no translation in the selected language. Using the English version instead.
[Mon Oct 16 06:56:01 2017] [hphp] [1071:7f05023ff700:35:000013] [] \nWarning: 'LiveSync' has no translation in the selected language. Using the English version instead.
[Mon Oct 16 06:56:01 2017] [hphp] [1071:7f05023ff700:35:000014] [] \nWarning: 'Optional LiveSync Auth Key' has no translation in the selected language. Using the English version instead.
[Mon Oct 16 06:56:01 2017] [hphp] [1071:7f05023ff700:35:000015] [] \nWarning: 'Custom Organization' has no translation in the selected language. Using the English version instead.
[Mon Oct 16 06:56:01 2017] [hphp] [1071:7f05023ff700:35:000016] [] \nWarning: 'Custom Byline' has no translation in the selected language. Using the English version instead.
[Mon Oct 16 06:56:01 2017] [hphp] [1071:7f05023ff700:35:000018] [] \nWarning: 'CTF' has no translation in the selected language. Using the English version instead.
[Mon Oct 16 06:58:04 2017] [hphp] [1071:7f05023ff700:36:000001] [] #0 /var/www/fbctf/src/Router.php(83): SessionUtils::sessionLogout()\n#1 /var/www/fbctf/src/Router.php(20): Router::genRouteNormal()\n#2 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#3 (): genInit()\n#4 /var/www/fbctf/src/index.php(17): HH\\Asio\\join()\n#5 {main}
[Mon Oct 16 06:58:04 2017] [hphp] [1071:7f04f23ff700:32:000002] [] \nWarning: 'CTF' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:13:14 2017] [hphp] [1069:7f88babff700:1:000002] [] \nWarning: 'CTF' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:13:21 2017] [hphp] [1069:7f88babff700:2:000001] [] Getting admin
[Wed Oct 18 07:13:21 2017] [hphp] [1069:7f88babff700:2:000002] [] Getting monitor
[Wed Oct 18 07:13:21 2017] [hphp] [1069:7f88babff700:2:000003] [] Getting Lag1
[Wed Oct 18 07:13:21 2017] [hphp] [1069:7f88babff700:2:000004] [] Getting HacKTH
[Wed Oct 18 07:13:21 2017] [hphp] [1069:7f88babff700:2:000005] [] Getting TIJ
[Wed Oct 18 07:13:21 2017] [hphp] [1069:7f88babff700:2:000006] [] Getting slabdrill
[Wed Oct 18 07:13:21 2017] [hphp] [1069:7f88babff700:2:000007] [] Getting AFDM2217
[Wed Oct 18 07:13:21 2017] [hphp] [1069:7f88babff700:2:000008] [] Getting noname
[Wed Oct 18 07:13:21 2017] [hphp] [1069:7f88babff700:2:000010] [] \nWarning: 'CTF' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000001] [] \nWarning: 'Change' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000002] [] \nWarning: 'Autorun Cycle (s)' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000003] [] \nWarning: 'Auto Announcements' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000004] [] \nWarning: 'Game Schedule' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000005] [] \nWarning: 'Game Start Year' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000006] [] \nWarning: 'Game End Year' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000007] [] \nWarning: 'Month' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000008] [] \nWarning: 'Month' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000009] [] \nWarning: 'Day' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000010] [] \nWarning: 'Day' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000011] [] \nWarning: 'Minute' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000012] [] \nWarning: 'Minute' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000013] [] \nWarning: 'LiveSync' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000014] [] \nWarning: 'Optional LiveSync Auth Key' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000015] [] \nWarning: 'Custom Organization' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000016] [] \nWarning: 'Custom Byline' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:14:06 2017] [hphp] [1069:7f88babff700:4:000018] [] \nWarning: 'CTF' has no translation in the selected language. Using the English version instead.

[Wed Oct 18 07:15:02 2017] [hphp] [1069:7f88bf3ff700:8:000001] [] \nWarning: 'Utilities' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:02 2017] [hphp] [1069:7f88bf3ff700:8:000002] [] \nWarning: 'Flush Memcached' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:02 2017] [hphp] [1069:7f88bf3ff700:8:000003] [] \nWarning: 'Reset Database' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:02 2017] [hphp] [1069:7f88bf3ff700:8:000004] [] \nWarning: 'Restore Database' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:02 2017] [hphp] [1069:7f88bf3ff700:8:000005] [] \nWarning: 'Backup Database' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:02 2017] [hphp] [1069:7f88bf3ff700:8:000006] [] \nWarning: 'Import Attachments' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:02 2017] [hphp] [1069:7f88bf3ff700:8:000007] [] \nWarning: 'Export Attachments' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:02 2017] [hphp] [1069:7f88bf3ff700:8:000009] [] \nWarning: 'CTF' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000001] [] \nWarning: 'Change' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000002] [] \nWarning: 'Autorun Cycle (s)' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000003] [] \nWarning: 'Auto Announcements' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000004] [] \nWarning: 'Game Schedule' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000005] [] \nWarning: 'Game Start Year' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000006] [] \nWarning: 'Game End Year' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000007] [] \nWarning: 'Month' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000008] [] \nWarning: 'Month' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000009] [] \nWarning: 'Day' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000010] [] \nWarning: 'Day' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000011] [] \nWarning: 'Minute' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000012] [] \nWarning: 'Minute' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000013] [] \nWarning: 'LiveSync' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000014] [] \nWarning: 'Optional LiveSync Auth Key' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000015] [] \nWarning: 'Custom Organization' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000016] [] \nWarning: 'Custom Byline' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:07 2017] [hphp] [1069:7f88babff700:10:000018] [] \nWarning: 'CTF' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:29 2017] [hphp] [1069:7f88bf3ff700:9:000001] [] \nWarning: 'Utilities' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:29 2017] [hphp] [1069:7f88bf3ff700:9:000002] [] \nWarning: 'Flush Memcached' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:29 2017] [hphp] [1069:7f88bf3ff700:9:000003] [] \nWarning: 'Reset Database' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:29 2017] [hphp] [1069:7f88bf3ff700:9:000004] [] \nWarning: 'Restore Database' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:29 2017] [hphp] [1069:7f88bf3ff700:9:000005] [] \nWarning: 'Backup Database' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:29 2017] [hphp] [1069:7f88bf3ff700:9:000006] [] \nWarning: 'Import Attachments' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:29 2017] [hphp] [1069:7f88bf3ff700:9:000007] [] \nWarning: 'Export Attachments' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:29 2017] [hphp] [1069:7f88bf3ff700:9:000009] [] \nWarning: 'CTF' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000001] [] \nWarning: 'Change' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000002] [] \nWarning: 'Autorun Cycle (s)' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000003] [] \nWarning: 'Auto Announcements' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000004] [] \nWarning: 'Game Schedule' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000005] [] \nWarning: 'Game Start Year' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000006] [] \nWarning: 'Game End Year' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000007] [] \nWarning: 'Month' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000008] [] \nWarning: 'Month' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000009] [] \nWarning: 'Day' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000010] [] \nWarning: 'Day' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000011] [] \nWarning: 'Minute' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000012] [] \nWarning: 'Minute' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000013] [] \nWarning: 'LiveSync' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000014] [] \nWarning: 'Optional LiveSync Auth Key' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000015] [] \nWarning: 'Custom Organization' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000016] [] \nWarning: 'Custom Byline' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:15:33 2017] [hphp] [1069:7f88babff700:11:000018] [] \nWarning: 'CTF' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:05 2017] [hphp] [1069:7f88bf3ff700:10:000001] [] \nWarning: 'Utilities' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:05 2017] [hphp] [1069:7f88bf3ff700:10:000002] [] \nWarning: 'Flush Memcached' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:05 2017] [hphp] [1069:7f88bf3ff700:10:000003] [] \nWarning: 'Reset Database' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:05 2017] [hphp] [1069:7f88bf3ff700:10:000004] [] \nWarning: 'Restore Database' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:05 2017] [hphp] [1069:7f88bf3ff700:10:000005] [] \nWarning: 'Backup Database' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:05 2017] [hphp] [1069:7f88bf3ff700:10:000006] [] \nWarning: 'Import Attachments' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:05 2017] [hphp] [1069:7f88bf3ff700:10:000007] [] \nWarning: 'Export Attachments' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:05 2017] [hphp] [1069:7f88bf3ff700:10:000009] [] \nWarning: 'CTF' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000001] [] \nWarning: 'Change' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000002] [] \nWarning: 'Autorun Cycle (s)' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000003] [] \nWarning: 'Auto Announcements' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000004] [] \nWarning: 'Game Schedule' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000005] [] \nWarning: 'Game Start Year' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000006] [] \nWarning: 'Game End Year' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000007] [] \nWarning: 'Month' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000008] [] \nWarning: 'Month' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000009] [] \nWarning: 'Day' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000010] [] \nWarning: 'Day' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000011] [] \nWarning: 'Minute' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000012] [] \nWarning: 'Minute' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000013] [] \nWarning: 'LiveSync' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000014] [] \nWarning: 'Optional LiveSync Auth Key' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000015] [] \nWarning: 'Custom Organization' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000016] [] \nWarning: 'Custom Byline' has no translation in the selected language. Using the English version instead.
[Wed Oct 18 07:16:08 2017] [hphp] [1069:7f88babff700:12:000018] [] \nWarning: 'CTF' has no translation in the selected language. Using the English version instead.

Best regards Ysagi

**Comment by stevcoll** [comment]
@Ysagi Don't see any errors in that log, which is strange because if you're getting 500's you should almost certainly have errors in there. Could also check the nginx error log...

I'm mostly out of ideas, but if you can reprovision from scratch, we could take a look at the output of provision (redirect stdout+stderr into a file for the whole setup process). I haven't been able to reproduce this so maybe there are some clues in there.

**Comment by justinwray** [comment]
@Ysagi 

To reaffirm what @stevcoll has said, if you are seeing the AJAX request, but are getting a 500 error, there should be an error in the HHVM error log.  If you do not see any AJAX request at all, then there should be an error in your browser's console.  That is unless your JavaScript files failed to build correctly.

Can you answer the following:

- Do you see any AJAX requests when you change the date value?

- Are any AJAX requests getting HTTP 500 errors?

- Do you see any errors in the browser console?

You can follow @stevcoll's suggestion to reprovision, or you could also perform one intermediate step - running grunt:

```
cd /var/www/fbctf
grunt --force
```

If you attempt to rebuild the JS files with grunt, please provide the output here in this thread.

One final note, please ensure the time you are entering is valid - as you complete the entire time (year, day, min, hour...etc) it will submit multiple requests, but the configuration will not be changed until an entirely valid time is provided.
