### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by skyridertk** [facebook/fbctf#59]
Please put things that work.

**Comment by javuto** [comment]
Can you be more specific?

**Comment by mehnomy** [comment]
@skyridertk Are you trying to use the development or production installation?

My current build for production installation is:
- 2GB Ram, Ubuntu 14.04 with Nginx installed
- SSL Certificate verified with Comodo, and uploaded to cloudflare and configured in default nginx settings
- Run through the instructions which were laid out perfectly fine however i have seen a change in the installation log from using `pwd` to now using $PWD for the ./extra/provision.sh prod command.
- provide your ssl key and crt e.g something like:
/etc/ssl/security_rmit.key
/root/security_rmit.csr
 (Locations will vary depending on where you created your csr and placed your SSL certificate and key.)

Please provide more information on where you're having issues or a error log so we can help you out mate.

**Comment by Mikey828** [comment]
Finances would assist brother

**Comment by mehnomy** [comment]
@Mikey828 

I didn't catch that sorry mate, what did you mean?

**Comment by Mikey828** [comment]
I'm Michael, commander of the Angelic army, a servant of Christ Jesus,
atlantis will soon be raised NWO fast approaching Nero reborn, I seek help
Bless you in Jesus name
Being followed by government
Let them follow for I AM fearless
Any anti spyware basic hacking tools would be helpful
Thank you

**Comment by Excis3** [comment]
Strange people here, just install in a vm in development and you are good to go for testing.
Later you can go for production and get an ssl certificate if you like the system.

**Comment by colbyjoe1919** [comment]
---------- Forwarded message ----------

**Comment by skyridertk** [comment]
@mehnomy Im using the production installation.  I cant locate SSL Certificate file! Any ideas? Im using linux mint.

**Comment by mehnomy** [comment]
Did you create self signed certificates, or are you using a certificate which you have verified with a SSL provider?

Most common locations are:
- /etc/ssl/certs
- /etc/ssl/private
- /

**Comment by skyridertk** [comment]
Its not working. I created some in /etc/nginx/cert/.

**Comment by skyridertk** [comment]
The thing is that fbctf is not loading. Its not opening at http://10.10.... Also vagrant is failing

**Comment by javuto** [comment]
@skyridertk is that a vagrant related problem? Can you share logs to see why is not loading?

**Comment by skyridertk** [comment]
i tried the production then the development. Both of them were flops.

**Comment by skyridertk** [comment]
Where can i possibly find the logs?

**Comment by mehnomy** [comment]
all your http/https requests errors can be seen here
cat /var/log/nginx/error.log

**Comment by skyridertk** [comment]
cat /var/log/nginx/error.log
2016/05/15 23:45:26 [emerg] 14782#0:
BIO_new_file("/etc/nginx/certs/fbctf.csr") failed (SSL:
error:02001002:system library:fopen:No such file or
directory:fopen('/etc/nginx/certs/fbctf.csr','r') error:2006D080:BIO
routines:BIO_new_file:no such file)
2016/05/15 23:45:26 [emerg] 14802#0:
BIO_new_file("/etc/nginx/certs/fbctf.csr") failed (SSL:
error:02001002:system library:fopen:No such file or
directory:fopen('/etc/nginx/certs/fbctf.csr','r') error:2006D080:BIO
routines:BIO_new_file:no such file)
2016/05/16 13:32:59 [emerg] 1657#0:
BIO_new_file("/etc/nginx/certs/fbctf.csr") failed (SSL:
error:02001002:system library:fopen:No such file or
directory:fopen('/etc/nginx/certs/fbctf.csr','r') error:2006D080:BIO
routines:BIO_new_file:no such file)
2016/05/16 18:52:24 [emerg] 31787#0:
BIO_new_file("/etc/nginx/certs/fbctf.csr") failed (SSL:
error:02001002:system library:fopen:No such file or
directory:fopen('/etc/nginx/certs/fbctf.csr','r') error:2006D080:BIO
routines:BIO_new_file:no such file)
2016/05/16 18:52:25 [emerg] 31812#0:
BIO_new_file("/etc/nginx/certs/fbctf.csr") failed (SSL:
error:02001002:system library:fopen:No such file or
directory:fopen('/etc/nginx/certs/fbctf.csr','r') error:2006D080:BIO
routines:BIO_new_file:no such file)
2016/05/16 19:04:27 [warn] 14499#0: "ssl_stapling" ignored, issuer
certificate not found
2016/05/16 19:04:28 [warn] 14511#0: "ssl_stapling" ignored, issuer
certificate not found
2016/05/16 19:04:28 [emerg] 14511#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/16 19:04:28 [emerg] 14511#0: bind() to 0.0.0.0:443 failed (98:
Address already in use)
2016/05/16 19:04:28 [emerg] 14511#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/16 19:04:28 [emerg] 14511#0: bind() to 0.0.0.0:443 failed (98:
Address already in use)
2016/05/16 19:04:28 [emerg] 14511#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/16 19:04:28 [emerg] 14511#0: bind() to 0.0.0.0:443 failed (98:
Address already in use)
2016/05/16 19:04:28 [emerg] 14511#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/16 19:04:28 [emerg] 14511#0: bind() to 0.0.0.0:443 failed (98:
Address already in use)
2016/05/16 19:04:28 [emerg] 14511#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/16 19:04:28 [emerg] 14511#0: bind() to 0.0.0.0:443 failed (98:
Address already in use)
2016/05/16 19:04:28 [emerg] 14511#0: still could not bind()
2016/05/16 19:37:00 [warn] 13803#0: "ssl_stapling" ignored, issuer
certificate not found
2016/05/16 19:37:00 [warn] 13823#0: "ssl_stapling" ignored, issuer
certificate not found
2016/05/16 19:37:01 [warn] 13827#0: "ssl_stapling" ignored, issuer
certificate not found
2016/05/16 19:37:01 [emerg] 13827#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/16 19:37:01 [emerg] 13827#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/16 19:37:01 [emerg] 13827#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/16 19:37:01 [emerg] 13827#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/16 19:37:01 [emerg] 13827#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/16 19:37:01 [emerg] 13827#0: still could not bind()
2016/05/17 19:09:59 [warn] 1774#0: "ssl_stapling" ignored, issuer
certificate not found
2016/05/18 15:03:46 [warn] 1715#0: "ssl_stapling" ignored, issuer
certificate not found
2016/05/18 16:03:20 [error] 1718#0: *3 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host:
"localhost"
2016/05/18 16:03:21 [error] 1718#0: *3 open()
"/var/www/fbctf/src/favicon.ico" failed (2: No such file or directory),
client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host:
"localhost"
2016/05/18 16:03:21 [error] 1718#0: *3 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000",
host: "localhost"
2016/05/18 16:03:21 [error] 1718#0: *3 open()
"/var/www/fbctf/src/favicon.ico" failed (2: No such file or directory),
client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host:
"localhost"
2016/05/18 16:03:21 [error] 1718#0: *3 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000",
host: "localhost"
2016/05/18 16:03:34 [error] 1718#0: *3 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host:
"localhost"
2016/05/18 16:03:37 [error] 1718#0: *3 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host:
"localhost"
2016/05/18 16:05:30 [error] 1719#0: *10 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host:
"localhost"
2016/05/18 21:39:29 [warn] 1747#0: "ssl_stapling" ignored, issuer
certificate not found
2016/05/19 00:04:27 [error] 1754#0: *6 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host:
"localhost"
2016/05/19 00:04:28 [error] 1754#0: *6 open()
"/var/www/fbctf/src/favicon.ico" failed (2: No such file or directory),
client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host:
"localhost"
2016/05/19 00:04:28 [error] 1754#0: *6 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000",
host: "localhost"
2016/05/19 00:13:13 [error] 1754#0: *10 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host:
"localhost"
2016/05/19 00:44:34 [warn] 11486#0: "ssl_stapling" ignored, issuer
certificate not found
2016/05/19 00:44:34 [emerg] 11486#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/19 00:44:34 [emerg] 11486#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/19 00:44:34 [emerg] 11486#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/19 00:44:34 [emerg] 11486#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/19 00:44:34 [emerg] 11486#0: bind() to 0.0.0.0:80 failed (98:
Address already in use)
2016/05/19 00:44:34 [emerg] 11486#0: still could not bind()
2016/05/19 08:25:22 [warn] 1756#0: "ssl_stapling" ignored, issuer
certificate not found
2016/05/19 10:01:45 [error] 1758#0: *2 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host:
"localhost"
2016/05/19 10:01:45 [error] 1758#0: *2 open()
"/var/www/fbctf/src/favicon.ico" failed (2: No such file or directory),
client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host:
"localhost"
2016/05/19 10:01:45 [error] 1758#0: *2 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000",
host: "localhost"
2016/05/19 10:02:17 [error] 1758#0: *7 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host:
"127.0.0.1"
2016/05/19 10:02:18 [error] 1758#0: *7 open()
"/var/www/fbctf/src/favicon.ico" failed (2: No such file or directory),
client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host:
"127.0.0.1"
2016/05/19 10:02:18 [error] 1758#0: *7 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000",
host: "127.0.0.1"
2016/05/19 10:02:18 [error] 1758#0: *7 open()
"/var/www/fbctf/src/favicon.ico" failed (2: No such file or directory),
client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host:
"127.0.0.1"
2016/05/19 10:02:18 [error] 1758#0: *7 connect() failed (111: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000",
host: "127.0.0.1"
2016/05/19 15:51:45 [warn] 1946#0: "ssl_stapling" ignored, issuer
certificate not found
2016/05/19 15:58:38 [warn] 1777#0: "ssl_stapling" ignored, issuer
certificate not found
2016/05/19 16:04:25 [warn] 1930#0: "ssl_stapling" ignored, issuer
certificate not found
2016/05/19 16:09:43 [warn] 1918#0: "ssl_stapling" ignored, issuer
certificate not found

**Comment by skyridertk** [comment]
Thats the error log

**Comment by mehnomy** [comment]
Hello @skyridertk,
 
- is your apache2 running? could you stop apache2 and then restart nginx.
- when you ran the provision script what was the location of your CRT and KEY files?
- whats your current build, as you have swapped from using production to development and also are you using with vagrant VM or without?
- could you delete everything in your nginx/error.log file and restart nginx and try to connect to the IP address which is located in your ifconfig, as the log file is a little confusing with multiple date stamps in their not knowing what you have resolved and when, just so i can get a clearer picture.

Regards,
Byron

**Comment by skyridertk** [comment]
@Byron Icant locate nginx/error.log

**Comment by mehnomy** [comment]
/var/log/nginx/error.log delete everything inside and do what I mentioned above please. 

Regards,
Byron
