### ISSUE TITLE
[NOT AN ISSUE] Where can I find a list of online CTFs who use FBCTF?

### ISSUE THREAD

**Issue by jcchristian** [facebook/fbctf#593]
-- NOT AN ISSUE --

Does someone know and/or can provide a list of free/open online CTF challenges who use the FBCTF platform?

Thanks.

-- NOT AN ISSUE --

**Comment by stevcoll** [comment]
@jcchristian You can check a site such as ctftime.org to see various CTFs with details. As for FBCTF itself, it's open source and there is no official or unofficial list of CTFs that I'm aware of.
