### ISSUE TITLE
Failed to fetch, provision fails

### ISSUE THREAD

**Issue by theKlabia** [facebook/fbctf#596]
Failing to provision a fresh install of Ubuntu 14.04 (ubuntu-14.04.5-server-amd64.iso).

It looks like it is trying to get http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-i386/, failing, and the script stops.
 
I've followed the installation guide for production manual exactly, no issues.

--- Error ---
 
```
root@ctf:~/fbctf# ./extra/provision.sh -m prod -s $PWD -R
[+] Running apt-get update
Hit http://dl.hhvm.com trusty InRelease
Ign http://us.archive.ubuntu.com trusty InRelease
Get:1 http://us.archive.ubuntu.com trusty-updates InRelease [65.9 kB]
...TRUNCATED
Hit http://us.archive.ubuntu.com trusty Release.gpg
Err http://dl.hhvm.com trusty/main i386 Packages
  404  Not Found [IP: 13.33.151.31 80]
Get:3 http://us.archive.ubuntu.com trusty-updates/main Sources [407 kB]
...TRUNCATED
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Fetched 5,652 kB in 9s (566 kB/s)
W: Failed to fetch http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found [IP: 13.33.151.31 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
root@ctf:~/fbctf#
```

--- End Error ---

So far, I've tried clearing the last downloaded updates:
`sudo rm -vf /var/lib/apt/lists/*`
Didn't work.

I checked out the /etc/apt/sources and nothing seemed wrong. It is only failing to get the i386.

Finally I just commented out the apt-get update in lib.sh and it seemed to get farther but fails again when "## Populating apt-get cache..."

Version:
```
root@ctf:~/fbctf# uname -a
Linux ctf 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by nYrXvcpk2l47ciid** [comment]
I'm having this issue as well. Looks like Cloudfront is down.
[http://www.isitdownrightnow.com/cloudfront.net.html](http://www.isitdownrightnow.com/cloudfront.net.html)

**Comment by theKlabia** [comment]
I seemed to have just completely bypassed it. Provisioning is successful and it seems to work.

edit a few files and comment out these lines:

/etc/apt/sources.list:
(at the bottom)
#deb http://dl.hhvm.com/ubuntu trusty main


fbctf/extra/lib.sh:
function package_repo_update() {
  log "Running apt-get update"
#  sudo DEBIAN_FRONTEND=noninteractive apt-get update
}


fbctf/extra/lib.sh:
  log "Adding HHVM repo"
  #sudo DEBIAN_FRONTEND=noninteractive add-apt-repository "deb http://dl.hhvm.com/ubuntu $(lsb_release -sc) main"

**Comment by nYrXvcpk2l47ciid** [comment]
That worked for me up until
```
[+] Installing HHVM
[+] Installing hhvm
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package hhvm
```

**Comment by nYrXvcpk2l47ciid** [comment]
I see there's not a `binary-i386` directory here... [http://dl.hhvm.com/ubuntu/dists/trusty/main/](http://dl.hhvm.com/ubuntu/dists/trusty/main/)
Just `binary-amd64`.

**Comment by nYrXvcpk2l47ciid** [comment]
Looks like `binary-i386` has been there before (2016), but not anymore.
https://web.archive.org/web/20160925085946/http://dl.hhvm.com/ubuntu/dists/trusty/main/

**Comment by theKlabia** [comment]
Maybe try manually installing it first, uncomment out the change in sources.list too.

```
sudo apt-get install software-properties-common
sudo apt-get install hhvm
```

My steps were the following:

1. Do everything in instructions, then it failed.
2. Comment out the first apt-get update in lib.sh
3. Run again, but still failed
4. Comment out sources.list
5. Run again, but still failed
6. rm -vf /var/lib/apt/lists*
7. apt-get update
8. apt-get upgrade
9. run again, but still failed
10. comment out the second line in lib.sh

Sorry this is so vague. I've been spinning wheels on this for like 2 hours but it seems to still be working finally over here.

**Comment by nYrXvcpk2l47ciid** [comment]
I just uncommented line 235 and ran `quick_setup install prod`. It got a little farther, and probably installed hhvm, but later, after `apt-get update` ran somewhere (line 42 was still commented out), I hit the error: 
`W: Failed to fetch http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-i386/Packages`
Now I'm going to comment line 235 out again and see if it finishes up.

**Comment by nYrXvcpk2l47ciid** [comment]
Same error, probably because I forgot to comment out the source in `/etc/apt/sources.list` again.

**Comment by nYrXvcpk2l47ciid** [comment]
Looks like that did the trick. Still installing.

**Comment by nYrXvcpk2l47ciid** [comment]
Aaaaand it works! So it would appear that the problem lies in installing hhvm. As for how that should be fixed, I'm not so sure.

**Comment by theKlabia** [comment]
well done. It's definitely a problem with Ubuntu. It looks like this is moving to 16.04 soon so this might not even be a priority.

**Comment by javierfigueroa** [comment]
Installed using Ubuntu16.04 x64.
I had to set --allow-unauthenticated for any apt-get command since the hhvm package doesn't seem to be authenticated.

**Comment by wmmw123** [comment]
Hello,

I'm having the same problem.

How did you fix the problem?

Thanks.

**Comment by wmmw123** [comment]
@javierfigueroa 

Does it work on Ubuntu16.04 x64?

The administrator recommends the 14.04 model.

**Comment by stevcoll** [comment]
All,

Apologies for the delay. As HHVM is no longer supported with 14.04, we are indeed moving over to 16.04. This includes some additional provision changes for compatibility with 16.04. The PR should definitely be up this week. Just doing some final testing to ensure Docker and Vagrant are functional.

**Comment by stevcoll** [comment]
Small update: While building the PR, we ran into a TravisCI build error related to sessions. Specifically, the Memcached::getAllKeys function is not operating properly. We've had some issues with getAllKeys in the past, so @justinwray  is implementing a workaround.

**Comment by javierfigueroa** [comment]
@wmmw123 it works in 16.04 x64 as per my comment.  See above for the small change I had to make to get it going.

**Comment by MNWPRO** [comment]
the problem of hhvm is Still unsolved
@stevcoll

**Comment by stevcoll** [comment]
@MNWPRO Yes again we apologize for the delay, there were more incompatibilities with upstream dependencies than we initially thought. We have a lot of install types now in addition to prod/dev such as Vagrant, Docker, Multi-Container Docker, and the new Multi-Server installation.

@justinwray has submitted a PR merging dev into master. Once that gets committed we should be fully 16.04 compatible on all installation types. At that point we will also update the documentation to reflect the new platform!

**Comment by MNWPRO** [comment]
@stevcoll     What time can you solve the problem, please?

**Comment by stevcoll** [comment]
@MNWPRO We allow at least 24 hours for comments and feedback on a PR before merging. In the meantime feel free to pull the Dev branch.

**Comment by MNWPRO** [comment]
Look forward to the emergence of a new version
@stevcoll

**Comment by justinwray** [comment]
The platform has now been updated to support Ubuntu 16.04 exclusively.  This upgrade to Ubuntu 16.04 should resolve all of the installation issues from this thread.

Please see #607 for more details.

Should you encounter installation issues with Ubuntu 16.04, please open a new issue.
