### ISSUE TITLE
No css / js

### ISSUE THREAD

**Issue by jeffhackshaw** [facebook/fbctf#60]
Hi, Trying to install this for a while now. The server itself seems to be running but returns 404 errors for app.js and for fb-ctf.css which makes it look terrible / unusable. 

from firefox:
     GET https://0.0.0.0/static/css/fb-ctf.css [HTTP/1.1 404 Not Found 1ms]
     GET https://0.0.0.0/static/dist/js/app.js [HTTP/1.1 404 Not Found 0ms]

There are no errors during /extra/provision.sh prod $PWD , and this is all that is in hhvm/error.log:

[Sun May 15 17:00:50 2016] [hphp] [17247:7f70b9bff700:3:000001] [] \nNotice: A session had already been started - ignoring session_start() in /var/www/fbctf/src/SessionUtils.php on line 32.

$ ls /var/www/fbctf/src/static/js
     admin.js  clock.js   graphics.js  modal.js    slider.js  widget.js
     app.js    fb-ctf.js  index.js     plugins.js  utils.js

**Comment by javuto** [comment]
Did you install the platform yourself or did you use the provision script? Is it running in a Vagrant machine or a separate server?

**Comment by jeffhackshaw** [comment]
I used the provision script, basically brand new install of ubuntu 14.04 not in vagrant. The first thing I did was basically this:

sudo apt-get install git
git clone https://github.com/facebook/fbctf
cd fbctf
./extra/provision.sh prod $PWD

I created self-signed key, crt and put the paths of them into the provision script when asked.

**Comment by jeffhackshaw** [comment]
Working now
