### ISSUE TITLE
What are the field lengths for the Flag and Quiz Levels? 

### ISSUE THREAD

**Issue by hahnakane** [facebook/fbctf#603]
What are the field lengths (max number of characters) for the following:

-Quiz Level Title
-Quiz Level Question
-Quiz Level Answer

-Flag Level Title
-Flag Level Description
-Flag Level Answer

Knowing this will allow us to know what the character restrictions are when designing quiz and flag challenges.

**Comment by stevcoll** [comment]
@hahnakane Quizzes and Flags are identical in size restrictions per the database schema:

- Level Titles are restricted to 255 characters. Display wise they will line wrap if you have sufficient spaces.
- Level Descriptions are restricted to 65,535 characters. Display wise you should have no issues as they are inside of a scrolling box. I have pasted around a 9,000 word essay into the description field during testing which was quite amusing.
- Level Answers are restricted to 65.535 characters.
