### ISSUE TITLE
Window Size Error - Infinite Loop

### ISSUE THREAD

**Issue by GithubGuy64** [facebook/fbctf#61]
Ran into a bug after installing in development mode where the landing page gets stuck in a continuous loop. The page just states Window is Too Small and it tries to reload over and over and over. Anyone else seen this issue?

Details:

VirtualBox on Yosemite - Ubuntu 14.04 vm
URI - https://<vm_IP>/index.php?page=mobile   <-- i don't know why it thinks its mobile
VM Browser - Chrome (50.0.2661.x)

Thanks

**Comment by gsingh93** [comment]
The "mobile" argument is just stating that your screen width is too small. Did you make the window too small?

We'll look into the refresh issue.

**Comment by GithubGuy64** [comment]
@gsingh93 Thanks for the pointer, do you also know the minimum window size to not be identified as a mobile browser?

**Comment by GithubGuy64** [comment]
@gsingh93 The glitch appears to be isolated to the browser on my VM. Hitting it from my host OS, the CTF platform works fine, Thanks!

**Comment by gsingh93** [comment]
That's weird. The size is 960 pixels, as listed here: https://github.com/facebook/fbctf/blob/5d75a0a5b71d724ff71ac301e99ad5ed99a7947b/src/static/js/app.js#L53

Was your VM browser bigger than that? If you know enough JavaScript to modify the platform, can you print out what the browser size is?
