### ISSUE TITLE
Attachments corrupted when downloading

### ISSUE THREAD

**Issue by jnwarp** [facebook/fbctf#617]
When downloading a file, the file appears broken on certain files.  This is because the file size is being appended to the file when downloading.

__Steps to reproduce:__
1. Upload an attachment as a text file
2. Download attachment through challenge
3. Look at the downloaded file, there is a number appended.

__Screenshot:__
<img src="https://i.imgur.com/5Wgcktt.png">

__Problematic code:__
*src/data/attachments.php*
```php
$data = readfile(Attachment::attachmentsDir.$filename);
```

The read file function appends the length to the end of the file. Instead it should be replaced with `file_get_contents`.

**Comment by hahnakane** [comment]
I have this same issue as well.

**Comment by jnwarp** [comment]
@gsingh93 would you mind taking a look at this issue? I'll be deploying an instance of FBCTF soon, it would really help to make sure that the fix is in one of the branches.

Please let me know if there are any adjustments you'd like me to make.

**Comment by gsingh93** [comment]
Merged that PR, thanks!
