### ISSUE TITLE
facebook/xhp-lib 2.3.0 requires hhvm ~3.6 -> you are running this with PHP and not HHVM

### ISSUE THREAD

**Issue by TheControlFreak** [facebook/fbctf#62]
The title says it all. 

facebook/xhp-lib requires hhvm for install except that 

I have hhvm installed on my ubuntu.

`

  Problem 1
    - facebook/xhp-lib 2.3.0 requires hhvm ~3.6 -> you are running this with PHP and not HHVM.
    - facebook/xhp-lib 2.2.4 requires hhvm ~3.6 -> you are running this with PHP and not HHVM.
    - facebook/xhp-lib 2.2.3 requires hhvm ~3.6 -> you are running this with PHP and not HHVM.
    - facebook/xhp-lib 2.2.2 requires hhvm ~3.6 -> you are running this with PHP and not HHVM.
    - facebook/xhp-lib 2.2.1 requires hhvm * -> you are running this with PHP and not HHVM.
    - facebook/xhp-lib 2.2.0 requires hhvm * -> you are running this with PHP and not HHVM.
    - facebook/xhp-lib 2.1.0 requires hhvm * -> you are running this with PHP and not HHVM.
    - facebook/xhp-lib 2.0.2 requires hhvm * -> you are running this with PHP and not HHVM.
    - facebook/xhp-lib 2.0.1 requires hhvm * -> you are running this with PHP and not HHVM.
    - facebook/xhp-lib 2.0.0 requires hhvm * -> you are running this with PHP and not HHVM.
    - Installation request for facebook/xhp-lib 2.x -> satisfiable by facebook/xhp-lib[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0].`
[
[fulllog.txt](https://github.com/facebook/fbctf/files/265404/fulllog.txt)
](url)

**Comment by kevthehermit** [comment]
Try these

  log "HHVM as PHP systemwide"
  sudo /usr/bin/update-alternatives --install /usr/bin/php php /usr/bin/hhvm 60

  log "Enabling HHVM to start by default"
  sudo update-rc.d hhvm defaults

**Comment by TheControlFreak** [comment]
@kevthehermit I appreciate your help but it's still not working. It's still the same output

**Comment by javuto** [comment]
@TheControlFreak you need to run HHVM 3.13, which is the default package for Ubuntu 14.04 LTS

**Comment by TheControlFreak** [comment]
@javuto I'm running Ubuntu 16.04 LTS and 
overlord@Aspire-V5-472G:~$ hhvm --version
HipHop VM 3.11.1 (rel)
Compiler: 3.11.1+dfsg-1ubuntu1
Repo schema: 2f678922fc70b326c82e56bedc2fc106c2faca61

**Comment by TheControlFreak** [comment]
@javuto I will try manually installing hhvm 3.13

**Comment by gsingh93** [comment]
Please reopen if you're still having issues.
