### ISSUE TITLE
Users are able to login before the game is scheduled to start.

### ISSUE THREAD

**Issue by sbadakhc** [facebook/fbctf#622]
Is it possible to prevent users from logging in before a game is scheduled to restart. Those user who logged in started playing the game and then when the game started their captured states where reset. It would be good to prevent users from logging in until the game has actually started.

**Comment by gsingh93** [comment]
We generally use the controls on the admin page to disable all the challenges before the game starts. This is the approach most CTF platforms use. Does that work for you?

**Comment by sbadakhc** [comment]
Yes that is acceptable.

Thanks.
