### ISSUE TITLE
Usage in commercial settings

### ISSUE THREAD

**Issue by nonewz** [facebook/fbctf#627]
I know this is not a technical issue but I didn't find any contact info to submit this question. I work for a security vendor education team. I would like to use **fbctf** in a course we sell to our customers. Quiz and flag will be about the content covered in the couse. Since this a commercial setting, I would like to know if I could get the permission to do so. 
Thanks for your help.

**Comment by gsingh93** [comment]
Sorry, our license is [Creative Commons Attribution-NonCommercial](https://raw.githubusercontent.com/facebook/fbctf/master/LICENSE), which prohibits this software for commercial use.

**Comment by nonewz** [comment]
Hi, 
I understand and will not use this option. May I suggest you change your page as this suggest commercial use is allowed: 
![image](https://user-images.githubusercontent.com/36957720/36977191-9a9f414a-2080-11e8-879a-aa65cf5c34e7.png)

**Comment by gsingh93** [comment]
This is actually a bug with Github, I can report it to them.
