### ISSUE TITLE
 I can not register to the local server

### ISSUE THREAD

**Issue by overcrash66** [facebook/fbctf#63]
I have installed everything, but when I connect to the server's homepage I can not register..
need help

**Comment by Excis3** [comment]
I had the same issue when installing in production mode.
When i installed as development i had no troubles.

I figured out that curl was missing on a fresh ubuntu 14.04 install, so installed it.
Did the install script again but for development and all worked fine.
:/

**Comment by mpomarole** [comment]
Please post output from provision script and `/var/log/hhvm/error` so we can help you.

**Comment by overcrash66** [comment]
@Excis3 thank you, my problem is resolved :+1:
