### ISSUE TITLE
Self Signed Certs and 502 Bad Gateway

### ISSUE THREAD

**Issue by no1rscyber** [facebook/fbctf#64]
We are very keen to get this into PROD.

All is well until we get to the certificate part. We have created the certs using:

openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout privateKey.key -out certificate.crt

We then enter the path details when the install asks for the cert locations.

All seems to be well but we are now getting a 502 Bad Gateway error.

Any assistance greatly appreciated.

**Comment by mehnomy** [comment]
could you please dump your error log into paste bin:
cat /var/log/nginx/error.log

**Comment by no1rscyber** [comment]
Hi,


Here is our /var/log/nginx/error.log

[http://pastebin.com/6YabjUMC](url)

**Comment by no1rscyber** [comment]
Here is the log

http://pastebin.com/6YabjUMC

**Comment by mehnomy** [comment]
>Quote from gsingh93  
Yea, in prod mode you need to create your own certs. You don't want to be using self-signed certs in production for security reasons.
In dev mode, using a self-signed cert is fine, so we generate it for you.

Errors on Lines 1-10 show that they don't like your self signed Certificates (insecure), my suggestion would be to go to somewhere like name cheap and get yourself a cheap Comodo SSL certificate they take a few minutes to setup.

Warnings on Lines 11-13
Referring to your self signed certificate and your configurations solution can be found here:
http://serverfault.com/questions/567124/nginx-ssl-stapling-ignored-no-ocsp-responder-url-in-the-certificate

Errors on Line 14-63 shows that you most likely haven't configured your Nginx configuration file correctly.

Are you setting this up on a virtual machine with VagrantVM or Ubuntu 14.04, or a virtual server?

**Comment by no1rscyber** [comment]
Setting this up on a real box.

Im tempted to go to a 64bit OS instead of 32bit as others seem to have a similar issue.

I have seen in other posts that using a self signed cert should be OK for intranet type implementations?

**Comment by mehnomy** [comment]
From my knowledge you can't use a 32bit as flow isn't supported - however i could be wrong.

 when you ran ./extra/provision.sh dev $PWD before placing the locations (or after) of your SSL Crt and Key did you see any errors?

Errors such as:
http://i.imgur.com/yMRgZeH.png

**Comment by no1rscyber** [comment]
Thanks for the info, just going to try the 64bit OS to see if that fixes it. Im more than happy to use self signed certs as this will not be going anywhere near the Internet.

**Comment by mehnomy** [comment]
No worries if you have anymore issues just reply back here, we are all here to help.

**Comment by no1rscyber** [comment]
64bit OS did the trick. Seems to be up and running now. 

Thanks.
