### ISSUE TITLE
Fatal Error for undefined method

### ISSUE THREAD

**Issue by CCLDArjun** [facebook/fbctf#665]

**Comment by CCLDArjun** [comment]
Most Recent Version
Ubuntu 18
i havent really tried to fix it 
![screen shot 2019-01-19 at 5 06 19 pm](https://user-images.githubusercontent.com/31632587/51433975-94043600-1c0c-11e9-9afd-ba01f742a665.png)

**Comment by v1ncenth** [comment]
Use Ubuntu 16.04
