### ISSUE TITLE
could not find a distribution template for Kali/n/a

### ISSUE THREAD

**Issue by manisashank** [facebook/fbctf#666]
I want to host a ctf event locally so I thought fbctf is a best platform but when I tried installing it in my kali linux I am encountering an error while adding HHVM repo can anybody help me to fix this...
![IMG_20190319_211709](https://user-images.githubusercontent.com/35716660/54620746-a247c480-4a8c-11e9-9a89-abb7f86692c6.jpg)

**Comment by v1ncenth** [comment]
Use Ubuntu 16.04
