### ISSUE TITLE
Flow server won't start

### ISSUE THREAD

**Issue by mehnomy** [facebook/fbctf#67]
Hello,

I have created a whole wiki on replicating what i have done everything seems to be working i have resolved all issues but one with installing fbctf on a clean Ubuntu 14.04 x64 without using Docker or Vagrant VM.

Wiki Link: https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki

My environment sort of works despite all the images and graphics missing due to the flow server not starting which seems to be halting the js from compiling etc.. 

Environment Link: https://security.rmit.me

**The Flow Error(s) i'm getting is:**
```
- Running "run:flow" (run) task
- Launching Flow server for /var/www/fbctf/src
- Spawned flow server (child pid=28029)
- Logs will go to /tmp/flow/zSvarzSwwwzSfbctfzSsrc.log
- Started a new flow server: -The flow server is not responding (3 retries remaining): [local inference] \Launching Flow server for /var/www/fbctf/src
- Spawned flow server (child pid=28049)
- Logs will go to /tmp/flow/zSvarzSwwwzSfbctfzSsrc.log
- Started a new flow server: |flow is still initializing; this can take some time. [processing] /flow is still initializing; this can take some time. [local inference] -Launching Flow server for /var/www/fbctf/src
- Spawned flow server (child pid=28069)
- Logs will go to /tmp/flow/zSvarzSwwwzSfbctfzSsrc.log
- Error: Failed to start server. The server was killed prematurely with signal 7.
- Could not start Flow server!
```
**I have also tried flow.init afterwards:**
```
root@security:~# flow init
root@security:~# flow
Launching Flow server for /root
Spawned flow server (child pid=28372)
Logs will go to /tmp/flow/zSroot.log
Launching Flow server for /root
Spawned flow server (child pid=28404)
Logs will go to /tmp/flow/zSroot.log
Launching Flow server for /root
Spawned flow server (child pid=28433)
Logs will go to /tmp/flow/zSroot.log
Error: Failed to start server. The server was killed prematurely with signal 7.
Could not start Flow server!
root@security:~# 
```

**Flow Error Log:**
[2016-05-17 04:43:34] Initializing Server (This might take some time)
[2016-05-17 04:43:34] executable=/root/.opam/system/bin/flow
[2016-05-17 04:43:34] version=0.22.1
[2016-05-17 04:43:35] Parsing
/var/www/fbctf/node_modules/flexslider No such file or directory
[2016-05-17 04:43:35] Building package heap
[2016-05-17 04:43:35] Running local inference
--- afterwards ---
[2016-05-17 06:58:59] Initializing Server (This might take some time)
[2016-05-17 06:58:59] executable=/root/.opam/system/bin/flow
[2016-05-17 06:58:59] version=0.22.1
[2016-05-17 06:59:00] Parsing
[2016-05-17 06:59:01] Building package heap
[2016-05-17 06:59:04] Running local inference

**Nginx Error Log:** (both are failed GET Requests)
open() "/var/www/fbctf/src/static/css/fb-ctf.css" failed (2: No such file or directory)
open() "/var/www/fbctf/src/static/dist/js/app.js" failed (2: No such file or directory)

- fb-ctf.css doesn't exist however the scss does in /var/www/fbctf/src/static/css/scss as fb-ctf.scss
- the second error for app.js the pathway is wrong; app is located in /var/www/fbctf/src/static/js/app.js

**hhvm Error Log:**
[Tue May 17 05:16:50 2016] [hphp] [27957:7fe3759ff700:13:000001] [] \nNotice: A session had already been started - ignoring session_start() in /var/www/fbctf/src/SessionUtils.php on line 32

**Two other JS errors more details can be found in the Setup Link below:**
/var/www/fbctf/src/static/js/admin.js
  33:39  error  Parsing error: Unexpected token :

/var/www/fbctf/src/static/js/plugins.js
  51:9  error  Move function declaration to function body root  no-inner-declarations

**The Setup:**
http://pastebin.com/mM6ive8r

**Request:**
Could somebody please provide me a copy of their working `~/.flowconfig` file, as mines currently looking a little empty and it could be the problem.. not entirely sure i have exhausted my knowledge.

current .flowconfig file:
```
[ignore]

[include]

[libs]

[options]
```

Just on the side note i requested access a couple days ago for the small private repository of challenges, if you don't mind checking.

Kind Regards,
Byron Fisher

**Comment by gsingh93** [comment]
1) How much RAM and how many cores do you have in your VM?
2) You should be using our `.flowconfig`: https://github.com/facebook/fbctf/blob/master/src/.flowconfig. The flowconfig you've posted won't work.

We've had a large number of requests for the repository of challenges, and currently going through them.

**Comment by mehnomy** [comment]
We are Currently utilising 2GB of RAM in the VM with an extra 1GB on swap, what would your recommendations be for a production server?

Production environment needs:
In the near on future after getting a complete build up and running with a few custom challenges we will be reproducing this on a dedicated server for hackathons which we run for RMIT Students and other Universities.

the .flowconfig file gets auto deleted after 2-3minutes after hanging/failing to start, thanks for the URL totally forgot to check the src on github.

Cheers,
Byron

**Comment by gsingh93** [comment]
Your server specs seem fine. I think the problem is your flowconfig. Let me know if flow still gives you issues.

**Comment by mehnomy** [comment]
Cheers mate it was just the .flowconfig, 
going to redeploy on a dedicated to see how things go.

Kind Regards,
Byron Fisher

**Comment by colbyjoe1919** [comment]
This has gone too far we are going to all be wage and salary cuts by months end.  We don't need this yahoo let's go make money not toss it.

**Comment by colbyjoe1919** [comment]
Let's move on.  I didn't sign on to be an evil nerd for the prestige.  I got my gold digger hottie wife I'm good.  Let's do someone else.
