### ISSUE TITLE
Cannot choose team shield in Chrome

### ISSUE THREAD

**Issue by davidmoremad** [facebook/fbctf#672]
**FBCTF version** - commit `4ec9b6be404fce1bed6d1066fccf10c4255767bb`
**System/OS** - Ubuntu 18.10 (AWS official AMI)
**Affected browser** - Chrome 74.0.3729.108 (Build oficial) (64 bits)

It's not possible to choose a team shield in the registration form in Chrome, and because of this, it's not possible to register a team.

Doesn't happen in Safari or Firefox and no JS errors on the browser

Refs: @dfernandezvalero

**Comment by v1ncenth** [comment]
See https://github.com/facebook/fbctf/issues/670
