### ISSUE TITLE
Will FBCTF work in a newer version of Ubuntu?

### ISSUE THREAD

**Issue by DLui1** [facebook/fbctf#68]
I have Ubuntu 16.04 installed in virtualbox with FBCTF installed but seem to be getting a "secure connection failed" message when trying to go to the login page with the web address of https://10.10.10.5 . What am I doing wrong? Does FBCTF work in only Ubuntu 14.04 or will it work in any version of Ubuntu higher than 14.04 as well?

**Comment by mehnomy** [comment]
at this point in time it seems to have only been tested in Ubuntu v14.04, so it most likely will not work on any other versions.

Its quite specific in the guide that you must be using Ubuntu v14.04 x64, maybe in the future but not for now it seems.

Regards,
Byron

**Comment by dylanjacob** [comment]
A couple things to check,

Is the IP address on your Ubuntu 16.04 VM actually `10.10.10.5`?  Do an `ifconfig` and see what the actual assigned IP is, and try connecting to `https://<ip address>`.

Also, did you create SSL certificates and point to them during the install process?  If not, try this:

```
# Creates a private RSA key that is 2048 bits
openssl genrsa -out fbctf.key 2048
# Will ask you for several pieces of information in order to generate a Certificate Signing Request (CSR).  The most important being the Common Name if you plan on using a DNS name i.e. fbctf.yourdomain.com
openssl req -new -key fbctf.key -out fbctf.csr
# Using the generated CSR and private key, this command will generate the actual certificate
openssl req -x509 -days 1095 -key fbctf.key -in fbctf.csr -out fbctf.cer
# Moves all of the generated files to the NGINX certs directory.  In an actual production environment you would move the key to a separate directory and restrict access to yourself and the user that NGINX runs as
mv fbctf.* /etc/nginx/certs/.
```

Try re-running the `provision.sh` script and providing the path to the cert (`/etc/nginx/certs/fbctf.cer` and `/etc/nginx/certs/fbctf.key` in the example).  This is how I generated my certificates and, while I do get an error in my browser saying that the certificates are not trusted, I can allow an exception knowing that I generated the certificates.  In an actual production environment, you would create the private key and the CSR as in the instructions, but provide them to an actual Certificate Authority, such as Komodo or Digicert (or one of the many others) and they would provide you the actual cert (`fbctf.cer` in my example).

**Comment by DLui1** [comment]
Thanks for the information, guys. I'm going to install Ubuntu 14.04 in virtualbox and try again.

**Comment by gsingh93** [comment]
The README states that you should used 14.04, so you should use 14.04. The HHVM team does not provide an official HHVM package for 16.04 yet. You can try installing HHVM 3.13 yourself (note this version is higher than the version in the default repos), but we can't guarantee everything will work.

We'll support 16.04 in the near future, but we can't give a timeline.
