### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Ajauregui69** [facebook/fbctf#69]
This are the finale lines when i try to install FBCTF and i try to conect but nothing apear...

[+] Installing Unison 2.48.3
[+] Remember install the same version of unison (2.48.3) in your host machine
[+] Creating DB - fbctf
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[+] Importing schema...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[+] Importing countries...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[+] Importing logos...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[+] Creating user...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[+] DB Connection file
[+] Adding default admin user
[+] The password for admin is: d5022ecdf5685acdfc4dcfc39683254c
/var/www/fbctf/extra/lib.sh: línea 179: hhvm: orden no encontrada
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[+] fbctf deployment is complete! Ready in https://10.10.10.5

please help me

**Comment by dylanjacob** [comment]
I had those errors too.  I edited the variables at the top of my `provision.sh` file to match my MYSQL server setup since I already had MYSQL installed.  I have also noticed that in the `extra` folder there is a `settings.ini.example` file with some variables you can set.  Try renaming this file to `settings.ini` and editing it with appropriate values for `DB_USERNAME` and `DB_PASSWORD`.  Perhaps the `provision.sh` script will utilize those values when setting things up?

Ultimately, those errors mean that the provision process cannot log in to your MYSQL database to set up a new database, user and install the schema.

**Comment by Ajauregui69** [comment]
I couldn't do it.
What if you make a video tuto, that would help alot

**Comment by colbyjoe1919** [comment]
Stop you guys let's just ease up off the guy  already you know give him a
break.  Cease the torturing let's try that yeah I think that will work.

**Comment by Ajauregui69** [comment]
If you do it, you will be the first one

**Comment by agilajah** [comment]
I assume you are running linux(ubuntu) on your machine, kill your mysql process id : 
$ ps -ef | grep mysql
$ kill [proc id]

then, start again.
$ sudo /etc/init.d/mysql start

**Comment by cjrollo** [comment]
The lib.sh helper assumes that mysql needs to be install and will do it. However, the mysql server is *not* started. Similar to the nginx server, the install _mysql() function should have a "restart". Something like...

function install_mysql() {
  local __pwd=$1

  log "Installing MySQL"

  echo "mysql-server-5.5 mysql-server/root_password password $__pwd" | sudo debconf-set-selections
  echo "mysql-server-5.5 mysql-server/root_password_again password $__pwd" | sudo debconf-set-selections
  package mysql-server

 **# Restart mysql-server
  sudo service mysql restart**
}

**Comment by gsingh93** [comment]
If you're still having issues, please reopen.
