### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Pika-Boo** [facebook/fbctf#72]
Have a Ubuntu 14.04 in a VM. In order to provide self signed certificate, created one via:
     sudo openssl req -x509 -nodes -days 365 -newkey rsa -keyout ssl.key -out ssl.crt
Followed the production instructions and gave the crt and key file for ssl.
The setup completes with the admin password and statement fbctf deploment is complete! Ready in https://10.10.10.5. However nothing really loads in 10.10.10.5

Query: Is there an installation error(If so how do i get the error logs and fix the issue) or is there any step I am missing(If so what is it).

Thanks in advance.

**Comment by mehnomy** [comment]
Could you try running the following command to get your IP address:
ifconfig eth0

Once found, copy and paste that to your browser and hit enter.. does it work?

**Comment by Pika-Boo** [comment]
The local IP address open the default apache page. Opening the same link with https doesnt really work

**Comment by Pika-Boo** [comment]
Would stopping apache and hitting the local IP help?

**Comment by mehnomy** [comment]
oohs thats your problem right there, we are using Nginx not apache could you stop Apache and start Nginx and retry.

**Comment by Pika-Boo** [comment]
I guess it is working pretty now. Thanks a ton :+1:
