### ISSUE TITLE
Internet Connectivity Required?

### ISSUE THREAD

**Issue by no1rscyber** [facebook/fbctf#75]
Could I pose a few questions please?

We wish to run this in Production and currently we have managed to successfully implement this to a point.

Does the "./extra/provision.sh prod $PWD" need to be run everytime the server is booted up and used in production?

Does it require Internet access everytime if this is the case?

We would like to build the server, load in our levels and then move it into our lab infrastructure which is air gapped from the Internet.

**Comment by mehnomy** [comment]
**Simple test:**
sudo reboot

wait for it to reboot, open up your browser and go to the IP address is it still working?

I have tested it and it works like a charm,
disconnect the server from internet and repeat the following steps does it work?

Regards,
Byron

**Comment by no1rscyber** [comment]
Changed IP to our internal 10 network and rebooted. Could not connect to server once it had come back up on the new IP.

Had to change it back to dhcp on my internet connected network (192 network) and reboot once again. Server successfully came back online.

Would be useful to move it over to my internal non internet connected network!

**Comment by colbyjoe1919** [comment]
How many times are we going to try one more thing.  Nothing works it's like
he's working with God or something.  That's the only way he could be
stopping us so effectively.  If that's true that means gods real.  And that
means........crap.  uh brb I have to talk to a priest er I'm mean buy some
paste. At the store.   Well looks like we chose the wrong side fellas. Our
bad.  I heard he's forgiving.

**Comment by gsingh93** [comment]
Provisioning only needs to happen once. Off the top of my head, no external network access is necessary as long as you don't add any base levels which our outside your network (we connect to the base levels to see which team is captured them).
