### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Shivam5o** [facebook/fbctf#76]
I have installed in development mode. After installation, password is printed in the console at the end of provisioning. Admin is the user by default. After entering credentials in VM (User & password )
it shows error login incorrect.

**Comment by mehnomy** [comment]
did you install curl?

sudo apt-get update
sudo apt-get install curl

**Comment by Shivam5o** [comment]
Curl is already installed

This is what I get in VM
```
facebookCTF-DEV login: admin
password
login Incorrect
```

**Comment by darkclownstein** [comment]
i also have this problem

**Comment by mehnomy** [comment]
@Shivam5o can you please read the wiki i have created you can only use Ubuntu 14.04 x64:
- [The Wiki](https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki)

@darkclownstein could you please reply back in your own issue.

**Comment by Shivam5o** [comment]
@mehnomy you mean to say i need to install again in production mode with my own SSL certificates?
Development mode won't work?

**Comment by mehnomy** [comment]
@Shivam5o 
**Production Mode:**
- if you need a SSL Certificate you can get a free one from https://letsencrypt.org, it does work with a self signed certificate however its **NOT unrecommended**. Else i would recommend purchasing one from name cheap where you can get a domain for $.88 and a Comodo SSL Certificate for an extra $2 at the cart page.

**Development Mode:**
- You can use a self signed SSL with no issues within dev mode, make sure to use ./extra/provision.sh dev $PWD.

Regards,
Byron

**Comment by Shivam5o** [comment]
Thank You. I will do that.
