### ISSUE TITLE
Country filters are reversed

### ISSUE THREAD

**Issue by Excis3** [facebook/fbctf#77]
Hi,
i have a question regarding the Country management.
When you apply a filter as "Disabled", all Enabled country's are shown and visa versa.
Is this intended or a bug.

![capture](https://cloud.githubusercontent.com/assets/18592596/15321720/85b64326-1c38-11e6-993b-9f6661de159b.PNG)

![capture](https://cloud.githubusercontent.com/assets/18592596/15321731/9a54f1c4-1c38-11e6-96f7-24f326ad408a.PNG)

**Comment by gsingh93** [comment]
Oops. We'll fix. Thanks for the issue :)

**Comment by NMEsearch** [comment]
I don't think this is a bug. The countries listed in the first image are all disabled. The green "ENABLE" button isn't there to show that country's status, it's there to enable the country.

The same, but opposite, can be said for the second image.

**Comment by Excis3** [comment]
Ah, indeed this could be possible.
@gsingh93 is the logic correct?
If so you can close this issue.

**Comment by gsingh93** [comment]
Ah, you're right.

I think we should changed the button though to say the current state of the country, instead of the action that will be taken when clicking the button. So we would change "Enable" to "Disabled" and "Disable" to "Enabled". This has been confusing me from the beginning :P

Are you alright with that @javuto?

**Comment by javuto** [comment]
Yeah, we can do that. Makes sense.

**Comment by javuto** [comment]
This is already implemented here https://github.com/facebook/fbctf/commit/80b5b2cd367ca32acab67f9070865e97115e9b43

**Comment by 15w34r0n3D4y** [comment]
Still not fixed.
