### ISSUE TITLE
Allow longer/shorter game times

### ISSUE THREAD

**Issue by landmanmanc** [facebook/fbctf#78]
Feature request : custom gametime longer then 24 hours.

**Comment by colbyjoe1919** [comment]
A day here is a 1000 years in spirit prison.  So your penance might take a
minute.

**Comment by gsingh93** [comment]
Yea, I was planning on changing this. Thanks for the issue!

**Comment by landmanmanc** [comment]
Would be nice to set custom times, and not just 12/24/48 hours.

**Comment by javuto** [comment]
Implemented in https://github.com/facebook/fbctf/pull/118
