### ISSUE TITLE
I cant make it work

### ISSUE THREAD

**Issue by Ajauregui69** [facebook/fbctf#80]
Please someone help me :(

**Comment by nimdavirus** [comment]
@Ajauregui69 

We need a lot more information.  Screen shots and descriptions of what you can and cannot do, well help us troubleshoot with you.

-Nimdy

**Comment by Ajauregui69** [comment]
i do the install Production way, but when i go to https://10.10.10.5 it doesn't show anything

**Comment by Nimdy** [comment]
Read:

https://github.com/facebook/fbctf/issues/22

I already posted my solutions.

There are many possible issues that could come up and a lot of it sadly is because of the untrained eye. 

They are easy fixes, we can help you troubleshoot through them.

I am going to make a YOUTUBE video tonight and provide a walk through.

**Comment by Ajauregui69** [comment]
LOL untrainded eye..

TNX

**Comment by Nimdy** [comment]
We all have the "untrained eye" right now. All of us will be masters are at a 15 min setup process. I was fumbling all over the place. I spent 3 hours trying to get the script to work and didn't notice the difference between ` and ' .... lol

**Comment by Ajauregui69** [comment]
i really appreciate your help, i hope your video, when you make it please paste the link here pleas :)))))))

**Comment by Ajauregui69** [comment]
@Nimdy i got this error, ` * Restarting nginx nginx                                                                                                      [fail] 
[+] Installing Unison 2.48.3
[+] Remember install the same version of unison (2.48.3) in your host machine
[+] Creating DB - fbctf
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
[+] Importing schema...
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
[+] Importing countries...
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
[+] Importing logos...
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
[+] Creating user...
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
[+] DB Connection file
[+] Adding default admin user
[+] The password for admin is: password
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
[+] fbctf deployment is complete! Ready in https://10.10.10.5`

**Comment by agilajah** [comment]
This is maybe happens because your mysql root-account's password is different from what is actually need. I saw here : https://github.com/facebook/fbctf/blob/master/extra/provision.sh the password is 'root'. Maybe changing yout mysql root-account's password to 'root' can resolve the error.

**Comment by gsingh93** [comment]
If you're still having issues, please reopen.
