### ISSUE TITLE
Scoring with Bases

### ISSUE THREAD

**Issue by wytshadow** [facebook/fbctf#81]
Are there instructions or tutorials on how to setup a basic machine to use as a base level for a king of the hill style CTF? I found the score_base.py script in the extras folder but I am not sure how to use it. what does the fbctf machine need to run to receive points from the compromised base/victim machines? Is the score_base.py script what runs on the compromised machines to tell the fbctf who to give points to? Any help with this topic would be much appreciated.

**Comment by javuto** [comment]
The documentation on how to setup bases is here: https://github.com/facebook/fbctf/wiki/FBCTF-Challenge-Overview
Let us know if you have any questions or encounter issues along the way!

**Comment by gsingh93** [comment]
If you still need help, let us know.
