### ISSUE TITLE
Player Names

### ISSUE THREAD

**Issue by NMEsearch** [facebook/fbctf#86]
I've enabled player names, which allows for input during registration, but once submitted I can't find where to check who was on each team.

In the admin panel under Teams it says "No Team Names" when looking at the 'Names' tab above the team. Also, on the gameboard, when clicking on a team logo in the 'Teams' window nothing is listed under 'team_members'.

Is this a bug?

Hopefully the above makes sense...

**Comment by gsingh93** [comment]
Thanks for the issue! We still need to expose the player names in the UI.

**Comment by javuto** [comment]
One step to fix this has been merged with https://github.com/facebook/fbctf/pull/267, now we need to expose the names in the UI

**Comment by johnny-y-wang** [comment]
Seems like the frontend form is not submitting team data and backend is not doing any validation against 
teamdata settings.
