### ISSUE TITLE
Help with Configuration

### ISSUE THREAD

**Issue by NMEsearch** [facebook/fbctf#87]
Could someone please help me by explaining what some of the admin configuration settings do. I've played around with them all but haven’t noticed much difference.

Under LOGIN, what does STRONG PASSWORDS change?

What do all the setting under GAME do?

Thanks for any help.

**Comment by mehnomy** [comment]
If strongpassword is checked e.g Boolean 1 it requires the following regex:
INSERT INTO `password_types` (field, regex, description) VALUES("1", "/.*^(?=.{8,})(?=.*[a-z])(?=.*[0-9]).*$/", "Length > 8, [a-z] and [0-9]");
INSERT INTO `password_types` (field, regex, description) VALUES("2", "/.*^(?=.{8,})(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).*$/", "Length > 8, [a-z], [A-Z] and [0-9]");
INSERT INTO `password_types` (field, regex, description) VALUES("3", "/.*^(?=.{8,})(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*\W).*$/", "Length > 8, [a-z], [A-Z], [0-9] and Special chars");

if strongpassword is unchecked e.g Boolean 0 then no regex is run so a simple password like 'password' would be accepted.

Kind Regards,
Byron Fisher

**Comment by gsingh93** [comment]
@javuto can you document strong passwords along with some of the other configuration in the wiki?

**Comment by juliannagler** [comment]
Check out the [wiki](https://github.com/facebook/fbctf/wiki) for more information on the admin configuration settings. If you're still facing issues, please create a new issue. Closing this one out.
