### ISSUE TITLE
favicon.ico no such file or directory/ Wont load

### ISSUE THREAD

**Issue by jrobber1** [facebook/fbctf#88]
2016/05/18 08:38:13 [error] 3857#0: *12 open() "/var/www/fbctf/src/favicon.ico" failed (2: No such file or directory), client: 10.10.10.5, server: , request: "GET /favicon.ico HTTP/1.1", host: "10.10.10.5"

Installed with prod no vagrant. Used self signed cert

**Comment by mehnomy** [comment]
Hello @jrobber1,
Do you have any other issues / problems? are you able to load your website still?

The fav icon is just the tiny image you see when you create multiple tabs, more of a deco thing.
If it doesn't exist just simply upload it into your directory.
- https://github.com/facebook/fbctf/blob/master/src/static/img/favicon.png

If you're having multiple issues try following my wiki guide:
https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki

Kind Regards,
Byron Fisher

**Comment by jrobber1** [comment]
The page will not load. That's the only error. I'll look over the wiki. Thanks

Jesse Roberts




On Wed, May 18, 2016 at 8:50 AM -0700, "Byron Fisher" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @jrobber1<https://github.com/jrobber1>,
Do you have any other issues / problems? are you able to load your website still?

The fav icon is just the tiny image you see when you create multiple tabs, more of a deco thing.
If it doesn't exist just simply upload it into your directory.

  *   https://github.com/facebook/fbctf/blob/master/src/static/img/favicon.png

If you're having multiple issues try following my wiki guide:
https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki

Kind Regards,
Byron Fisher

-

**Comment by mehnomy** [comment]
Hey @jrobber1,

The page not loading is a whole other issue then just a tiny favicon, could you copy what the output of the prevision script and paste it into a pastebin and provide the URL in a reply.

I'd suggest running from scratch if you're going to use my wiki so its a clean slate, to insure that your not starting in an environment which may already have issues.

If your issues persist please feel free on replying as we're all here to help.

Kind Regards,
Byron Fisher

**Comment by gsingh93** [comment]
If you're still having an issue please reopen.
