### ISSUE TITLE
Quiz questions

### ISSUE THREAD

**Issue by jrobber1** [facebook/fbctf#91]
It would be great to have a way to upload quiz questions.

**Comment by mehnomy** [comment]
You can create individuals here:
http://i.imgur.com/tadCdrx.png

mmhms good idea though, a CSV is quite plausible to bulk create questions and upload, there are a couple ways to approach this with a button to upload a bulk questions if the title doesn't exist then it will allow them to upload, or using a feed approach is also plausible a little more complicated but it allows the on the fly approach by allowing deleting bulk, editing bulk or creating bulk without the need of having to upload a CSV all the time however much more complicated.

I guess taking taking it in baby steps would be the best approach, any developers interested in undertaking this its not complicated multiple rows within a CSV and insert the data:

**Current code looks like:**
`// Create a quiz level.
  public static async function genCreateQuiz(
    string $title,
    string $question,
    string $answer,
    int $entity_id,
    int $points,
    int $bonus,
    int $bonus_dec,
    string $hint,
    int $penalty
  ): Awaitable<int> {
    $db = await self::genDb();
    $result = await $db->queryf(
      'SELECT id FROM categories WHERE category = %s LIMIT 1',
      'Quiz'
    );
    $category_id = intval(must_have_idx($result->mapRows()[0], 'id'));
    return await self::genCreate(
      'quiz',
      $title,
      $question,
      $entity_id,
      $category_id,
      $points,
      $bonus,
      $bonus_dec,
      $bonus,
      $answer,
      $hint,
      $penalty
    );
  }`

Currently got my head in the mix with the front-end editor, however i can take a look at this next week if there is no rush.

Kind Regards,
Byron Fisher

**Comment by gsingh93** [comment]
Using CSV's to upload levels is on the current roadmap.

**Comment by javuto** [comment]
This will be implemented here: https://github.com/facebook/fbctf/pull/150
