### ISSUE TITLE
Can't run (Gruntfile.js)

### ISSUE THREAD

**Issue by TerminatorXII** [facebook/fbctf#92]
To start the program I've to open Gruntfile.js,
but when I open it, it shows CMD for 0,3s and then it close.
Tried to run with Java, same problem, then with nodejs, same problem

CMD message:
Can't find or run Gruntfile.js

**Comment by mehnomy** [comment]
Hello @TerminatorXII,

I don't really understand why your needing to open the file Gruntfile.js could you try following on a clean Ubuntu 14.04 x64 VM or VPS the instructions on my wiki:
https://github.com/mehnomy/FBCTF-Ubuntu-Setup

If you run into any further issues please feel free to reply.

Kind Regards,
Byron Fisher

**Comment by TerminatorXII** [comment]
> I don't really understand why your needing to open the file Gruntfile.js

It's the only possible way to run it?

**Comment by mehnomy** [comment]
What steps have you done / commands have you executed within your Ubuntu 14.04 x64 environment that have lead you to this problem.

Please note down everything you have done, so i can help you resolve your issues.

Kind Regards,
Byron Fisher

**Comment by TerminatorXII** [comment]
I run it on windows, is that the problem?

**Comment by mehnomy** [comment]
Yes that is the problem i was curious to why you said CMD and not terminal.

The platform requires a Ubuntu 14.04 x64 Operating System, [please read the instructions on the front page.](https://github.com/facebook/fbctf)

[If you require help with the setup please follow my wiki for instructions.](https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki)

Kind Regards,
Byron Fisher

**Comment by TerminatorXII** [comment]
Does Unbutu changes my current operating system? or is it a program?

**Comment by mehnomy** [comment]
**Do not reformat your computer**

Please run Ubuntu 14.04 x64 in a Virtual Machine, software such as [Virtual Box](https://www.virtualbox.org) which is free allows you to create sandboxed environments which do not effect your current Windows operating system it will just take some computer resources when it is activated; resources such as CPU cores, RAM, and storage space all of these are set by you when first creating the Virtual Machine.

Please follow this guide on how to setup a Virtual Box with Ubuntu 14.04 x64 Installed on it:
https://www.youtube.com/watch?v=QkJmahizwO4

Kind Regards,
Byron Fisher

**Comment by TerminatorXII** [comment]
Can't run Unbutu http://prntscr.com/b5nl8x

**Comment by TerminatorXII** [comment]
Googled it, but I can't change it to 64 bit, and checked me bios, but can only test my hardware.. (I have 64 bit system)

**Comment by mehnomy** [comment]
Please refer to:
[Solution](http://askubuntu.com/questions/308937/cannot-install-ubuntu-in-virtualbox-due-to-this-kernel-requires-an-x86-64-cpu)

Kind Regards,
Byron Fisher

**Comment by gsingh93** [comment]
Please reopen if you're having issues. I've heard that Vagrant/VirtualBox on Windows works fine, but I can't confirm myself.
