### ISSUE TITLE
Ability to custom brand the CTF with your name and logo.

### ISSUE THREAD

**Issue by tbowman01** [facebook/fbctf#93]
Could you provide an interface in the admin menu to brand the CTF?
ie.  upload and use a custom logo/icon and change the "Powered by Facebook" 

Temporary work around in order to customize/brand the CTF the logo and file can be found here:
- Logo Location: /fbctf/src/static/svg/icons/social-facebook.svg
- File Location:  /fbctf/src/xhp/Fbbranding.php

If you place your own logo in the same location and update the code you could start to customize the feel.  The /fbctf/src/static/css/scss/_navigation-branding.scss file has the style sheet code to customize the site further.

**Comment by mehnomy** [comment]
This is a non commercial license agreement when using the Platform which has been created and released by Facebook, i don't agree on having a way to change it from being Branded with Facebook since they've have created this amazing platform.

> Facebook CTF retains a Creative Commons (CC) License, which means it can be used by any non-commercial entity for **educational purposes**. The platform was built with education and competition organizers in mind. Dozens of high school and college-level student clubs, national competition organizations, educational institutions, and industry groups have already run successful competitions using the Facebook CTF platform.

When creating an event e.g at a University for instance students would be more engaged and willing to participate seeing the Facebook logo over a unknown logo, and if you were to have a landing page for information then i think thats more then enough.

The site looks amazing as it is, if you really want to customise or if anyone else wanted to change the feel i don't really see the need of providing a admin editor to do such things, when it all can be done via the css.


Kind Regards,
Byron Fisher

**Comment by tbowman01** [comment]
As the intent is for educational purposes with the education and competition organizations in mind.  I interpret this as internal education/competitions among teams.  The suggestion was geared more towards those high school or less tech savvy who do not know where to find the cascading style sheets or how to read where they are linking from.  

For the high school group or possibly even college level the "Powered by Facebook" may have some appeal.  However, in industry, as I have pitched using the platform to management for internal training.  I have recieved multiple comments about Facebook.  That initially is a challenge and may be best addressed with stating that the Facebook CTF retains a Creative Commons (CC) License, which means it can be used by any non-commercial entity for educational purposes. The platform was built with education and competition organizers in mind.

I agree the platform looks great.  I also see some room for growth and possibly forks of it as occasionally happens with open source.  If there is a way to upload multiple questions I can see a possible test bank of questions for the jeopardy style.

In the demo levels (babys_first_bof) it discusses the ability to upload or link to a hosted system where you could have the player download an ova, retrieve some objectives, and return a flag to the system for scoring.  Some questions may have multiple steps to obtain the answer/flag.  

Great discussion point.  Thanks for your comment Byron.

Regards,
Trevor

**Comment by javuto** [comment]
Merged in https://github.com/facebook/fbctf/pull/448

**Comment by jbooz1** [comment]
The custom branding icon sizes get morphed. None of the icons I have tried to import work because they seem to change dimensions when uploading them

**Comment by ElliotWilde** [comment]
Had the same issue, any PNG uploaded got squashed. Seems to only be SVG files that work. 

Try using an online converter, https://svgcreator.com for example.
