### ISSUE TITLE
It doesn't make work!!

### ISSUE THREAD

**Issue by Younet007** [facebook/fbctf#96]
Hi guys, 
I have a problem to access to 10.10.10.5
First i tried to make it with my server, so I run ./extra/provision.sh in prod mode, also I use my own certificate, then I tried to use in VM but I have a problem with the vagrant file, and the access problem persist.
Thanks

**Comment by mehnomy** [comment]
Hello @Younet007,

Please follow my wiki guide with a fresh Ubuntu 14.04 64x.
[My Guide](https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki)

Kind Regards,
Byron Fisher

**Comment by Younet007** [comment]
thanks for your answer, but the problem is always there :)

**Comment by Younet007** [comment]
also I run ubuntu 15.10 x32

**Comment by tbowman01** [comment]
If you run "netstat -an | grep tcp" are you listening on 80 or 443 locally?

**Comment by mehnomy** [comment]
@Younet007 it requires 64bits since some of the main packages e.g flow type requires it. You will continue to have your problems if you do not switch over to Ubuntu 14.04 x64.

Kind Regards,
Byron Fisher

**Comment by Younet007** [comment]
Hi,
I move to ubuntu x64, and I have installed all the pre-requirements, all seems to be fine, until I can't access to 10.10.10.5 th page still blank, any Ideas??
best regards
Joseph

**Comment by mehnomy** [comment]
@Younet007 have you tried ifconfig in the command line and using the IP address?
 - If you have could you please copy your provision output into a paste bin so I can take a look please.

Kind Regards,
Byron Fisher

**Comment by Younet007** [comment]
sould I configure my local interface??

**Comment by Younet007** [comment]
@tbowman01 I'm listening on 80 and 443.

**Comment by mehnomy** [comment]
@Younet007 could you please copy and paste the ifconfig output to here.

Regards,
Byron

**Comment by Younet007** [comment]
Hi,
@mehnomy here the ifconfig output
enp0s3    Link encap:Ethernet  HWaddr 08:00:27:fe:ce:a8  
          inet adr:10.0.2.15  Bcast:10.0.2.255  Masque:255.255.255.0
          adr inet6: fe80::e341:85b1:6bd1:1652/64 Scope:Lien
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Packets reçus:617 erreurs:0 :0 overruns:0 frame:0
          TX packets:898 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:1000 
          Octets reçus:182481 (182.4 KB) Octets transmis:133259 (133.2 KB)

lo        Link encap:Boucle locale  
          inet adr:127.0.0.1  Masque:255.0.0.0
          adr inet6: ::1/128 Scope:Hôte
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          Packets reçus:11915 erreurs:0 :0 overruns:0 frame:0
          TX packets:11915 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:1 
          Octets reçus:938808 (938.8 KB) Octets transmis:938808 (938.8 KB)

**Comment by mehnomy** [comment]
can you try 10.0.2.15 in your browser.

**Comment by Younet007** [comment]
It respnd by a bad gateway

**Comment by mehnomy** [comment]
502? can you stop apache and start nginx

**Comment by Younet007** [comment]
I already did

**Comment by Younet007** [comment]
One more thing when I execute ./extra/provision.sh prod `pwd`, in some point it shows an error : 
  ✔ flow binary test passed successfully
/usr/local/lib
└─┬ flow-bin@0.25.0 
  └─┬ bin-wrapper@3.0.2
    └─┬ download@4.4.3
      └─┬ vinyl-fs@2.4.3
        └─┬ glob-stream@5.3.2
          └─┬ micromatch@2.3.8
            └── braces@1.8.5 

Running "force:eslint" (force) task

Running "force-internal:pre:eslint" (force-internal) task
>> Enable force mode for task eslint.

Running "eslint:dist" (eslint) task

/var/www/fbctf/src/static/js/plugins.js
  51:9  error  Move function declaration to function body root  no-inner-declarations

✖ 1 problem (1 error, 0 warning

**Comment by Younet007** [comment]
I also modify the path in the provision.sh file and restart the nginx service, then I try to access to 10.0.2.15 and the page still blank.
Any more Ideas
Thanks .

**Comment by mehnomy** [comment]
why did you modify the path in the provision script?

**Comment by Younet007** [comment]
the path seems wrong that's why.

**Comment by mehnomy** [comment]
which one of these has the fbctf directory: cd /var/www or /usr/share/nginx/html or /usr/share/nginx/www?

**Comment by Younet007** [comment]
it's /usr/share/nginx/html and I put this path in the provision file

**Comment by mehnomy** [comment]
are you sure your using 64 bit and not 32 bit?

**Comment by Younet007** [comment]
yes I run ubuntu 16.04 x64 in a Virtual machine

**Comment by mehnomy** [comment]
Could you do me a favour can you create a new VM and follow my guide don't use Vagrant VM or anything else, just follow my guide with Virtual Box or similar software:
https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki

Make sure when first running the provision script that you know where your html or www directory is for nginx.

**Comment by Younet007** [comment]
ok I'll try
thanks.

**Comment by Younet007** [comment]
Hello @mehnomy 
I reinstall the ubuntu 16.04 x64 and now I'm going to install the pre-requierements. Any advices
best regards
joseph

**Comment by mehnomy** [comment]
@Younet007 

The only advice i can give you, is make sure to follow my guide very strictly don't give anything follow everything in order, the `index` on the home page has numbers for a reason.
[The Wiki](https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki)

Regards,
Byron

**Comment by gsingh93** [comment]
Please follow the README instructions carefully. Only 64 bit Ubuntu 14.04 is supported at this time. Please reopen if you're still having issues.
