### ISSUE TITLE
possibility to import/export game state

### ISSUE THREAD

**Issue by landmanmanc** [facebook/fbctf#98]
Would be nice to import/export everything that has been added to make a game. For example a game consists of 30 quiz questions, and you are able to export them including the data + flag + points given.

Make's it easier to change game.

**Comment by mehnomy** [comment]
https://github.com/facebook/fbctf/issues/91
> Using CSV's to upload levels is on the current roadmap.

why would you want to export the data/flag/points given?

Kind Regards,
Byron Fisher

**Comment by tbowman01** [comment]
@landmanmanc I agree, it may be beneficial to export the given details to a file.  

However, if there was a way to import/export game data.  Then quickly turn an entire question category on/off that might help with large data sets.

On a slightly different path...  After the CTF has completed, it might be beneficial to provide a customized report for each player.  As this is used for an educational tool, the CTF completion report may include the following data:  final rank, final level, total points obtained, questions answered, possible references to questions answered wrong, etc...

**Comment by mehnomy** [comment]
@tbowman01 thats a really cool suggestion, i will take a look into that as future milestone, after the front-end editor. 👍 
- won't be able to do each player as it is teamwork.

Kind Regards,
Byron Fisher

**Comment by gsingh93** [comment]
Closing since I already stated import/export is in the roadmap.
